# Generated by Django 5.1.7 on 2026-01-06 10:48

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Organisation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EventResourceAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free Access"),
                            ("ticket_only", "Ticket Holder Only"),
                            ("paid", "Paid Access"),
                            ("sponsor_only", "Sponsor Only"),
                            ("speaker_only", "Speaker Only"),
                            ("organizer_only", "Organizer Only"),
                        ],
                        default="ticket_only",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_required", models.BooleanField(default=False)),
                ("visible_before_event", models.BooleanField(default=False)),
                ("visible_during_event", models.BooleanField(default=True)),
                ("visible_after_event", models.BooleanField(default=True)),
                ("days_visible_before", models.IntegerField(default=0)),
                ("days_visible_after", models.IntegerField(default=30)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="EventResourcePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_option", models.CharField(max_length=100)),
                ("purchased_at", models.DateTimeField(default=datetime.datetime.now)),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("auto_expire", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_hours", models.IntegerField(default=24)),
                ("requires_ticket", models.BooleanField(default=False)),
                ("allowed_before_event_hours", models.IntegerField(default=24)),
                ("enable_chat", models.BooleanField(default=True)),
                ("enable_file_sharing", models.BooleanField(default=True)),
                ("enable_voice_chat", models.BooleanField(default=False)),
                ("enable_video_chat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EventShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("internal", "Shared within Platform"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("link", "Copy Link"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("shared_to", models.JSONField(blank=True, default=dict)),
                ("shared_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="EventSocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("platform", models.CharField(blank=True, max_length=50)),
                ("clicks", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_name", models.CharField(max_length=200)),
                ("speaker_bio", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                ("sponsor_details", models.TextField(max_length=1000)),
                ("established_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                ("agreement_details", models.TextField(max_length=2000)),
                ("signed_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit_description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="sponsor_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=200)),
                ("package_details", models.TextField(max_length=1000)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipAgreementDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.CharField(max_length=5000)),
                ("document_file", models.FileField(upload_to="sponsorship_documents/")),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("applicant_contact", models.CharField(max_length=200)),
                ("application_details", models.TextField(max_length=2000)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="approved",
                        max_length=100,
                    ),
                ),
                ("approval_reason", models.TextField(max_length=2000)),
                ("approval_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(upload_to="sponsorship_certificates/"),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_file", models.FileField(upload_to="sponsorship_contracts/")),
                ("signed_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipDowngrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="downgraded",
                        max_length=100,
                    ),
                ),
                ("downgrade_date", models.DateTimeField(auto_now_add=True)),
                ("downgrade_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateTimeField(auto_now_add=True)),
                ("evaluation_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="extended",
                        max_length=100,
                    ),
                ),
                ("extension_date", models.DateTimeField(auto_now_add=True)),
                ("extension_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_message", models.TextField(max_length=2000)),
                ("feedback_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                ("change_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_file", models.FileField(upload_to="sponsorship_invoices/")),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter_file", models.FileField(upload_to="sponsorship_letters/")),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_name", models.CharField(max_length=200)),
                ("level_benefits", models.TextField(max_length=1000)),
                ("level_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recognition_date", models.DateTimeField(auto_now_add=True)),
                ("recognition_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="rejected",
                        max_length=100,
                    ),
                ),
                ("rejection_reason", models.TextField(max_length=2000)),
                ("rejection_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="renewed",
                        max_length=100,
                    ),
                ),
                ("renewal_date", models.DateTimeField(auto_now_add=True)),
                ("renewal_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("report_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipTermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="inactive",
                        max_length=100,
                    ),
                ),
                ("termination_date", models.DateTimeField(auto_now_add=True)),
                ("termination_reason", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="transferred",
                        max_length=100,
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("new_sponsor_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="upgraded",
                        max_length=100,
                    ),
                ),
                ("upgrade_date", models.DateTimeField(auto_now_add=True)),
                ("upgrade_details", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_title", models.CharField(max_length=200)),
                ("survey_description", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EventSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_text", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EventTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Tickets"),
                            ("vip", "VIP Tickets"),
                            ("vvip", "VVIP Tickets"),
                            ("couple", "Couple Tickets"),
                            ("group", "Group Tickets"),
                        ],
                        default="regular",
                        max_length=100,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.IntegerField()),
                ("qr_code", models.FileField(upload_to="events_tickets/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventTicketPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_option", models.CharField(max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("ticket_codes", models.JSONField(default=list)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_transferable", models.BooleanField(default=True)),
                ("transferred_at", models.DateTimeField(blank=True, null=True)),
                ("purchased_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="EventToAnnouncementConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("retain_event", models.BooleanField(default=True)),
                ("converted_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="EventUserReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("misleading", "Misleading Information"),
                            ("scam", "Potential Scam"),
                            ("duplicate", "Duplicate Event"),
                            (
                                "cancelled_not_updated",
                                "Event Cancelled but Not Updated",
                            ),
                            ("fake_event", "Fake Event"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reported_at", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="event_videos/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=2000)),
                ("capacity", models.IntegerField()),
                ("duration", models.DurationField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "booking_deadline",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("attendees_viewable", models.BooleanField(default=False)),
                ("activate_feedback", models.BooleanField(default=True)),
                ("event_date", models.DateTimeField(default=datetime.datetime.now)),
                ("deadline_reached", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("live", "live"),
                            ("inactive", "Inactive"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                            ("deleted", "Deleted"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                            ("upcoming", "Upcoming"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="active",
                        max_length=200,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(default=datetime.datetime.now)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="event_attendees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=500)),
                ("blocked_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBrowserReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("remind_before_minutes", models.IntegerField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_reminders",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_browser_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=300)),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("decided_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventcategory",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collaborator_name", models.CharField(max_length=200)),
                ("collaboration_details", models.TextField(max_length=1000)),
                ("entered_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to="Events.event",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Events.eventcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventEmailReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("remind_before_hours", models.IntegerField()),
                ("email_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_reminders",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_email_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField(default="", max_length=2000)),
                ("rating", models.IntegerField(default=0)),
                (
                    "attendendance_status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("bookmarked", "Bookmarked"),
                            ("attending", "Attending"),
                            ("at_the_event", "Currently at the Event"),
                            ("attended", "Attended"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled on Attending"),
                            ("blocked", "Blocked"),
                            ("disliked", "Disliked"),
                            ("report", "Report"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=200,
                    ),
                ),
                ("viewable", models.BooleanField(default=True)),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFeedbackResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_message", models.TextField(max_length=2000)),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventfeedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=200)),
                ("file_content", models.FileField(upload_to="event_files/")),
                ("description", models.TextField(max_length=5000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_message", models.TextField(max_length=2000)),
                ("follow_up_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventHelpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_support_requests",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_help_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventHelpResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("is_solution", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_responses",
                        to="Events.eventhelprequest",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_event_help_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interested", models.BooleanField(default=True)),
                ("notify_updates", models.BooleanField(default=True)),
                ("marked_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitation_message", models.TextField(max_length=1000)),
                ("sent_on", models.DateTimeField(auto_now_add=True)),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inviter_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="invited_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.BooleanField(default=False)),
                ("comment", models.TextField(max_length=2000, null=True)),
                ("reaction", models.CharField(max_length=2000)),
                ("viewable", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="commenter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLogistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("total_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier", models.CharField(max_length=200)),
                ("delivery_date", models.DateTimeField()),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventMediaCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_outlet", models.CharField(max_length=200)),
                ("coverage_details", models.TextField(max_length=2000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(max_length=200)),
                ("partnership_details", models.TextField(max_length=1000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_manage_tickets", models.BooleanField(default=False)),
                ("can_manage_resources", models.BooleanField(default=False)),
                ("can_manage_logistics", models.BooleanField(default=False)),
                ("can_invite_users", models.BooleanField(default=False)),
                ("can_approve_registrations", models.BooleanField(default=False)),
                ("can_moderate_feedback", models.BooleanField(default=False)),
                ("can_manage_sponsors", models.BooleanField(default=False)),
                ("can_manage_room", models.BooleanField(default=False)),
                ("can_post_announcements", models.BooleanField(default=False)),
                ("can_respond_to_help", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_permissions",
                        to="Events.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_event_perms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="event_photos/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pinned_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promotion_channel", models.CharField(max_length=200)),
                ("promotion_details", models.TextField(max_length=1000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("excited", "Excited"),
                            ("interested", "Interested"),
                            ("attending", "Definitely Attending"),
                            ("maybe", "Maybe Attending"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reactions",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reactions_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendee_status",
                    models.CharField(
                        choices=[
                            ("attendee", "Attendee"),
                            ("host", "Host"),
                            ("guest_speaker", "Guest Speaker"),
                            ("main_speaker", "Main Speaker"),
                            ("sponsor_rep", "Sponsor's Representative"),
                            ("patner_rep", "Patner's Representative"),
                            ("collaborator_rep", "Collaborator's Representative"),
                            ("coordinator", "Coordinator"),
                            ("moderator", "Moderator"),
                            ("organiser", "Organiser"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="attendee",
                        max_length=200,
                    ),
                ),
                (
                    "attendance_permission",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_message", models.CharField(max_length=300)),
                ("reminder_date", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "target",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_title", models.CharField(max_length=200)),
                ("report_content", models.TextField(max_length=5000)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRepost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=500)),
                ("reposted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reposts",
                        to="Events.event",
                    ),
                ),
            ],
        ),
    ]
