# Generated by Django 5.1.7 on 2025-11-07 13:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Organisation", "0002_rename_created_at_organisation_created_on_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=2000)),
                ("capacity", models.IntegerField()),
                ("duration", models.DurationField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "booking_deadline",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 7, 16, 0, 12, 497398)
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 7, 16, 0, 12, 497417)
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("live", "live"),
                            ("inactive", "Inactive"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                            ("deleted", "Deleted"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=200,
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=300)),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("decided_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventcategory",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collaborator_name", models.CharField(max_length=200)),
                ("collaboration_details", models.TextField(max_length=1000)),
                ("entered_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField(max_length=2000)),
                ("rating", models.IntegerField()),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFeedbackResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_message", models.TextField(max_length=2000)),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventfeedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=200)),
                ("file_content", models.FileField(upload_to="event_files/")),
                ("description", models.TextField(max_length=5000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_message", models.TextField(max_length=2000)),
                ("follow_up_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLogistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("total_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier", models.CharField(max_length=200)),
                ("delivery_date", models.DateTimeField()),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventMediaCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_outlet", models.CharField(max_length=200)),
                ("coverage_details", models.TextField(max_length=2000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(max_length=200)),
                ("partnership_details", models.TextField(max_length=1000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="event_photos/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promotion_channel", models.CharField(max_length=200)),
                ("promotion_details", models.TextField(max_length=1000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendee_status",
                    models.CharField(
                        choices=[
                            ("attendee", "Attendee"),
                            ("host", "Host"),
                            ("guest_speaker", "Guest Speaker"),
                            ("main_speaker", "Main Speaker"),
                            ("sponsor_rep", "Sponsor's Representative"),
                            ("patner_rep", "Patner's Representative"),
                            ("collaborator_rep", "Collaborator's Representative"),
                            ("coordinator", "Coordinator"),
                            ("moderator", "Moderator"),
                            ("organiser", "Organiser"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="attendee",
                        max_length=200,
                    ),
                ),
                (
                    "attendance_permission",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_message", models.CharField(max_length=300)),
                ("reminder_date", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "target",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_name", models.CharField(max_length=200)),
                ("speaker_bio", models.TextField(max_length=1000)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="moderator_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "slotted_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="speaker_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                ("sponsor_details", models.TextField(max_length=1000)),
                ("established_on", models.DateField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "sponsor_rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                ("agreement_details", models.TextField(max_length=2000)),
                ("signed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventfile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="named_sponsor",
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organisations_participating",
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit_description", models.TextField(max_length=1000)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="sponsor_logos/")),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=200)),
                ("package_details", models.TextField(max_length=1000)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipAgreementDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.CharField(max_length=5000)),
                ("document_file", models.FileField(upload_to="sponsorship_documents/")),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("applicant_contact", models.CharField(max_length=200)),
                ("application_details", models.TextField(max_length=2000)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="approved",
                        max_length=100,
                    ),
                ),
                ("approval_reason", models.TextField(max_length=2000)),
                ("approval_date", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsorshipapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(upload_to="sponsorship_certificates/"),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_file", models.FileField(upload_to="sponsorship_contracts/")),
                ("signed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipDowngrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="downgraded",
                        max_length=100,
                    ),
                ),
                ("downgrade_date", models.DateTimeField(auto_now_add=True)),
                ("downgrade_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateTimeField(auto_now_add=True)),
                ("evaluation_details", models.TextField(max_length=2000)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="extended",
                        max_length=100,
                    ),
                ),
                ("extension_date", models.DateTimeField(auto_now_add=True)),
                ("extension_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_message", models.TextField(max_length=2000)),
                ("feedback_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_file", models.FileField(upload_to="sponsorship_invoices/")),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter_file", models.FileField(upload_to="sponsorship_letters/")),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_name", models.CharField(max_length=200)),
                ("level_benefits", models.TextField(max_length=1000)),
                ("level_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recognition_date", models.DateTimeField(auto_now_add=True)),
                ("recognition_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="rejected",
                        max_length=100,
                    ),
                ),
                ("rejection_reason", models.TextField(max_length=2000)),
                ("rejection_date", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsorshipapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="renewed",
                        max_length=100,
                    ),
                ),
                ("renewal_date", models.DateTimeField(auto_now_add=True)),
                ("renewal_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("report_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                ("change_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsorshipreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipTermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="inactive",
                        max_length=100,
                    ),
                ),
                ("termination_date", models.DateTimeField(auto_now_add=True)),
                ("termination_reason", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="transferred",
                        max_length=100,
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("new_sponsor_name", models.CharField(max_length=200)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorshipUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="upgraded",
                        max_length=100,
                    ),
                ),
                ("upgrade_date", models.DateTimeField(auto_now_add=True)),
                ("upgrade_details", models.TextField(max_length=2000)),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsponsoragreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_title", models.CharField(max_length=200)),
                ("survey_description", models.TextField(max_length=2000)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(max_length=1000)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsurvey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_text", models.TextField(max_length=2000)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventsurveyquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.eventtag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Tickets"),
                            ("vip", "VIP Tickets"),
                            ("vvip", "VVIP Tickets"),
                            ("couple", "Couple Tickets"),
                            ("group", "Group Tickets"),
                        ],
                        default="regular",
                        max_length=100,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.IntegerField()),
                ("qr_code", models.FileField(upload_to="events_tickets/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="event_videos/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
            ],
        ),
    ]
