# Generated by Django 5.1.7 on 2026-01-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Announcements", "0002_initial"),
        ("Authentication", "0003_initial"),
        ("Events", "0001_initial"),
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
        ("Payment", "0001_initial"),
        ("Resources", "0001_initial"),
        ("Rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrepost",
            name="reposted_to",
            field=models.ManyToManyField(
                blank=True, related_name="reposted_events", to="Rooms.room"
            ),
        ),
        migrations.AddField(
            model_name="eventrepost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_reposts_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventresourceaccess",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventresourceaccess",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_access_controls",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventresourceaccess",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Resources.resource"
            ),
        ),
        migrations.AddField(
            model_name="eventresourcepurchase",
            name="resource_access",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="Events.eventresourceaccess",
            ),
        ),
        migrations.AddField(
            model_name="eventresourcepurchase",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="eventresourcepurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_resource_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventroom",
            name="activated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_event_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventroom",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_room",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_event",
                to="Rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsession",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsession",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventshare",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_shares",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_shared",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsociallink",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="eventsociallink",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="moderator_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="slotted_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventschedule",
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="speaker_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsponsor",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsor",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsor",
            name="sponsor_rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsponsoragreement",
            name="agreement_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventfile"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsoragreement",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsoragreement",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="named_sponsor",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsoragreement",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisations_participating",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorbenefit",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventsponsor"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorlogo",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventsponsor"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorpackage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorpayment",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventsponsor"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipagreementdocument",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipapplication",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipapplication",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipapproval",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsorshipapplication",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipcertificate",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipcontract",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipdowngrade",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipevaluation",
            name="evaluated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipevaluation",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipextension",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipfeedback",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiphistory",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipinvoice",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipletter",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiplevel",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiprecognition",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiprejection",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsorshipapplication",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiprenewal",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipreport",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiphistory",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsorshipreport",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiptermination",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshiptransfer",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsponsorshipupgrade",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsponsoragreement",
            ),
        ),
        migrations.AddField(
            model_name="eventsurvey",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventsurveyquestion",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventsurvey"
            ),
        ),
        migrations.AddField(
            model_name="eventsurveyresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.eventsurveyquestion",
            ),
        ),
        migrations.AddField(
            model_name="eventsurveyresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventtagassignment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventtagassignment",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.eventtag"
            ),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventticketpurchase",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_purchases",
                to="Events.eventticket",
            ),
        ),
        migrations.AddField(
            model_name="eventticketpurchase",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="eventticketpurchase",
            name="transferred_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventticketpurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_event_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventtoannouncementconversion",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Announcements.announcements",
            ),
        ),
        migrations.AddField(
            model_name="eventtoannouncementconversion",
            name="converted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="eventtoannouncementconversion",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcement_conversions",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventuserreport",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_event_reports",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventuserreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_events_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventuserreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_event_reports_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventvideo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="admin_deps",
            field=models.ManyToManyField(blank=True, to="Institution.admindep"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="admissions",
            field=models.ManyToManyField(blank=True, to="Institution.admissions"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="boards",
            field=models.ManyToManyField(blank=True, to="Organisation.board"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="cafeterias",
            field=models.ManyToManyField(blank=True, to="Institution.cafeteria"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="career_offices",
            field=models.ManyToManyField(blank=True, to="Institution.careeroffice"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="centres",
            field=models.ManyToManyField(blank=True, to="Organisation.centre"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="committees",
            field=models.ManyToManyField(blank=True, to="Organisation.committee"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="counsellings",
            field=models.ManyToManyField(blank=True, to="Institution.counselling"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="default_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="departments",
            field=models.ManyToManyField(blank=True, to="Organisation.department"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="direct_message_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="divisions",
            field=models.ManyToManyField(blank=True, to="Organisation.division"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_visibility",
                to="Events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="faculties",
            field=models.ManyToManyField(blank=True, to="Institution.faculty"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="finances",
            field=models.ManyToManyField(blank=True, to="Institution.finance"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="health_services",
            field=models.ManyToManyField(blank=True, to="Institution.healthservices"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="hostels",
            field=models.ManyToManyField(blank=True, to="Institution.hostel"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="hrs",
            field=models.ManyToManyField(blank=True, to="Institution.hr"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="icts",
            field=models.ManyToManyField(blank=True, to="Institution.ict"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="inst_departments",
            field=models.ManyToManyField(blank=True, to="Institution.instdepartment"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="institutes",
            field=models.ManyToManyField(blank=True, to="Organisation.institute"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="institution_branches",
            field=models.ManyToManyField(blank=True, to="Institution.instbranch"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="institutions",
            field=models.ManyToManyField(blank=True, to="Institution.institution"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="legals",
            field=models.ManyToManyField(blank=True, to="Institution.legal"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="libraries",
            field=models.ManyToManyField(blank=True, to="Institution.library"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="marketings",
            field=models.ManyToManyField(blank=True, to="Institution.marketing"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="Organisation.organisation"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="organistion_branches",
            field=models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="other_institution_units",
            field=models.ManyToManyField(
                blank=True, to="Institution.otherinstitutionunit"
            ),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="other_organisation_units",
            field=models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="programmes",
            field=models.ManyToManyField(blank=True, to="Institution.programme"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="programs",
            field=models.ManyToManyField(blank=True, to="Organisation.program"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="projects",
            field=models.ManyToManyField(blank=True, to="Organisation.project"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="registrar_offices",
            field=models.ManyToManyField(blank=True, to="Institution.registraroffice"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.room"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="sections",
            field=models.ManyToManyField(blank=True, to="Organisation.section"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="securities",
            field=models.ManyToManyField(blank=True, to="Institution.security"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="student_affairs",
            field=models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="support_services",
            field=models.ManyToManyField(blank=True, to="Institution.supportservices"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="teams",
            field=models.ManyToManyField(blank=True, to="Organisation.team"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="transports",
            field=models.ManyToManyField(blank=True, to="Institution.transport"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="units",
            field=models.ManyToManyField(blank=True, to="Organisation.unit"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="users_with_access",
            field=models.ManyToManyField(blank=True, to="Authentication.profile"),
        ),
        migrations.AddField(
            model_name="eventvisibility",
            name="vc_offices",
            field=models.ManyToManyField(blank=True, to="Institution.vcoffice"),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_visibility_changed_logs",
                to="Authentication.profile",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="new_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_new_visibility_logs",
                to="Events.eventvisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="previous_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_previous_visibility_logs",
                to="Events.eventvisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_visibility_logs",
                to="Events.event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventblock",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventbrowserreminder",
            index=models.Index(
                fields=["remind_at", "sent"], name="Events_even_remind__125d76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(
                fields=["event", "-created_at"], name="Events_even_event_i_cc1e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(fields=["user"], name="Events_even_user_id_c00a0b_idx"),
        ),
        migrations.AddIndex(
            model_name="eventemailreminder",
            index=models.Index(
                fields=["remind_at", "email_sent"],
                name="Events_even_remind__4838b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventhelprequest",
            index=models.Index(
                fields=["event", "status"], name="Events_even_event_i_e7a426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventinterest",
            index=models.Index(
                fields=["user", "interested"], name="Events_even_user_id_c3e9b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventinterest",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventpermission",
            index=models.Index(
                fields=["event", "user"], name="Events_even_event_i_d2100e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventpermission",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpin",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventreaction",
            index=models.Index(
                fields=["event", "reaction_type"], name="Events_even_event_i_ca2062_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventreaction",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventrepost",
            index=models.Index(
                fields=["user", "-reposted_at"], name="Events_even_user_id_3bfba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresourceaccess",
            index=models.Index(
                fields=["event", "access_type"], name="Events_even_event_i_c28abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresourcepurchase",
            index=models.Index(
                fields=["user", "purchased_at"], name="Events_even_user_id_bb5c8d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventresourcepurchase",
            unique_together={("user", "resource_access")},
        ),
        migrations.AddIndex(
            model_name="eventroom",
            index=models.Index(
                fields=["event", "is_active"], name="Events_even_event_i_5f4c41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventshare",
            index=models.Index(
                fields=["event", "share_type"], name="Events_even_event_i_e15a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketpurchase",
            index=models.Index(
                fields=["user", "ticket"], name="Events_even_user_id_602699_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketpurchase",
            index=models.Index(
                fields=["payment_status"], name="Events_even_payment_880f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventuserreport",
            index=models.Index(
                fields=["status", "-reported_at"], name="Events_even_status_92a3a2_idx"
            ),
        ),
    ]
