# Generated by Django 5.1.7 on 2025-11-07 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 7, 16, 12, 36, 633148)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 7, 16, 12, 36, 633167)
            ),
        ),
    ]
