# Generated by Django 5.1.7 on 2026-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="complexity_level",
            field=models.CharField(
                choices=[
                    ("small", "Small Event"),
                    ("midlevel", "Mid-Level Event"),
                    ("sophisticated", "Sophisticated Event"),
                ],
                default="small",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_location",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("physical", "Physical"),
                    ("hybrid", "Hybrid"),
                ],
                default="physical",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("invite_only", "Invite Only"),
                    ("members_only", "Members Only"),
                    ("students_only", "Students Only"),
                    ("staff_only", "Staff Only"),
                    ("faculty_only", "Faculty Only"),
                    ("department_only", "Department Only"),
                    ("division_only", "Division Only"),
                    ("organisation_only", "Organisation Only"),
                    ("institution_only", "Institution Only"),
                    ("program_only", "Program Only"),
                    ("other_organisation_unit_only", "Other Organisation Unit Only"),
                    ("other_institution_unit_only", "Other Institution Unit Only"),
                ],
                default="public",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
