# Generated by Django 5.1.7 on 2026-01-28 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0003_initial"),
        ("Articles", "0001_initial"),
        ("Events", "0003_event_complexity_level_event_event_location_and_more"),
        ("Payment", "0001_initial"),
        ("Research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAnnouncementLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("promotion", "Event Promotion"),
                            ("update", "Event Update"),
                            ("reminder", "Event Reminder"),
                            ("cancellation", "Cancellation Notice"),
                        ],
                        default="promotion",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_events",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_announcements",
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="event_documents/")),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("requires_ticket", models.BooleanField(default=False)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_documents",
                        to="Events.event",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventArticleLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("preview", "Event Preview"),
                            ("recap", "Event Recap"),
                            ("related", "Related Content"),
                            ("press", "Press Coverage"),
                        ],
                        default="related",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_events",
                        to="Articles.article",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_articles",
                        to="Events.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "article")},
            },
        ),
        migrations.CreateModel(
            name="EventPaymentGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("venue", "Venue Rental"),
                            ("catering", "Catering"),
                            ("equipment", "Equipment"),
                            ("speakers", "Speaker Fees"),
                            ("general", "General Fund"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_payment_groups",
                        to="Events.event",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_events",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "payment_group")},
            },
        ),
        migrations.CreateModel(
            name="EventProductLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("merchandise", "Event Merchandise"),
                            ("equipment", "Equipment/Supplies"),
                            ("recommended", "Recommended Product"),
                            ("sponsor", "Sponsor Product"),
                        ],
                        default="merchandise",
                        max_length=50,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_products",
                        to="Events.event",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_events",
                        to="Payment.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "product")},
            },
        ),
        migrations.CreateModel(
            name="EventResearchLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("presentation_order", models.IntegerField(default=0)),
                ("is_keynote", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_research",
                        to="Events.event",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_events",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["presentation_order"],
                "unique_together": {("event", "research")},
            },
        ),
    ]
