# Generated by Django 5.1.7 on 2025-11-07 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0004_alter_event_booking_deadline_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 531353)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 531373)
            ),
        ),
    ]
