# Generated by Django 5.2.11 on 2026-03-05 06:06

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0005_event_institution_event_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("access", "Page Access"),
                            ("read", "Read/View"),
                            ("share", "Shared"),
                            ("react", "Reacted"),
                            ("download", "Downloaded Material"),
                            ("rsvp", "RSVP"),
                            ("reminder_set", "Reminder Set"),
                            ("ticket_purchase", "Ticket Purchased"),
                            ("comment", "Commented"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "action"],
                        name="Events_even_event_i_c58f86_idx",
                    ),
                    models.Index(
                        fields=["event", "-created_at"],
                        name="Events_even_event_i_eeb95b_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="Events_even_user_id_31546d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventUserReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time_before",
                    models.CharField(
                        choices=[
                            ("1h", "1 Hour Before"),
                            ("2h", "2 Hours Before"),
                            ("3h", "3 Hours Before"),
                            ("6h", "6 Hours Before"),
                            ("12h", "12 Hours Before"),
                            ("1d", "1 Day Before"),
                            ("2d", "2 Days Before"),
                            ("1w", "1 Week Before"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("send_notification", models.BooleanField(default=True)),
                ("send_email", models.BooleanField(default=True)),
                ("send_system_message", models.BooleanField(default=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("system_message_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reminders",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_user_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["remind_at", "notification_sent"],
                        name="Events_even_remind__0740a9_idx",
                    )
                ],
                "unique_together": {("event", "user", "time_before")},
            },
        ),
    ]
