# Generated by Django 5.2.11 on 2026-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0006_eventanalytics_eventuserreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
