# Generated by Django 5.1.7 on 2025-11-09 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0007_alter_event_booking_deadline_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 926707)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 926739)
            ),
        ),
    ]
