# Generated by Django 5.2.11 on 2026-03-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0007_event_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="Events.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="qr_code",
            field=models.FileField(blank=True, null=True, upload_to="events_tickets/"),
        ),
        migrations.CreateModel(
            name="EventSlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("checked_in", "Checked In"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True, default="")),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_bookings",
                        to="Events.event",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="Events.eventticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "booking_status"],
                        name="Events_even_event_i_536963_idx",
                    )
                ],
                "unique_together": {("event", "user")},
            },
        ),
    ]
