# Generated by Django 5.2.11 on 2026-03-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0008_eventticket_is_free_alter_eventticket_event_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="seeking_partners",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="seeking_sponsors",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventslotbooking",
            name="quantity",
            field=models.IntegerField(
                default=1, help_text="Number of units purchased of this ticket/tier"
            ),
        ),
        migrations.CreateModel(
            name="EventMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="event_materials/")),
                ("title", models.CharField(max_length=200)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule / Program"),
                            ("brochure", "Brochure"),
                            ("promo", "Promotional Material"),
                            ("sponsorship", "Sponsorship Deck"),
                            ("other", "Other Material"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. VIP Couple, Group of 10, Student Individual",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Total number of tickets available in this tier"
                    ),
                ),
                (
                    "group_size",
                    models.IntegerField(
                        default=1,
                        help_text="Number of people this ticket admits (e.g., 2 for couple)",
                    ),
                ),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                (
                    "custom_criteria",
                    models.CharField(
                        blank=True,
                        help_text="Specific string criteria if needed",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_tiers",
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventslotbooking",
            name="ticket_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tier_bookings",
                to="Events.tickettier",
            ),
        ),
        migrations.CreateModel(
            name="EventInteractionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Page View"),
                            ("share", "Shared Event"),
                            ("ticket_click", "Clicked to Buy Tickets"),
                            ("sponsor_click", "Clicked Sponsor Info"),
                            ("partner_click", "Clicked Partner Info"),
                            ("material_download", "Downloaded Material"),
                        ],
                        max_length=50,
                    ),
                ),
                ("viewer_age", models.IntegerField(blank=True, null=True)),
                (
                    "viewer_location_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "viewer_location_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0, help_text="For active views, how long they stayed"
                    ),
                ),
                (
                    "referring_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_analytics",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "interaction_type", "timestamp"],
                        name="Events_even_event_i_077725_idx",
                    )
                ],
            },
        ),
    ]
