# Generated by Django 5.1.7 on 2025-11-11 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0009_alter_event_booking_deadline_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 11, 16, 16, 12, 1549)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 11, 16, 16, 12, 1566)
            ),
        ),
    ]
