# Generated by Django 5.2.11 on 2026-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0009_event_seeking_partners_event_seeking_sponsors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_covers/"),
        ),
    ]
