# Generated by Django 5.2.11 on 2026-04-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0010_event_cover_image"),
        ("Funding", "0010_alter_business_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_events",
                to="Funding.business",
            ),
        ),
    ]
