# Generated by Django 5.2.11 on 2026-05-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0011_event_event_organizer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-time_stamp"]},
        ),
    ]
