# Generated by Django 5.1.7 on 2025-11-13 12:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0013_alter_event_booking_deadline_alter_event_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfeedback",
            name="attendendance_status",
            field=models.CharField(
                choices=[
                    ("interested", "Interested"),
                    ("bookmarked", "Bookmarked"),
                    ("attending", "Attending"),
                    ("at_the_event", "Currently at the Event"),
                    ("attended", "Attended"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled on Attending"),
                    ("blocked", "Blocked"),
                    ("disliked", "Disliked"),
                    ("report", "Report"),
                    ("neutral", "Neutral"),
                ],
                default="neutral",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eventfeedback",
            name="like",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 13, 15, 32, 41, 458386)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 13, 15, 32, 41, 458449)
            ),
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitation_message", models.TextField(max_length=1000)),
                ("sent_on", models.DateTimeField(auto_now_add=True)),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_review", "On Reveiwal Stage"),
                            ("disqualified", "Disqualified"),
                            ("inactive", "Inactive"),
                            ("renewed", "Renewed"),
                            ("extended", "Extended"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inviter_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="invited_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_title", models.CharField(max_length=200)),
                ("report_content", models.TextField(max_length=5000)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Events.event",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
