# Generated by Django 5.2.11 on 2026-06-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0014_seed_event_categories"),
        ("Organisation", "0008_organisation_portal_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsponsorshipapplication",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Organisation.organisation",
            ),
        ),
    ]
