# Generated by Django 5.1.7 on 2025-11-16 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0015_alter_event_booking_deadline_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 16, 13, 13, 19, 572930)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 16, 13, 13, 19, 571784)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 16, 13, 13, 19, 572473)
            ),
        ),
    ]
