# Generated by Django 5.2.11 on 2026-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0016_sponsor_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventslotbooking",
            name="attendee_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventslotbooking",
            name="attendee_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="eventslotbooking",
            name="attendee_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="eventslotbooking",
            name="attendee_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
