# Generated by Django 5.1.7 on 2025-11-17 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0016_event_scheduled_time_alter_event_booking_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="deadline_reached",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 17, 13, 25, 52, 552681)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 17, 13, 25, 52, 552741)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 17, 13, 25, 52, 552895)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("live", "live"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                    ("postponed", "Postponed"),
                    ("deleted", "Deleted"),
                    ("draft", "Draft"),
                    ("archived", "Archived"),
                    ("upcoming", "Upcoming"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("ongoing", "Ongoing"),
                ],
                default="active",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="eventfeedback",
            name="feedback",
            field=models.TextField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="eventfeedback",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
