# Generated by Django 5.1.7 on 2025-11-19 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0017_event_deadline_reached_alter_event_booking_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 7, 57, 36, 560985)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 7, 57, 36, 561024)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 7, 57, 36, 561138)
            ),
        ),
    ]
