# Generated by Django 5.1.7 on 2025-11-19 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0019_alter_event_booking_deadline_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 250309)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 250384)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 250636)
            ),
        ),
    ]
