# Generated by Django 5.2.11 on 2026-06-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rebuild_event_organizer_column(apps, schema_editor):
    """
    Repoint Events_event.event_organizer_id from Funding.business (uuid PK)
    to Events_organizerprofile (bigint PK). Postgres cannot CAST uuid to
    bigint, and old uuid values reference businesses, not organizer
    profiles, so the column is dropped and recreated as an empty bigint
    FK column.
    """
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            """
            DO $$
            DECLARE r RECORD;
            BEGIN
                FOR r IN
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = '"Events_event"'::regclass
                      AND contype = 'f'
                      AND conname LIKE '%%event_organizer_id%%'
                LOOP
                    EXECUTE format('ALTER TABLE "Events_event" DROP CONSTRAINT %%I', r.conname);
                END LOOP;
            END $$;
            """
        )
        schema_editor.execute('ALTER TABLE "Events_event" DROP COLUMN "event_organizer_id"')
        schema_editor.execute('ALTER TABLE "Events_event" ADD COLUMN "event_organizer_id" bigint NULL')
        schema_editor.execute(
            'ALTER TABLE "Events_event" ADD CONSTRAINT "Events_event_event_organizer_id_fk" '
            'FOREIGN KEY ("event_organizer_id") '
            'REFERENCES "Events_organizerprofile" ("id") '
            'DEFERRABLE INITIALLY DEFERRED'
        )
        schema_editor.execute(
            'CREATE INDEX "Events_event_event_organizer_id_idx" '
            'ON "Events_event" ("event_organizer_id")'
        )
    else:
        schema_editor.execute('ALTER TABLE "Events_event" DROP COLUMN "event_organizer_id"')
        schema_editor.execute('ALTER TABLE "Events_event" ADD COLUMN "event_organizer_id" bigint NULL')


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0019_event_booking_uuid_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("bio", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizer_avatars/"
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("is_open_for_partnership", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer Profile",
                "verbose_name_plural": "Organizer Profiles",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="event",
                    name="event_organizer",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to="Events.organizerprofile",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rebuild_event_organizer_column,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
        ),
        migrations.CreateModel(
            name="SponsorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="sponsor_logos/"
                    ),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("website", models.URLField(blank=True, default="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. $1k-$5k per event",
                        max_length=100,
                    ),
                ),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor Profile",
                "verbose_name_plural": "Sponsor Profiles",
            },
        ),
    ]
