# Generated by Django 5.2.11 on 2026-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0022_partnershipinvitation_sponsorapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendance",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="location",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organizer_covers/"
            ),
        ),
    ]
