# Generated by Django 5.2.11 on 2026-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0023_eventattendance_category_eventattendance_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerfollow",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
