# Generated by Django 5.1.7 on 2025-11-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0023_alter_event_booking_deadline_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 453000)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 453021)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 453127)
            ),
        ),
    ]
