# Generated by Django 5.2.11 on 2026-06-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0025_sponsorfollow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsurveyquestion",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For multiple choice: list of option strings. For rating: [min, max]",
            ),
        ),
        migrations.AddField(
            model_name="eventsurveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Response"),
                    ("multiple_choice", "Multiple Choice"),
                    ("rating", "Rating Scale"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventSurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_title", models.CharField(max_length=200)),
                (
                    "template_description",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                (
                    "questions_data",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of {question_text, question_type, options} objects",
                    ),
                ),
                (
                    "is_platform",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-built platform templates visible to all",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_platform", "-created_at"],
            },
        ),
    ]
