# Generated by Django 5.1.7 on 2025-11-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0027_remove_eventfeedback_like_eventlike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventlike",
            old_name="created_at",
            new_name="created_on",
        ),
    ]
