# Generated by Django 5.1.7 on 2025-11-26 15:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        ("Events", "0028_rename_created_at_eventlike_created_on"),
        (
            "Institution",
            "0005_admindep_staff_admissions_staff_cafeteria_staff_and_more",
        ),
        ("Organisation", "0010_alter_board_members_alter_centre_members_and_more"),
        ("Rooms", "0053_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="event_date",
        ),
        migrations.AddField(
            model_name="event",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="EventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_deps",
                    models.ManyToManyField(blank=True, to="Institution.admindep"),
                ),
                (
                    "admissions",
                    models.ManyToManyField(blank=True, to="Institution.admissions"),
                ),
                ("boards", models.ManyToManyField(blank=True, to="Organisation.board")),
                (
                    "cafeterias",
                    models.ManyToManyField(blank=True, to="Institution.cafeteria"),
                ),
                (
                    "career_offices",
                    models.ManyToManyField(blank=True, to="Institution.careeroffice"),
                ),
                (
                    "centres",
                    models.ManyToManyField(blank=True, to="Organisation.centre"),
                ),
                (
                    "committees",
                    models.ManyToManyField(blank=True, to="Organisation.committee"),
                ),
                (
                    "counsellings",
                    models.ManyToManyField(blank=True, to="Institution.counselling"),
                ),
                (
                    "default_rooms",
                    models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
                ),
                (
                    "departments",
                    models.ManyToManyField(blank=True, to="Organisation.department"),
                ),
                (
                    "direct_message_rooms",
                    models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
                ),
                (
                    "divisions",
                    models.ManyToManyField(blank=True, to="Organisation.division"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_visibility",
                        to="Events.event",
                    ),
                ),
                (
                    "faculties",
                    models.ManyToManyField(blank=True, to="Institution.faculty"),
                ),
                (
                    "finances",
                    models.ManyToManyField(blank=True, to="Institution.finance"),
                ),
                (
                    "health_services",
                    models.ManyToManyField(blank=True, to="Institution.healthservices"),
                ),
                (
                    "hostels",
                    models.ManyToManyField(blank=True, to="Institution.hostel"),
                ),
                ("hrs", models.ManyToManyField(blank=True, to="Institution.hr")),
                ("icts", models.ManyToManyField(blank=True, to="Institution.ict")),
                (
                    "inst_departments",
                    models.ManyToManyField(blank=True, to="Institution.instdepartment"),
                ),
                (
                    "institutes",
                    models.ManyToManyField(blank=True, to="Organisation.institute"),
                ),
                (
                    "institution_branches",
                    models.ManyToManyField(blank=True, to="Institution.instbranch"),
                ),
                (
                    "institutions",
                    models.ManyToManyField(blank=True, to="Institution.institution"),
                ),
                ("legals", models.ManyToManyField(blank=True, to="Institution.legal")),
                (
                    "libraries",
                    models.ManyToManyField(blank=True, to="Institution.library"),
                ),
                (
                    "marketings",
                    models.ManyToManyField(blank=True, to="Institution.marketing"),
                ),
                (
                    "organisations",
                    models.ManyToManyField(blank=True, to="Organisation.organisation"),
                ),
                (
                    "organistion_branches",
                    models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
                ),
                (
                    "other_institution_units",
                    models.ManyToManyField(
                        blank=True, to="Institution.otherinstitutionunit"
                    ),
                ),
                (
                    "other_organisation_units",
                    models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
                ),
                (
                    "programmes",
                    models.ManyToManyField(blank=True, to="Institution.programme"),
                ),
                (
                    "programs",
                    models.ManyToManyField(blank=True, to="Organisation.program"),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, to="Organisation.project"),
                ),
                (
                    "registrar_offices",
                    models.ManyToManyField(
                        blank=True, to="Institution.registraroffice"
                    ),
                ),
                ("rooms", models.ManyToManyField(blank=True, to="Rooms.room")),
                (
                    "sections",
                    models.ManyToManyField(blank=True, to="Organisation.section"),
                ),
                (
                    "securities",
                    models.ManyToManyField(blank=True, to="Institution.security"),
                ),
                (
                    "student_affairs",
                    models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
                ),
                (
                    "support_services",
                    models.ManyToManyField(
                        blank=True, to="Institution.supportservices"
                    ),
                ),
                ("teams", models.ManyToManyField(blank=True, to="Organisation.team")),
                (
                    "transports",
                    models.ManyToManyField(blank=True, to="Institution.transport"),
                ),
                ("units", models.ManyToManyField(blank=True, to="Organisation.unit")),
                (
                    "users_with_access",
                    models.ManyToManyField(blank=True, to="Authentication.profile"),
                ),
                (
                    "vc_offices",
                    models.ManyToManyField(blank=True, to="Institution.vcoffice"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_visibility_changed_logs",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "new_visibility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_new_visibility_logs",
                        to="Events.eventvisibility",
                    ),
                ),
                (
                    "previous_visibility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_previous_visibility_logs",
                        to="Events.eventvisibility",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_visibility_logs",
                        to="Events.event",
                    ),
                ),
            ],
        ),
    ]
