# Generated by Django 5.1.7 on 2025-11-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0030_event_attendees_event_attendees_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendees_counter",
        ),
    ]
