# Generated by Django 5.1.7 on 2025-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0031_remove_event_attendees_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="activate_feedback",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees_viewable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventfeedback",
            name="viewable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventlike",
            name="viewable",
            field=models.BooleanField(default=True),
        ),
    ]
