# Generated by Django 5.1.7 on 2026-01-03 09:43

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0033_comment_status_completedtask_status_and_more"),
        ("Events", "0032_event_activate_feedback_event_attendees_viewable_and_more"),
        ("Payment", "0004_individualshare_product_usersubscription_and_more"),
        ("Resources", "0019_visibility_operation_state"),
        ("Rooms", "0074_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHelpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_support_requests",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_help_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventHelpResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("is_solution", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_responses",
                        to="Events.eventhelprequest",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_event_help_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interested", models.BooleanField(default=True)),
                ("notify_updates", models.BooleanField(default=True)),
                ("marked_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_manage_tickets", models.BooleanField(default=False)),
                ("can_manage_resources", models.BooleanField(default=False)),
                ("can_manage_logistics", models.BooleanField(default=False)),
                ("can_invite_users", models.BooleanField(default=False)),
                ("can_approve_registrations", models.BooleanField(default=False)),
                ("can_moderate_feedback", models.BooleanField(default=False)),
                ("can_manage_sponsors", models.BooleanField(default=False)),
                ("can_manage_room", models.BooleanField(default=False)),
                ("can_post_announcements", models.BooleanField(default=False)),
                ("can_respond_to_help", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_permissions",
                        to="Events.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_event_perms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pinned_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("excited", "Excited"),
                            ("interested", "Interested"),
                            ("attending", "Definitely Attending"),
                            ("maybe", "Maybe Attending"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reactions",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reactions_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRepost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=500)),
                ("reposted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reposts",
                        to="Events.event",
                    ),
                ),
                (
                    "reposted_to",
                    models.ManyToManyField(
                        blank=True, related_name="reposted_events", to="Rooms.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reposts_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventResourceAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free Access"),
                            ("ticket_only", "Ticket Holder Only"),
                            ("paid", "Paid Access"),
                            ("sponsor_only", "Sponsor Only"),
                            ("speaker_only", "Speaker Only"),
                            ("organizer_only", "Organizer Only"),
                        ],
                        default="ticket_only",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_required", models.BooleanField(default=False)),
                ("visible_before_event", models.BooleanField(default=False)),
                ("visible_during_event", models.BooleanField(default=True)),
                ("visible_after_event", models.BooleanField(default=True)),
                ("days_visible_before", models.IntegerField(default=0)),
                ("days_visible_after", models.IntegerField(default=30)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_access_controls",
                        to="Events.event",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Resources.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventResourcePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_option", models.CharField(max_length=100)),
                ("purchased_at", models.DateTimeField(default=datetime.datetime.now)),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="Events.eventresourceaccess",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.transactiontoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_resource_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("auto_expire", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_hours", models.IntegerField(default=24)),
                ("requires_ticket", models.BooleanField(default=False)),
                ("allowed_before_event_hours", models.IntegerField(default=24)),
                ("enable_chat", models.BooleanField(default=True)),
                ("enable_file_sharing", models.BooleanField(default=True)),
                ("enable_voice_chat", models.BooleanField(default=False)),
                ("enable_video_chat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_event_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_room",
                        to="Events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_event",
                        to="Rooms.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("internal", "Shared within Platform"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("link", "Copy Link"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("shared_to", models.JSONField(blank=True, default=dict)),
                ("shared_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_shares",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("platform", models.CharField(blank=True, max_length=50)),
                ("clicks", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTicketPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_option", models.CharField(max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("ticket_codes", models.JSONField(default=list)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_transferable", models.BooleanField(default=True)),
                ("transferred_at", models.DateTimeField(blank=True, null=True)),
                ("purchased_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_purchases",
                        to="Events.eventticket",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.transactiontoken",
                    ),
                ),
                (
                    "transferred_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_event_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventToAnnouncementConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("retain_event", models.BooleanField(default=True)),
                ("converted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_conversions",
                        to="Events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventUserReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("misleading", "Misleading Information"),
                            ("scam", "Potential Scam"),
                            ("duplicate", "Duplicate Event"),
                            (
                                "cancelled_not_updated",
                                "Event Cancelled but Not Updated",
                            ),
                            ("fake_event", "Fake Event"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reported_at", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_event_reports",
                        to="Events.event",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_events_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_event_reports_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=500)),
                ("blocked_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="EventBrowserReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("remind_before_minutes", models.IntegerField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_reminders",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_browser_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["remind_at", "sent"],
                        name="Events_even_remind__125d76_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to="Events.event",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Events.eventcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-created_at"],
                        name="Events_even_event_i_cc1e3a_idx",
                    ),
                    models.Index(
                        fields=["user"], name="Events_even_user_id_c00a0b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventEmailReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("remind_before_hours", models.IntegerField()),
                ("email_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_reminders",
                        to="Events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_email_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["remind_at", "email_sent"],
                        name="Events_even_remind__4838b0_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="eventhelprequest",
            index=models.Index(
                fields=["event", "status"], name="Events_even_event_i_e7a426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventinterest",
            index=models.Index(
                fields=["user", "interested"], name="Events_even_user_id_c3e9b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventinterest",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventpermission",
            index=models.Index(
                fields=["event", "user"], name="Events_even_event_i_d2100e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventpermission",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpin",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventreaction",
            index=models.Index(
                fields=["event", "reaction_type"], name="Events_even_event_i_ca2062_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventreaction",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventrepost",
            index=models.Index(
                fields=["user", "-reposted_at"], name="Events_even_user_id_3bfba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresourceaccess",
            index=models.Index(
                fields=["event", "access_type"], name="Events_even_event_i_c28abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresourcepurchase",
            index=models.Index(
                fields=["user", "purchased_at"], name="Events_even_user_id_bb5c8d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventresourcepurchase",
            unique_together={("user", "resource_access")},
        ),
        migrations.AddIndex(
            model_name="eventroom",
            index=models.Index(
                fields=["event", "is_active"], name="Events_even_event_i_5f4c41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventshare",
            index=models.Index(
                fields=["event", "share_type"], name="Events_even_event_i_e15a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketpurchase",
            index=models.Index(
                fields=["user", "ticket"], name="Events_even_user_id_602699_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketpurchase",
            index=models.Index(
                fields=["payment_status"], name="Events_even_payment_880f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventuserreport",
            index=models.Index(
                fields=["status", "-reported_at"], name="Events_even_status_92a3a2_idx"
            ),
        ),
    ]
