# Generated by Django 5.1.7 on 2026-02-03 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("institution_id", models.UUIDField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(
                        help_text="Fallback if no org link", max_length=255
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("responsibilities", models.TextField(blank=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                ("location", models.CharField(max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead/Manager"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("design", "Design & Creative"),
                            ("writing", "Writing & Content"),
                            ("marketing", "Marketing"),
                            ("finance", "Finance & Accounting"),
                            ("legal", "Legal"),
                            ("admin", "Administrative"),
                            ("education", "Education & Training"),
                            ("engineering", "Engineering"),
                            ("healthcare", "Healthcare"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_careers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Career Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(help_text="Skills and qualifications needed"),
                ),
                ("pay_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pay_timing",
                    models.CharField(
                        choices=[
                            ("before", "Payment Before Work"),
                            ("after", "Payment After Completion"),
                            ("milestone", "Milestone-based Payment"),
                            ("negotiable", "Negotiable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("design", "Design & Creative"),
                            ("writing", "Writing & Content"),
                            ("marketing", "Marketing"),
                            ("finance", "Finance & Accounting"),
                            ("legal", "Legal"),
                            ("admin", "Administrative"),
                            ("education", "Education & Training"),
                            ("engineering", "Engineering"),
                            ("healthcare", "Healthcare"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Remote or specific location",
                        max_length=255,
                    ),
                ),
                ("is_remote", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_gigs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_gigs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCareerPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("gig", "Looking for Gigs"),
                            ("employment", "Looking for Employment"),
                            ("recruit", "Looking to Hire"),
                            ("both", "Both Gigs and Employment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industries",
                    models.JSONField(
                        default=list, help_text="List of preferred industries"
                    ),
                ),
                ("skills", models.JSONField(default=list, help_text="User's skills")),
                (
                    "preferred_pay_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "preferred_pay_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "preferred_job_types",
                    models.JSONField(
                        default=list, help_text="Full-time, part-time, etc."
                    ),
                ),
                ("is_remote_only", models.BooleanField(default=False)),
                ("preferred_locations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cover_letter", models.TextField()),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="career_resumes/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("interview", "Interview Scheduled"),
                            ("offered", "Offer Extended"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for reviewers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="Careers.careeropportunity",
                    ),
                ),
            ],
            options={
                "unique_together": {("career", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="GigApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cover_letter", models.TextField()),
                (
                    "proposed_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gig_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="Careers.gig",
                    ),
                ),
            ],
            options={
                "unique_together": {("gig", "applicant")},
            },
        ),
    ]
