# Generated by Django 5.2.11 on 2026-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeropportunity",
            name="clicks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="careeropportunity",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="careeropportunity",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gig",
            name="clicks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gig",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gig",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
