# Generated by Django 5.2.11 on 2026-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Careers", "0003_careeropportunity_image_url_gig_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeropportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("draft", "Draft"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
