# Generated by Django 5.1.7 on 2026-02-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0001_initial"),
        ("Institution", "0005_institutionmember_title"),
        (
            "Organisation",
            "0004_remove_board_organistaion_remove_centre_organistaion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="Organisation.organisation",
            ),
        ),
    ]
