# Generated by Django 5.2.11 on 2026-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0003_article_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="read_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
