# Generated by Django 5.2.11 on 2026-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0004_article_read_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
