# Generated by Django 5.1.7 on 2026-01-07 09:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Announcements", "0002_initial"),
        ("Events", "0001_initial"),
        ("Institution", "0001_initial"),
        ("Resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=5000)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="direct_messages/files"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("not_sent", "Not Sent"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("link", "Link"),
                            ("announcement", "Announcement"),
                            ("task", "Task"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                (
                    "message_origin",
                    models.CharField(
                        choices=[("original", "Original"), ("forwarded", "Forwarded")],
                        default="original",
                        max_length=50,
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_on", models.DateTimeField(default=datetime.datetime.now)),
                ("read_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectMessageRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "announcements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_announcements",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "announcements_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_announcements_requests",
                        to="Announcements.announcementsrequest",
                    ),
                ),
                (
                    "completed_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_completed_tasks",
                        to="Announcements.completedtask",
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="dm_room_events", to="Events.event"
                    ),
                ),
                (
                    "file_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_file_responses",
                        to="Announcements.fileresponse",
                    ),
                ),
                (
                    "forwarded_messages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="forwarded_in_dm_rooms",
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True,
                        related_name="linked_in_dm_rooms",
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="dm_rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "pins",
                    models.ManyToManyField(
                        blank=True, related_name="dm_room_pins", to="Announcements.pin"
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_replies",
                        to="Announcements.reply",
                    ),
                ),
                (
                    "reposts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_reposts",
                        to="Announcements.reposts",
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_resources",
                        to="Resources.resource",
                    ),
                ),
                (
                    "task_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_task_responses",
                        to="Announcements.taskresponse",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_tasks",
                        to="Announcements.task",
                    ),
                ),
                (
                    "texts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_texts",
                        to="Announcements.text",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="directmessage",
            name="dm_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="Rooms.directmessageroom",
            ),
        ),
        migrations.CreateModel(
            name="ForwadingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forwarded_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "direct_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_code",
                    models.CharField(
                        default="4C4E2975F0",
                        editable=False,
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("description", models.TextField(max_length=255, null=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                ("capacity_counter", models.IntegerField(default=0)),
                ("capacity_quota", models.IntegerField(default=0)),
                (
                    "operation_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("deleted", "Deleted"),
                            ("suspended", "Suspended"),
                            ("under_review", "Under Review"),
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sensored", "Sensored"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "text_priority",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators_only", "Admins and Moderators Only"),
                            ("all_members", "All Members"),
                            ("creator_only", "Creator Only"),
                        ],
                        default="creator",
                        max_length=200,
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_admins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "announcements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_announcements",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "announcements_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_announcements_requests",
                        to="Announcements.announcementsrequest",
                    ),
                ),
                (
                    "completed_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_completed_tasks",
                        to="Announcements.completedtask",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="room_events", to="Events.event"
                    ),
                ),
                (
                    "file_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_file_responses",
                        to="Announcements.fileresponse",
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="institution_related_to_room",
                        to="Institution.institution",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_moderators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organisation_related_to_room",
                        to="Institution.institution",
                    ),
                ),
                (
                    "past_memmbers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_past_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pins",
                    models.ManyToManyField(
                        blank=True, related_name="room_pins", to="Announcements.pin"
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_replies",
                        to="Announcements.reply",
                    ),
                ),
                (
                    "reposts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_reposts",
                        to="Announcements.reposts",
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_resources",
                        to="Resources.resource",
                    ),
                ),
                (
                    "task_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_task_responses",
                        to="Announcements.taskresponse",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="room_tasks", to="Announcements.task"
                    ),
                ),
                (
                    "text",
                    models.ManyToManyField(
                        blank=True, related_name="room_texts", to="Announcements.text"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefaultRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_code",
                    models.CharField(
                        default="84168679F1",
                        editable=False,
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(max_length=255, null=True)),
                ("inst_or_org_name", models.CharField(max_length=255)),
                (
                    "reference_object_code",
                    models.CharField(default="None", max_length=255),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "invitation_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("capacity_counter", models.IntegerField(default=0)),
                (
                    "operation_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("deleted", "Deleted"),
                            ("suspended", "Suspended"),
                            ("under_review", "Under Review"),
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sensored", "Sensored"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "text_priority",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators_only", "Admins and Moderators Only"),
                            ("all_members", "All Members"),
                            ("creator_only", "Creator Only"),
                        ],
                        default="creator",
                        max_length=200,
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admin_default_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "announcements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_announcements",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "announcements_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_announcements_requests",
                        to="Announcements.announcementsrequest",
                    ),
                ),
                (
                    "completed_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_completed_tasks",
                        to="Announcements.completedtask",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_events",
                        to="Events.event",
                    ),
                ),
                (
                    "file_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_file_responses",
                        to="Announcements.fileresponse",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_default_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_moderators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "past_memmbers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_past_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_pins",
                        to="Announcements.pin",
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_replies",
                        to="Announcements.reply",
                    ),
                ),
                (
                    "reposts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_reposts",
                        to="Announcements.reposts",
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_resources",
                        to="Resources.resource",
                    ),
                ),
                (
                    "task_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_task_responses",
                        to="Announcements.taskresponse",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_tasks",
                        to="Announcements.task",
                    ),
                ),
                (
                    "text",
                    models.ManyToManyField(
                        blank=True,
                        related_name="default_room_texts",
                        to="Announcements.text",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True, related_name="default_sub_rooms", to="Rooms.room"
                    ),
                ),
            ],
        ),
    ]
