# Generated by Django 5.1.7 on 2025-11-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="0d805cbc368b4b9d8ec0b5d572690e16",
                editable=False,
                max_length=200,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="DefaultRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_code",
                    models.CharField(
                        default="bbb99f1415564b4fa637fdd247af82bb",
                        editable=False,
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(max_length=255, null=True)),
                ("institution", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_default_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
