# Generated by Django 5.1.7 on 2026-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="BCED1FA3E8", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="27AC2C33ED", editable=False, max_length=200, unique=True
            ),
        ),
    ]
