# Generated by Django 5.1.7 on 2026-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0002_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="7B81D9EB74", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="7F11973F1F", editable=False, max_length=200, unique=True
            ),
        ),
    ]
