# Generated by Django 5.1.7 on 2025-11-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0002_room_room_code_defaultroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="8F0E8CDF3B", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="60C9D88E53", editable=False, max_length=200, unique=True
            ),
        ),
    ]
