# Generated by Django 5.1.1 on 2025-02-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_room_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='member',
            new_name='members',
        ),
    ]
