# Generated by Django 5.1.7 on 2026-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0003_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="C2BE9F6BC5", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="DF8AA0B156", editable=False, max_length=200, unique=True
            ),
        ),
    ]
