# Generated by Django 5.1.7 on 2026-02-01 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0003_alter_organisation_abbreviation_and_more"),
        ("Rooms", "0004_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="organisation",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisation_related_to_room",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=200, unique=True
            ),
        ),
    ]
