# Generated by Django 5.1.7 on 2025-11-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0004_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="9A91704E04", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="AFA845BC79", editable=False, max_length=200, unique=True
            ),
        ),
    ]
