# Generated by Django 5.1.7 on 2026-02-01 13:01
# Fixed: cannot cast UUID to bigint — drop and recreate the M2M table

import uuid
from django.db import migrations, models


def forwards(apps, schema_editor):
    """Drop the old M2M join table that references Institution (UUID PK)
    so Django can recreate it pointing to Organisation (bigint PK)."""
    connection = schema_editor.connection
    # Check if the old M2M table exists before trying to drop
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT EXISTS ("
            "  SELECT FROM information_schema.tables "
            "  WHERE table_name = 'Rooms_room_organisation'"
            ");"
        )
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute('DROP TABLE "Rooms_room_organisation" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0003_alter_organisation_abbreviation_and_more"),
        ("Rooms", "0004_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=200, unique=True
            ),
        ),
        # Step 1: Remove the old M2M field that points to Institution (UUID)
        migrations.RemoveField(
            model_name="room",
            name="organisation",
        ),
        # Step 2: Run the forward function to drop the table if it still exists
        migrations.RunPython(forwards, migrations.RunPython.noop),
        # Step 3: Re-add the M2M field pointing to Organisation (bigint)
        migrations.AddField(
            model_name="room",
            name="organisation",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisation_related_to_room",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=200, unique=True
            ),
        ),
    ]
