# Generated by Django 5.2.11 on 2026-02-12 14:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0005_alter_defaultroom_room_code_alter_room_organisation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTyping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "dm_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_users",
                        to="Rooms.directmessageroom",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_users",
                        to="Rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["room", "expires_at"],
                        name="Rooms_roomt_room_id_16faa8_idx",
                    ),
                    models.Index(
                        fields=["dm_room", "expires_at"],
                        name="Rooms_roomt_dm_room_856478_idx",
                    ),
                ],
            },
        ),
    ]
