# Generated by Django 5.1.7 on 2026-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0006_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="1E9B4CEF54", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="ECF010D444", editable=False, max_length=200, unique=True
            ),
        ),
    ]
