# Generated by Django 5.1.7 on 2026-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0008_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="C5F24C96AD", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="306A76D627", editable=False, max_length=200, unique=True
            ),
        ),
    ]
