# Generated by Django 5.1.7 on 2026-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_alter_defaultroom_room_code_alter_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultroom',
            name='room_code',
            field=models.CharField(default='8D4A13B8A1', editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='3FAE48C8AA', editable=False, max_length=200, unique=True),
        ),
    ]
