# Generated by Django 5.1.7 on 2026-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0009_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="072A195EDE", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="A9FE637AC2", editable=False, max_length=200, unique=True
            ),
        ),
    ]
