# Generated by Django 5.1.7 on 2025-11-11 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0009_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="57A2750A08", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="8FB850EA4A", editable=False, max_length=200, unique=True
            ),
        ),
    ]
