# Generated by Django 5.1.7 on 2026-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0009_alter_defaultroom_room_code_alter_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultroom',
            name='room_code',
            field=models.CharField(default='D8931B8DB8', editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='20C3DAD691', editable=False, max_length=200, unique=True),
        ),
    ]
