# Generated by Django 5.1.7 on 2025-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0016_alter_announcements_schedule_time_and_more"),
        ("Events", "0010_alter_event_booking_deadline_alter_event_date"),
        ("Rooms", "0010_room_admins_alter_defaultroom_room_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="announcements",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_announcements",
                to="Announcements.announcements",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="announcements_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_announcements_requests",
                to="Announcements.announcementsrequest",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="completed_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_completed_tasks",
                to="Announcements.completedtask",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="room_events", to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="file_responses",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_file_responses",
                to="Announcements.fileresponse",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pins",
            field=models.ManyToManyField(
                blank=True, related_name="room_pins", to="Announcements.pin"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="replies",
            field=models.ManyToManyField(
                blank=True, related_name="room_replies", to="Announcements.reply"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="reposts",
            field=models.ManyToManyField(
                blank=True, related_name="room_reposts", to="Announcements.reposts"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="task_responses",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_task_responses",
                to="Announcements.taskresponse",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="room_tasks", to="Announcements.task"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="text",
            field=models.ManyToManyField(
                blank=True, related_name="room_texts", to="Announcements.text"
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="BD7CDCF584", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="0F6929C02D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
