# Generated by Django 5.1.7 on 2026-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0010_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="19BA4C2C05", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="3BB9F134BE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
