# Generated by Django 5.1.7 on 2026-01-23 05:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0003_initial"),
        ("Events", "0002_initial"),
        ("Resources", "0002_initial"),
        ("Rooms", "0011_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="room_avatars/"),
        ),
        migrations.AddField(
            model_name="room",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="room_covers/"),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="83554AFC0C", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="64B7352225", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="RoomChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="room_chat_files/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_enabled", models.BooleanField(default=True)),
                (
                    "chat_permission",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("all_members", "All Members"),
                        ],
                        default="all_members",
                        max_length=50,
                    ),
                ),
                (
                    "who_can_add_members",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("all_members", "All Members"),
                        ],
                        default="admins_only",
                        max_length=50,
                    ),
                ),
                (
                    "who_can_edit_info",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("all_members", "All Members"),
                        ],
                        default="admins_only",
                        max_length=50,
                    ),
                ),
                (
                    "who_can_send_media",
                    models.CharField(
                        choices=[
                            ("admins_only", "Admins Only"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("all_members", "All Members"),
                        ],
                        default="all_members",
                        max_length=50,
                    ),
                ),
                ("allow_opinion_tagging", models.BooleanField(default=True)),
                ("allow_message_forwarding", models.BooleanField(default=True)),
                ("show_forward_source", models.BooleanField(default=True)),
                ("is_discoverable", models.BooleanField(default=True)),
                ("require_approval_to_join", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="Rooms.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=5000)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("event", "Event"),
                            ("task", "Task"),
                            ("resource", "Resource"),
                            ("announcement", "Announcement"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("is_forwarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_in_chats",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "delivered_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delivered_room_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_in_chats",
                        to="Events.event",
                    ),
                ),
                (
                    "forwarded_from_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forwarded_chats",
                        to="Rooms.room",
                    ),
                ),
                (
                    "forwarded_from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forwarded_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forwards",
                        to="Rooms.roomchat",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_room_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="Rooms.roomchat",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_in_chats",
                        to="Resources.resource",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="Rooms.room",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_in_chats",
                        to="Announcements.task",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chat_messages",
                        to="Rooms.roomchatfile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "created_at"],
                        name="Rooms_roomc_room_id_b11569_idx",
                    ),
                    models.Index(
                        fields=["sender", "created_at"],
                        name="Rooms_roomc_sender__8d719a_idx",
                    ),
                    models.Index(
                        fields=["room", "is_deleted"],
                        name="Rooms_roomc_room_id_828d96_idx",
                    ),
                ],
            },
        ),
    ]
