# Generated by Django 5.1.7 on 2025-11-11 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Announcements",
            "0017_choice_sub_question_fileresponse_sub_question_and_more",
        ),
        ("Events", "0011_alter_event_booking_deadline_alter_event_date"),
        ("Rooms", "0011_room_announcements_room_announcements_requests_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultroom",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_default_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="announcements",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_announcements",
                to="Announcements.announcements",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="announcements_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_announcements_requests",
                to="Announcements.announcementsrequest",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="completed_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_completed_tasks",
                to="Announcements.completedtask",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="default_room_events", to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="file_responses",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_file_responses",
                to="Announcements.fileresponse",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="pins",
            field=models.ManyToManyField(
                blank=True, related_name="default_room_pins", to="Announcements.pin"
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="replies",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_replies",
                to="Announcements.reply",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="reposts",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_reposts",
                to="Announcements.reposts",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="task_responses",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_task_responses",
                to="Announcements.taskresponse",
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="default_room_tasks", to="Announcements.task"
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="text",
            field=models.ManyToManyField(
                blank=True, related_name="default_room_texts", to="Announcements.text"
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="F002304E80", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="65A3FE3AEE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
