# Generated by Django 5.1.7 on 2025-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0012_defaultroom_admins_defaultroom_announcements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="CB740DB64D", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="B25A78BCD4", editable=False, max_length=200, unique=True
            ),
        ),
    ]
