# Generated by Django 5.1.7 on 2025-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0014_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultroom",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="default_sub_rooms", to="Rooms.room"
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="235A2D6904", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="B7C64D1CD6", editable=False, max_length=200, unique=True
            ),
        ),
    ]
