# Generated by Django 5.1.7 on 2025-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0015_defaultroom_rooms_alter_defaultroom_room_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="2A5C4FB27A", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="F28B32E56D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
