# Generated by Django 5.1.7 on 2025-11-17 10:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0023_alter_announcements_schedule_time_and_more"),
        ("Events", "0017_event_deadline_reached_alter_event_booking_deadline_and_more"),
        ("Rooms", "0017_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="B6A1683957", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="F96462DE79", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=5000)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="direct_messages/files"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("not_sent", "Not Sent"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("file", "File"), ("link", "Link")],
                        default="text",
                        max_length=50,
                    ),
                ),
                (
                    "message_origin",
                    models.CharField(
                        choices=[("original", "Original"), ("forwarded", "Forwarded")],
                        default="original",
                        max_length=50,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 17, 13, 25, 52, 671806)
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectMessageRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "announcements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_announcements",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "announcements_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_announcements_requests",
                        to="Announcements.announcementsrequest",
                    ),
                ),
                (
                    "completed_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_completed_tasks",
                        to="Announcements.completedtask",
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="dm_room_events", to="Events.event"
                    ),
                ),
                (
                    "file_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_file_responses",
                        to="Announcements.fileresponse",
                    ),
                ),
                (
                    "forwarded_messages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="forwarded_in_dm_rooms",
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True,
                        related_name="linked_in_dm_rooms",
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="dm_rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "pins",
                    models.ManyToManyField(
                        blank=True, related_name="dm_room_pins", to="Announcements.pin"
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_replies",
                        to="Announcements.reply",
                    ),
                ),
                (
                    "reposts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_reposts",
                        to="Announcements.reposts",
                    ),
                ),
                (
                    "task_responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_task_responses",
                        to="Announcements.taskresponse",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_tasks",
                        to="Announcements.task",
                    ),
                ),
                (
                    "texts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dm_room_texts",
                        to="Announcements.text",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="directmessage",
            name="dm_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="Rooms.directmessageroom",
            ),
        ),
        migrations.CreateModel(
            name="ForwadingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forwarded_on",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 17, 13, 25, 52, 672811)
                    ),
                ),
                (
                    "direct_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Rooms.directmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
