# Generated by Django 5.1.7 on 2025-11-19 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0019_directmessage_delivered_on_directmessage_read_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="88867E2CFC", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 32, 51, 697757)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("link", "Link"),
                    ("announcement", "Announcement"),
                    ("task", "Task"),
                ],
                default="text",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 32, 51, 697782)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 32, 51, 697695)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 32, 51, 698934)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="5748664715", editable=False, max_length=200, unique=True
            ),
        ),
    ]
