# Generated by Django 5.1.7 on 2025-11-19 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0020_alter_defaultroom_room_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="D88DA7DEA4", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 400323)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 400350)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 400247)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 9, 44, 19, 401956)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="695F4C6481", editable=False, max_length=200, unique=True
            ),
        ),
    ]
