# Generated by Django 5.1.7 on 2025-11-20 17:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0005_remove_resourcevisibility_created_at_and_more"),
        ("Rooms", "0021_alter_defaultroom_room_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultroom",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_resources",
                to="Resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="directmessageroom",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="dm_room_resources", to="Resources.resource"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="room_resources", to="Resources.resource"
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 924028)
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="56A577FAF2", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 955054)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 955079)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 954996)
            ),
        ),
        migrations.AlterField(
            model_name="directmessageroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 938936)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 956448)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 914098)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="BC92565BEB", editable=False, max_length=200, unique=True
            ),
        ),
    ]
