# Generated by Django 5.1.7 on 2025-11-20 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0023_alter_defaultroom_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 794443)
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="8DBF8F2E67", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 832990)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 833005)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 832956)
            ),
        ),
        migrations.AlterField(
            model_name="directmessageroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 818067)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 834083)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 772415)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="1358B615FE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
