# Generated by Django 5.1.7 on 2025-11-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0024_alter_defaultroom_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 515898)
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="5BEBB5CEB5", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 536478)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 536490)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 536450)
            ),
        ),
        migrations.AlterField(
            model_name="directmessageroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 526991)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 537232)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 504839)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="3118AE0D59", editable=False, max_length=200, unique=True
            ),
        ),
    ]
