# Generated by Django 5.1.7 on 2025-11-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0026_alter_defaultroom_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 874831)
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="DF959DE695", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="delivered_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 902280)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="read_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 902297)
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 902241)
            ),
        ),
        migrations.AlterField(
            model_name="directmessageroom",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 885545)
            ),
        ),
        migrations.AlterField(
            model_name="forwadinglog",
            name="forwarded_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 903617)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 13, 47, 57, 863604)
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="9D09AEC71F", editable=False, max_length=200, unique=True
            ),
        ),
    ]
