# Generated by Django 5.1.7 on 2025-11-21 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0004_alter_admindep_created_at_and_more"),
        ("Rooms", "0028_alter_defaultroom_created_on_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="institution",
        ),
        migrations.AddField(
            model_name="room",
            name="institutions",
            field=models.ManyToManyField(
                blank=True,
                related_name="institution_related_to_room",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organisation",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisation_related_to_room",
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="E768A46DE9", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="room_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="room_members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="2CED3A06BE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
