# Generated by Django 5.1.7 on 2025-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0029_remove_room_institution_room_institutions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="5F0E0DBDA4", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="049C0A1F2B", editable=False, max_length=200, unique=True
            ),
        ),
    ]
