# Generated by Django 5.1.7 on 2025-11-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0030_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="BF10F420C1", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="0E090DB3AC", editable=False, max_length=200, unique=True
            ),
        ),
    ]
