# Generated by Django 5.1.7 on 2025-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0033_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="40C6522E9B", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="CE0A4DD1C6", editable=False, max_length=200, unique=True
            ),
        ),
    ]
