# Generated by Django 5.1.7 on 2025-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0034_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="62A6D18C76", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="C337913E51", editable=False, max_length=200, unique=True
            ),
        ),
    ]
