# Generated by Django 5.1.7 on 2025-11-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0036_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="955F620857", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="146361C1CF", editable=False, max_length=200, unique=True
            ),
        ),
    ]
