# Generated by Django 5.1.7 on 2025-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0039_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="ECEB169230", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="B99B6185DE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
