# Generated by Django 5.1.7 on 2025-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0044_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="475FFE48D0", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="3561E1287A", editable=False, max_length=200, unique=True
            ),
        ),
    ]
