# Generated by Django 5.1.7 on 2025-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0046_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="defaultroom",
            old_name="institution",
            new_name="inst_or_org_name",
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="reference_object_code",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="4E05B846A4", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="14869238D7", editable=False, max_length=200, unique=True
            ),
        ),
    ]
