# Generated by Django 5.1.7 on 2025-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0047_rename_institution_defaultroom_inst_or_org_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="CDF3453FD1", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="23F4AB89A4", editable=False, max_length=200, unique=True
            ),
        ),
    ]
