# Generated by Django 5.1.7 on 2025-11-25 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0048_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultroom",
            name="capacity_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_moderators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="past_memmbers",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_room_past_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="capacity_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="capacity_quota",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="room_moderators", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="past_memmbers",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_past_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="2F9ADFF394", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="1E529C8CD6", editable=False, max_length=200, unique=True
            ),
        ),
    ]
