# Generated by Django 5.1.7 on 2025-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0049_defaultroom_capacity_counter_defaultroom_moderators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="EB5B7ACA09", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="0AF81E98EF", editable=False, max_length=200, unique=True
            ),
        ),
    ]
