# Generated by Django 5.1.7 on 2025-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0050_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="774C09AD16", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="E26D0481F6", editable=False, max_length=200, unique=True
            ),
        ),
    ]
