# Generated by Django 5.1.7 on 2025-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0054_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="8550B0EAB6", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="04E517A41D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
