# Generated by Django 5.1.7 on 2025-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0056_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="71931B3D29", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="6C51AD0D22", editable=False, max_length=200, unique=True
            ),
        ),
    ]
