# Generated by Django 5.1.7 on 2025-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0057_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="33182FD299", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="CC24203757", editable=False, max_length=200, unique=True
            ),
        ),
    ]
