# Generated by Django 5.1.7 on 2025-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0059_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="67A1A736BA", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="A96BE21253", editable=False, max_length=200, unique=True
            ),
        ),
    ]
