# Generated by Django 5.1.7 on 2025-12-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0065_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="C315E015F9", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="F409BB88D2", editable=False, max_length=200, unique=True
            ),
        ),
    ]
