# Generated by Django 5.1.7 on 2025-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0066_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="843F398909", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="79541B70F5", editable=False, max_length=200, unique=True
            ),
        ),
    ]
