# Generated by Django 5.1.7 on 2025-12-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0067_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="C9CCA969F2", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="18A6049FDE", editable=False, max_length=200, unique=True
            ),
        ),
    ]
