# Generated by Django 5.1.7 on 2025-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0068_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultroom",
            name="operation_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("under_review", "Under Review"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sensored", "Sensored"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="defaultroom",
            name="text_priority",
            field=models.CharField(
                choices=[
                    ("admins_only", "Admins Only"),
                    ("admins_moderators_only", "Admins and Moderators Only"),
                    ("all_members", "All Members"),
                    ("creator_only", "Creator Only"),
                ],
                default="creator",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="operation_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("under_review", "Under Review"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sensored", "Sensored"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="text_priority",
            field=models.CharField(
                choices=[
                    ("admins_only", "Admins Only"),
                    ("admins_moderators_only", "Admins and Moderators Only"),
                    ("all_members", "All Members"),
                    ("creator_only", "Creator Only"),
                ],
                default="creator",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="660D3E5CCE", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="ED0CDEA053", editable=False, max_length=200, unique=True
            ),
        ),
    ]
