# Generated by Django 5.1.7 on 2026-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0069_defaultroom_operation_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="D8A7EE8026", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="EDCEBF73F1", editable=False, max_length=200, unique=True
            ),
        ),
    ]
