# Generated by Django 5.1.7 on 2026-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0070_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="738488BC4B", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="3CAF9B946D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
