# Generated by Django 5.1.7 on 2026-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0071_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="781A8FA563", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="C2ECD5FE3A", editable=False, max_length=200, unique=True
            ),
        ),
    ]
