# Generated by Django 5.1.7 on 2026-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0073_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultroom",
            name="room_code",
            field=models.CharField(
                default="0C3A5F1DE0", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                default="89F3B90F4A", editable=False, max_length=200, unique=True
            ),
        ),
    ]
