# Generated by Django 5.1.7 on 2025-11-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "div_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("origin", models.CharField(max_length=500)),
                ("abbreviation", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("town", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("business", "Business Enterprise"),
                            ("ngo", "Non-Governmental Organisation (NGO)"),
                            ("learning_inst", "Learning Institution"),
                            ("go", "Governmental Organisation"),
                            ("ministry", "Ministry Organisation"),
                            ("other", "Other"),
                        ],
                        default="business",
                        max_length=200,
                    ),
                ),
                ("is_learning_inst", models.BooleanField(default=False)),
                ("industry", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "dep_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "division",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.division",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="organistion",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Organisation.organisation",
            ),
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "committee_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "committee_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgBranch",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "branch_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("origin", models.CharField(max_length=500)),
                ("region", models.CharField(max_length=500)),
                ("abbreviation", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("town", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="org_branch",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Organisation.orgbranch",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "project_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "section_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "team_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.section",
                    ),
                ),
            ],
        ),
    ]
