# Generated by Django 5.1.7 on 2025-11-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="orgbranch",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="committee",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="division",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "board_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Centre",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "centre_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "institute_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "program_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "organistaion",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "unit_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Organisation.department",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Center",
        ),
    ]
