# Generated by Django 5.1.7 on 2026-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Organisation",
            "0002_department_approval_status_department_approved_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="abbreviation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="city",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="origin",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="town",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
