# Generated by Django 5.1.7 on 2025-11-20 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0002_rename_created_at_organisation_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 824336)
            ),
        ),
        migrations.AlterField(
            model_name="centre",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 825544)
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 823921)
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 822251)
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 821784)
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 825954)
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 820385)
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 821234)
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 825138)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 824738)
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 822699)
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 823518)
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 823108)
            ),
        ),
    ]
