# Generated by Django 5.1.7 on 2026-02-09 13:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0003_alter_organisation_abbreviation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="organistaion",
        ),
        migrations.RemoveField(
            model_name="centre",
            name="organistaion",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="organistaion",
        ),
        migrations.RemoveField(
            model_name="division",
            name="organistion",
        ),
        migrations.RemoveField(
            model_name="institute",
            name="organistaion",
        ),
        migrations.RemoveField(
            model_name="program",
            name="organistaion",
        ),
        migrations.RemoveField(
            model_name="project",
            name="organistaion",
        ),
        migrations.AddField(
            model_name="board",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="centre",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centres",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committees",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institutes",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="Organisation.division",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="org_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="Organisation.orgbranch",
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="city",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="origin",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="postal_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="region",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="town",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="otherorgunit",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_units",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="Organisation.department",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="Organisation.section",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="Organisation.department",
            ),
        ),
        migrations.CreateModel(
            name="OrganisationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Custom editable title (e.g. 'Head of Marketing')",
                        max_length=200,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=datetime.datetime.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_members",
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation Member",
                "verbose_name_plural": "Organisation Members",
                "unique_together": {("organisation", "user")},
            },
        ),
    ]
