# Generated by Django 5.1.7 on 2026-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Organisation",
            "0004_remove_board_organistaion_remove_centre_organistaion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("business", "Business Enterprise"),
                    ("ngo", "Non-Governmental Organisation (NGO)"),
                    ("learning_inst", "Learning Institution"),
                    ("go", "Governmental Organisation"),
                    ("ministry", "Ministry Organisation"),
                    ("restaurant", "Restaurant"),
                    ("hotel", "Hotel"),
                    ("coffee_shop", "Coffee Shop"),
                    ("supermarket", "Supermarket"),
                    ("store", "Store"),
                    ("service_provider", "Service Provider"),
                    ("food_shop", "Food Shop"),
                    ("other", "Other"),
                ],
                default="business",
                max_length=200,
            ),
        ),
    ]
