# Generated by Django 5.1.7 on 2025-11-20 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Organisation",
            "0004_alter_board_created_on_alter_centre_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 593983)
            ),
        ),
        migrations.AlterField(
            model_name="centre",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 595368)
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 593514)
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 591412)
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 590772)
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 596148)
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 588980)
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 589996)
            ),
        ),
        migrations.AlterField(
            model_name="otherorgunit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 597245)
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 594912)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 594447)
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 591975)
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 593050)
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 592546)
            ),
        ),
    ]
