# Generated by Django 5.1.7 on 2025-11-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Organisation",
            "0005_alter_board_created_on_alter_centre_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 401363)
            ),
        ),
        migrations.AlterField(
            model_name="centre",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 402576)
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 400976)
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 399415)
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 398981)
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 402969)
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 397787)
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 398475)
            ),
        ),
        migrations.AlterField(
            model_name="otherorgunit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 403388)
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 402183)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 401754)
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 399804)
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 400586)
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 400198)
            ),
        ),
    ]
