# Generated by Django 5.2.11 on 2026-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0005_alter_organisation_org_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="cover_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="organisation_covers/"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="organisation_profiles/"
            ),
        ),
    ]
