# Generated by Django 5.1.7 on 2025-11-21 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Organisation",
            "0006_alter_board_created_on_alter_centre_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 959617)
            ),
        ),
        migrations.AlterField(
            model_name="centre",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 960812)
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 959177)
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 955770)
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 955305)
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 961215)
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 954079)
            ),
        ),
        migrations.AlterField(
            model_name="orgbranch",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 954756)
            ),
        ),
        migrations.AlterField(
            model_name="otherorgunit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 961688)
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 960415)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 960025)
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 956233)
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 958194)
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 956637)
            ),
        ),
    ]
