# Generated by Django 5.2.11 on 2026-02-13 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0006_organisation_cover_picture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_organisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
