# Generated by Django 5.2.11 on 2026-06-30 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organisation", "0009_organisation_invitations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationinvitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 7, 7, 12, 41, 37, 770455)
            ),
        ),
    ]
