# Generated by Django 5.2.11 on 2026-08-08 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0010_alter_organisationinvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationinvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 10, 12, 6, 603098)),
        ),
    ]
