# Generated by Django 5.2.11 on 2026-05-16 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name_plural", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "market_cap",
                    models.DecimalField(decimal_places=2, default=0, max_digits=30),
                ),
                (
                    "volume_24h",
                    models.DecimalField(decimal_places=2, default=0, max_digits=30),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_change_percent_24h",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_trade_amount",
                    models.DecimalField(
                        decimal_places=8, default=0.0001, max_digits=20
                    ),
                ),
                (
                    "max_trade_amount",
                    models.DecimalField(
                        decimal_places=8, default=1000000, max_digits=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("market", "Market"), ("limit", "Limit")],
                        max_length=10,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=10
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=30)),
                ("price", models.DecimalField(decimal_places=8, max_digits=30)),
                ("total", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="Trading.cryptoasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_order_size",
                    models.DecimalField(
                        decimal_places=8, default=0.0001, max_digits=30
                    ),
                ),
                (
                    "max_order_size",
                    models.DecimalField(
                        decimal_places=8, default=1000000, max_digits=30
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_pairs",
                        to="Trading.cryptoasset",
                    ),
                ),
                (
                    "quote_crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_pairs",
                        to="Trading.cryptoasset",
                    ),
                ),
            ],
            options={
                "unique_together": {("base_crypto", "quote_crypto")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("market", "Market"), ("limit", "Limit")],
                        max_length=10,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=10
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                (
                    "filled_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filled", "Filled"),
                            ("partially_filled", "Partially Filled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="Trading.tradingpair",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                (
                    "locked_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="Trading.cryptoasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "crypto")},
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=30),
                ),
                ("total_amount", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Trading.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=30)),
                ("avg_buy_price", models.DecimalField(decimal_places=8, max_digits=30)),
                ("current_price", models.DecimalField(decimal_places=8, max_digits=30)),
                ("total_value", models.DecimalField(decimal_places=8, max_digits=30)),
                ("profit_loss", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "profit_loss_percent",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="Trading.cryptoasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "unique_together": {("user", "crypto", "recorded_at")},
            },
        ),
    ]
