# Generated by Django 5.2.11 on 2026-02-17 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActivityLog", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionSecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_https", models.BooleanField(default=False)),
                ("is_vpn", models.BooleanField(default=False)),
                ("is_proxy", models.BooleanField(default=False)),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("secure", "Secure"),
                            ("warning", "Warning"),
                            ("unsafe", "Unsafe"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("isp", models.CharField(blank=True, max_length=200)),
                ("user_agent", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="DevicePermissionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permission_type", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("granted", "Permission Granted"),
                            ("revoked", "Permission Revoked"),
                            ("requested", "Permission Requested"),
                            ("denied", "Permission Denied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PermissionConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("location", "Location Tracking"),
                            ("camera", "Camera Access"),
                            ("microphone", "Microphone Access"),
                            ("contacts", "Contacts Access"),
                            ("phone_number", "Phone Number"),
                            ("online_status", "Online Status Tracking"),
                            ("internet_connection", "Internet Connection Info"),
                            ("search_history", "Search History"),
                            ("activity_logging", "Activity Logging"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["permission_type"],
            },
        ),
        migrations.CreateModel(
            name="SearchActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("search_type", models.CharField(default="general", max_length=50)),
                ("results_count", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-searched_at"],
            },
        ),
        migrations.AddField(
            model_name="useractivity",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("password_change", "Password Change"),
                    ("security", "Security Update"),
                    ("device", "Device Management"),
                    ("search", "Search"),
                    ("page_view", "Page View"),
                    ("interaction", "User Interaction"),
                    ("settings_change", "Settings Change"),
                    ("permission_change", "Permission Change"),
                    ("payment", "Payment Activity"),
                    ("group_action", "Group Action"),
                    ("profile_view", "Profile View"),
                    ("download", "Download"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-timestamp"], name="ActivityLog_user_id_d747ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type"], name="ActivityLog_activit_e86956_idx"
            ),
        ),
        migrations.AddField(
            model_name="connectionsecuritylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devicepermissionlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_permission_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permissionconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchactivitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionconsent",
            unique_together={("user", "permission_type")},
        ),
    ]
