# Generated by Django 5.2.11 on 2026-02-19 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActivityLog", "0003_connectionsecuritylog_devicepermissionlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="endpoint",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="request_method",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("password_change", "Password Change"),
                    ("security", "Security Update"),
                    ("device", "Device Management"),
                    ("search", "Search"),
                    ("page_view", "Page View"),
                    ("interaction", "User Interaction"),
                    ("settings_change", "Settings Change"),
                    ("permission_change", "Permission Change"),
                    ("payment", "Payment Activity"),
                    ("group_action", "Group Action"),
                    ("profile_view", "Profile View"),
                    ("download", "Download"),
                    ("api_request", "API Request"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["endpoint"], name="ActivityLog_endpoin_270836_idx"
            ),
        ),
    ]
