# Generated by Django 5.1.7 on 2025-11-28 15:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=100)),
                ("quantity", models.FloatField()),
                ("total_cost", models.DecimalField(decimal_places=4, max_digits=100)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                        ],
                        default="paypal",
                        max_length=2000,
                    ),
                ),
                ("payment_number", models.CharField(default="", max_length=10000)),
                ("payment_token", models.CharField(default="", max_length=10000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Purchase"),
                            ("group", "Group Purchase"),
                        ],
                        default="individual",
                        max_length=2000,
                    ),
                ),
                ("payment_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "purchase_item",
                    models.ManyToManyField(blank=True, to="Payment.paymentitem"),
                ),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_profile",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_profile",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("max_capacity", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "item_grouping",
                    models.ManyToManyField(blank=True, to="Payment.paymentitem"),
                ),
                (
                    "payment_profiles",
                    models.ManyToManyField(blank=True, to="Payment.paymentprofile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=100)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "payment_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
    ]
