# Generated by Django 5.1.7 on 2026-01-26 09:25

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Piggy Bank", max_length=255)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("description", models.TextField()),
                (
                    "locking_status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked_time", "Locked until Date"),
                            ("locked_goal", "Locked until Goal"),
                        ],
                        default="unlocked",
                        max_length=20,
                    ),
                ),
                ("maturity_date", models.DateTimeField(blank=True, null=True)),
                ("is_sharable", models.BooleanField(default=True)),
                ("is_bid", models.BooleanField(default=False)),
                ("bid_status", models.CharField(default="pending", max_length=20)),
                ("achieved", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "contribution_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "total_contributed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("joined_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGroups",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("description", models.TextField(blank=True)),
                ("max_capacity", models.IntegerField(default=3)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Membership"),
                            ("standard", "Standard Membership"),
                            ("premium", "Premium Membersip"),
                            ("gold", "Gold Membership"),
                        ],
                        default="free",
                        max_length=200,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_purchase", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Payment Groups",
            },
        ),
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.FloatField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Product"),
                            ("digital", "Digital Product"),
                            ("service", "Service"),
                            ("subscription", "Subscription"),
                            ("recommendation", "Recommendation"),
                        ],
                        default="physical",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_sharable", models.BooleanField(default=True)),
                ("requires_subscription", models.BooleanField(default=False)),
                ("duration_days", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("distributor", "Distributor"),
                            ("supplier", "Supplier"),
                            ("publisher", "Publisher"),
                            ("author", "Author"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("manufacturer", "Manufacturer"),
                            ("affiliate", "Affiliate"),
                            ("sponsor", "Sponsor"),
                            ("advertiser", "Advertiser"),
                            ("content_creator", "Content Creator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_name", models.CharField(max_length=500)),
                ("business_registration", models.CharField(blank=True, max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "pending_payout",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True, null=True, upload_to="partners/licenses/"
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True, null=True, upload_to="partners/verification/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("distributor", "Distributor"),
                            ("supplier", "Supplier"),
                            ("publisher", "Publisher"),
                            ("author", "Author"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("manufacturer", "Manufacturer"),
                            ("affiliate", "Affiliate"),
                            ("sponsor", "Sponsor"),
                            ("advertiser", "Advertiser"),
                            ("content_creator", "Content Creator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_name", models.CharField(max_length=500)),
                ("business_registration", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe your business and why you want to partner with us"
                    ),
                ),
                (
                    "products_services",
                    models.TextField(
                        help_text="What products or services will you offer?"
                    ),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partner_applications/licenses/",
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partner_applications/documents/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="Payment.partner",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("achieved", models.BooleanField(default=False)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="Payment.grouptarget",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentgroupmember",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="item_grouping",
            field=models.ManyToManyField(blank=True, to="Payment.paymentitem"),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="target_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.paymentitem",
            ),
        ),
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("amex", "American Express"),
                            ("discover", "Discover Card"),
                            ("western_union", "Western Union"),
                            ("stripe", "Stripe"),
                            ("cashapp", "Cash App"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("square", "Square"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skrill", "Skrill"),
                            ("neteller", "Neteller"),
                            ("alipay", "Alipay"),
                            ("wechat_pay", "WeChat Pay"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                            ("comrade_balance", "Comrade Balance"),
                        ],
                        default="paypal",
                        max_length=2000,
                    ),
                ),
                ("payment_number", models.CharField(default="", max_length=10000)),
                ("transaction_token", models.CharField(default="", max_length=10000)),
                (
                    "comrade_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "profile_token",
                    models.CharField(default="", max_length=10000, unique=True),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Membership"),
                            ("standard", "Standard Membership"),
                            ("premium", "Premium Membersip"),
                            ("gold", "Gold Membership"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("monthly_purchases", models.IntegerField(default=0)),
                ("last_purchase_month", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Purchase"),
                            ("group", "Group Purchase"),
                        ],
                        default="individual",
                        max_length=2000,
                    ),
                ),
                ("payment_date", models.DateTimeField(default=datetime.datetime.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "purchase_item",
                    models.ManyToManyField(blank=True, to="Payment.paymentitem"),
                ),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_profile",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_profile",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.CreateModel(
            name="PaymentAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_code", models.CharField(max_length=10000, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invitation_link", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "invited_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_code", models.CharField(max_length=10000, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="target_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.product",
            ),
        ),
        migrations.CreateModel(
            name="StandingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("next_contribution_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_orders",
                        to="Payment.paymentgroupmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionToken",
            fields=[
                (
                    "transaction_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("refund", "Refund"),
                            ("withdrawal", "Withdrawal"),
                            ("deposit", "Deposit"),
                            ("transfer", "Transfer"),
                            ("bid", "Bid"),
                            ("donation", "Donation"),
                            ("subscription", "Subscription"),
                            ("fee", "Fee"),
                            ("contribution", "Contribution"),
                            ("other", "Other"),
                        ],
                        default="purchase",
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pay_from",
                    models.CharField(
                        choices=[
                            ("external", "External Payment Option"),
                            ("internal", "Internal Payment Option (Comrade Balance)"),
                        ],
                        default="external",
                        max_length=200,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("amex", "American Express"),
                            ("discover", "Discover Card"),
                            ("western_union", "Western Union"),
                            ("stripe", "Stripe"),
                            ("cashapp", "Cash App"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("square", "Square"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skrill", "Skrill"),
                            ("neteller", "Neteller"),
                            ("alipay", "Alipay"),
                            ("wechat_pay", "WeChat Pay"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                            ("comrade_balance", "Comrade Balance"),
                        ],
                        default="paypal",
                        max_length=2000,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "recipient_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_profile",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Purchase"),
                            ("group", "Group Purchase"),
                        ],
                        default="individual",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("settled", "Settled"),
                            ("reversed", "Reversed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "authorization_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentauthorization",
                    ),
                ),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "verification_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentverification",
                    ),
                ),
                (
                    "transaction_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.transactiontoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("contributed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.transactiontoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("settled", "Settled"),
                            ("reversed", "Reversed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "authorization_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentauthorization",
                    ),
                ),
                (
                    "transaction_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.transactiontoken",
                    ),
                ),
                (
                    "verification_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentverification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["user"], name="Payment_par_user_id_bfb4a7_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["partner_type", "status"], name="Payment_par_partner_b3d526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["status"], name="Payment_par_status_3b0fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(
                fields=["applicant"], name="Payment_par_applica_293f38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(fields=["status"], name="Payment_par_status_6600dc_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(
                fields=["-created_at"], name="Payment_par_created_b00a71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(fields=["user"], name="Payment_pay_user_id_4fc255_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(
                fields=["profile_token"], name="Payment_pay_profile_4459cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(fields=["tier"], name="Payment_pay_tier_270dd0_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["creator"], name="Payment_pay_creator_c251df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["is_active"], name="Payment_pay_is_acti_41f89f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["-created_at"], name="Payment_pay_created_d4f5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroupmember",
            index=models.Index(
                fields=["payment_group"], name="Payment_pay_payment_c9d383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroupmember",
            index=models.Index(
                fields=["payment_profile"], name="Payment_pay_payment_28cd2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentgroupmember",
            unique_together={("payment_group", "payment_profile")},
        ),
        migrations.AddIndex(
            model_name="groupinvitation",
            index=models.Index(fields=["status"], name="Payment_gro_status_306179_idx"),
        ),
        migrations.AddIndex(
            model_name="groupinvitation",
            index=models.Index(
                fields=["expires_at"], name="Payment_gro_expires_e3ed27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupinvitation",
            unique_together={("payment_group", "invited_profile")},
        ),
        migrations.AddIndex(
            model_name="grouptarget",
            index=models.Index(
                fields=["payment_group", "achieved"],
                name="Payment_gro_payment_29307e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(
                fields=["next_contribution_date", "is_active"],
                name="Payment_sta_next_co_555f46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["payment_profile"], name="Payment_tra_payment_184221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["-created_at"], name="Payment_tra_created_46134e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["transaction_type"], name="Payment_tra_transac_863b2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["payment_group"], name="Payment_con_payment_f0f4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["-contributed_at"], name="Payment_con_contrib_f48e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "is_active"], name="Payment_use_user_id_a19506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["end_date"], name="Payment_use_end_dat_81a478_idx"
            ),
        ),
    ]
