# Generated by Django 5.1.7 on 2025-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free Membership"),
                    ("standard", "Standard Membership"),
                    ("premium", "Premium Membersip"),
                    ("gold", "Gold Membership"),
                ],
                default="standard",
                max_length=200,
            ),
        ),
    ]
