# Generated by Django 5.1.7 on 2026-01-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_piggy_banks",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grouptarget",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="grouptarget",
            name="locking_status",
            field=models.CharField(
                choices=[
                    ("unlocked", "Unlocked"),
                    ("locked", "Locked"),
                    ("locked_time", "Locked until Date"),
                    ("locked_goal", "Locked until Goal"),
                ],
                default="unlocked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grouptarget",
            name="payment_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddIndex(
            model_name="grouptarget",
            index=models.Index(
                fields=["owner", "achieved"], name="Payment_gro_owner_i_afb4e3_idx"
            ),
        ),
    ]
