# Generated by Django 5.1.7 on 2026-01-22 14:36

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0007_customuser_account_status_customuser_deactivated_at_and_more",
        ),
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("distributor", "Distributor"),
                            ("supplier", "Supplier"),
                            ("publisher", "Publisher"),
                            ("author", "Author"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("manufacturer", "Manufacturer"),
                            ("affiliate", "Affiliate"),
                            ("sponsor", "Sponsor"),
                            ("advertiser", "Advertiser"),
                            ("content_creator", "Content Creator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_name", models.CharField(max_length=500)),
                ("business_registration", models.CharField(blank=True, max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "pending_payout",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True, null=True, upload_to="partners/licenses/"
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True, null=True, upload_to="partners/verification/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("distributor", "Distributor"),
                            ("supplier", "Supplier"),
                            ("publisher", "Publisher"),
                            ("author", "Author"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("manufacturer", "Manufacturer"),
                            ("affiliate", "Affiliate"),
                            ("sponsor", "Sponsor"),
                            ("advertiser", "Advertiser"),
                            ("content_creator", "Content Creator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_name", models.CharField(max_length=500)),
                ("business_registration", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe your business and why you want to partner with us"
                    ),
                ),
                (
                    "products_services",
                    models.TextField(
                        help_text="What products or services will you offer?"
                    ),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partner_applications/licenses/",
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partner_applications/documents/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="Payment.partner",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["user"], name="Payment_par_user_id_bfb4a7_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["partner_type", "status"], name="Payment_par_partner_b3d526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["status"], name="Payment_par_status_3b0fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(
                fields=["applicant"], name="Payment_par_applica_293f38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(fields=["status"], name="Payment_par_status_6600dc_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerapplication",
            index=models.Index(
                fields=["-created_at"], name="Payment_par_created_b00a71_idx"
            ),
        ),
    ]
