# Generated by Django 5.1.7 on 2026-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0002_grouptarget_owner_grouptarget_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="contribution_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("percentage", "Percentage"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("one_time", "One Time"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
