# Generated by Django 5.1.7 on 2026-01-02 11:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0022_alter_customuser_options_and_more"),
        ("Payment", "0002_paymentgroups_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("contributed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invitation_link", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="GroupTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("achieved", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_code", models.CharField(max_length=10000, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "contribution_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "total_contributed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("joined_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_code", models.CharField(max_length=10000, unique=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="StandingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("next_contribution_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Purchase"),
                            ("group", "Group Purchase"),
                        ],
                        default="individual",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("settled", "Settled"),
                            ("reversed", "Reversed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionToken",
            fields=[
                (
                    "transaction_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("refund", "Refund"),
                            ("withdrawal", "Withdrawal"),
                            ("deposit", "Deposit"),
                            ("transfer", "Transfer"),
                            ("bid", "Bid"),
                            ("donation", "Donation"),
                            ("subscription", "Subscription"),
                            ("fee", "Fee"),
                            ("contribution", "Contribution"),
                            ("other", "Other"),
                        ],
                        default="purchase",
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pay_from",
                    models.CharField(
                        choices=[
                            ("external", "External Payment Option"),
                            ("internal", "Internal Payment Option (Comrade Balance)"),
                        ],
                        default="external",
                        max_length=200,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("amex", "American Express"),
                            ("discover", "Discover Card"),
                            ("western_union", "Western Union"),
                            ("stripe", "Stripe"),
                            ("cashapp", "Cash App"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("square", "Square"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skrill", "Skrill"),
                            ("neteller", "Neteller"),
                            ("alipay", "Alipay"),
                            ("wechat_pay", "WeChat Pay"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                            ("comrade_balance", "Comrade Balance"),
                        ],
                        default="paypal",
                        max_length=2000,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("settled", "Settled"),
                            ("reversed", "Reversed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name="paymentgroups",
            options={"verbose_name_plural": "Payment Groups"},
        ),
        migrations.RemoveField(
            model_name="paymentgroups",
            name="payment_profiles",
        ),
        migrations.RemoveField(
            model_name="paymentprofile",
            name="payment_token",
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="auto_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="current_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="requires_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="target_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="comrade_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="profile_token",
            field=models.CharField(default="", max_length=10000, unique=True),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="transaction_token",
            field=models.CharField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="max_capacity",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="paymentitem",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymentitem",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymentprofile",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("mpesa", "M-Pesa"),
                    ("mastercard", "MasterCard (Debit or Credit Card)"),
                    ("amex", "American Express"),
                    ("discover", "Discover Card"),
                    ("western_union", "Western Union"),
                    ("stripe", "Stripe"),
                    ("cashapp", "Cash App"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("square", "Square"),
                    ("bank_transfer", "Bank Transfer"),
                    ("skrill", "Skrill"),
                    ("neteller", "Neteller"),
                    ("alipay", "Alipay"),
                    ("wechat_pay", "WeChat Pay"),
                    ("jcb", "JCB"),
                    ("diners_club", "Diner's Club"),
                    ("unionpay", "UnionPay"),
                    ("maestro", "Maestro"),
                    ("visa", "Visa"),
                    ("venmo", "Venmo"),
                    ("gcash", "G-Cash"),
                    ("comrade_balance", "Comrade Balance"),
                ],
                default="paypal",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="paymentslot",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymentslot",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentgroups"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["creator"], name="Payment_pay_creator_c251df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["is_active"], name="Payment_pay_is_acti_41f89f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroups",
            index=models.Index(
                fields=["-created_at"], name="Payment_pay_created_d4f5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(fields=["user"], name="Payment_pay_user_id_4fc255_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(
                fields=["profile_token"], name="Payment_pay_profile_4459cd_idx"
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="invited_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="target_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.paymentitem",
            ),
        ),
        migrations.AddField(
            model_name="paymentauthorization",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="paymentverification",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standing_orders",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="authorization_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentauthorization",
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="verification_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentverification",
            ),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="payment_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.paymentprofile"
            ),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="recipient_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_profile",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="transaction_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="transactiontracker",
            name="authorization_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentauthorization",
            ),
        ),
        migrations.AddField(
            model_name="transactiontracker",
            name="transaction_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="transactiontracker",
            name="verification_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentverification",
            ),
        ),
        migrations.AddIndex(
            model_name="groupinvitation",
            index=models.Index(fields=["status"], name="Payment_gro_status_306179_idx"),
        ),
        migrations.AddIndex(
            model_name="groupinvitation",
            index=models.Index(
                fields=["expires_at"], name="Payment_gro_expires_e3ed27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupinvitation",
            unique_together={("payment_group", "invited_profile")},
        ),
        migrations.AddIndex(
            model_name="grouptarget",
            index=models.Index(
                fields=["payment_group", "achieved"],
                name="Payment_gro_payment_29307e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroupmember",
            index=models.Index(
                fields=["payment_group"], name="Payment_pay_payment_c9d383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgroupmember",
            index=models.Index(
                fields=["payment_profile"], name="Payment_pay_payment_28cd2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentgroupmember",
            unique_together={("payment_group", "payment_profile")},
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(
                fields=["next_contribution_date", "is_active"],
                name="Payment_sta_next_co_555f46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["payment_profile"], name="Payment_tra_payment_184221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["-created_at"], name="Payment_tra_created_46134e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontoken",
            index=models.Index(
                fields=["transaction_type"], name="Payment_tra_transac_863b2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["payment_group"], name="Payment_con_payment_f0f4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["-contributed_at"], name="Payment_con_contrib_f48e55_idx"
            ),
        ),
    ]
