# Generated by Django 5.1.7 on 2026-02-04 11:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_initial"),
        ("Payment", "0003_paymentgroups_contribution_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery Agent"),
                            ("sales", "Sales Agent"),
                            ("support", "Support Agent"),
                        ],
                        default="delivery",
                        max_length=20,
                    ),
                ),
                ("vehicle_type", models.CharField(blank=True, max_length=50)),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("operating_zone", models.CharField(max_length=100)),
                ("availability", models.JSONField(default=dict)),
                ("id_card", models.FileField(upload_to="agent_applications/ids/")),
                (
                    "driving_license",
                    models.FileField(
                        blank=True, null=True, upload_to="agent_applications/licenses/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("result_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_agent_apps",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shops/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="shops/banners/"
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("categories", models.JSONField(default=list)),
                ("min_order_quantity", models.IntegerField(default=1)),
                ("wholesale_pricing_available", models.BooleanField(default=False)),
                (
                    "catalog_sample",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="supplier_applications/catalogs/",
                    ),
                ),
                (
                    "business_permit",
                    models.FileField(upload_to="supplier_applications/permits/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_supplier_apps",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
    ]
