# Generated by Django 5.1.7 on 2026-01-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0023_remove_customuser_login_otp_secret_and_more"),
        ("Payment", "0003_contribution_groupinvitation_grouptarget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("achieved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Product"),
                            ("digital", "Digital Product"),
                            ("service", "Service"),
                            ("subscription", "Subscription"),
                            ("recommendation", "Recommendation"),
                        ],
                        default="physical",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_sharable", models.BooleanField(default=True)),
                ("requires_subscription", models.BooleanField(default=False)),
                ("duration_days", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="paymentslot",
            name="payment_group",
        ),
        migrations.RemoveField(
            model_name="paymentslot",
            name="payment_profile",
        ),
        migrations.RenameField(
            model_name="grouptarget",
            old_name="target_date",
            new_name="maturity_date",
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="bid_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="current_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="is_bid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="is_sharable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="locking_status",
            field=models.CharField(
                choices=[
                    ("unlocked", "Unlocked"),
                    ("locked_time", "Locked until Date"),
                    ("locked_goal", "Locked until Goal"),
                ],
                default="unlocked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="name",
            field=models.CharField(default="Piggy Bank", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="last_purchase_month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="monthly_purchases",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentprofile",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free Membership"),
                    ("standard", "Standard Membership"),
                    ("premium", "Premium Membersip"),
                    ("gold", "Gold Membership"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="max_capacity",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free Membership"),
                    ("standard", "Standard Membership"),
                    ("premium", "Premium Membersip"),
                    ("gold", "Gold Membership"),
                ],
                default="free",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(fields=["tier"], name="Payment_pay_tier_270dd0_idx"),
        ),
        migrations.AddField(
            model_name="individualshare",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="individualshare",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="Payment.grouptarget",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="target_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.product",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Payment.product"
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentSlot",
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "is_active"], name="Payment_use_user_id_a19506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["end_date"], name="Payment_use_end_dat_81a478_idx"
            ),
        ),
    ]
