# Generated by Django 5.1.7 on 2026-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0004_agentapplication_shopregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiontoken",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="payment_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
