# Generated by Django 5.1.7 on 2026-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0005_transactiontoken_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Group"),
                    ("piggy_bank", "Piggy Bank Group"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
