# Generated by Django 5.1.7 on 2026-02-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0006_paymentgroups_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvitation",
            name="invited_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="invited_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentprofile",
            ),
        ),
    ]
