# Generated by Django 5.2.11 on 2026-02-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Payment",
            "0008_establishment_establishmentbranch_hotelroom_booking_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroupmember",
            name="anonymous_alias",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="allow_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
