# Generated by Django 5.2.11 on 2026-02-19 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Payment",
            "0010_paymentgroups_is_matured_paymentgroups_is_terminated_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("mpesa", "M-Pesa"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("equity", "Equity Bank"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                ("last_four", models.CharField(blank=True, max_length=4)),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                            ("discover", "Discover"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("expiry_month", models.IntegerField(blank=True, null=True)),
                ("expiry_year", models.IntegerField(blank=True, null=True)),
                ("billing_zip", models.CharField(blank=True, max_length=20)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("paypal_email", models.EmailField(blank=True, max_length=254)),
                ("bank_account_last_four", models.CharField(blank=True, max_length=4)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("provider_token", models.CharField(blank=True, max_length=500)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_methods",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_profile", "is_default"],
                        name="Payment_sav_payment_4ab7e2_idx",
                    ),
                    models.Index(
                        fields=["method_type"], name="Payment_sav_method__2d7d26_idx"
                    ),
                ],
            },
        ),
    ]
