# Generated by Django 5.2.11 on 2026-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0011_savedpaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentprofile",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("mpesa", "M-Pesa"),
                    ("mastercard", "MasterCard (Debit or Credit Card)"),
                    ("amex", "American Express"),
                    ("discover", "Discover Card"),
                    ("western_union", "Western Union"),
                    ("stripe", "Stripe"),
                    ("cashapp", "Cash App"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("square", "Square"),
                    ("bank_transfer", "Bank Transfer"),
                    ("skrill", "Skrill"),
                    ("neteller", "Neteller"),
                    ("alipay", "Alipay"),
                    ("wechat_pay", "WeChat Pay"),
                    ("jcb", "JCB"),
                    ("diners_club", "Diner's Club"),
                    ("unionpay", "UnionPay"),
                    ("maestro", "Maestro"),
                    ("visa", "Visa"),
                    ("venmo", "Venmo"),
                    ("gcash", "G-Cash"),
                    ("comrade_balance", "Qomrade Balance"),
                ],
                default="paypal",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="transactiontoken",
            name="pay_from",
            field=models.CharField(
                choices=[
                    ("external", "External Payment Option"),
                    ("internal", "Internal Payment Option (Qomrade Balance)"),
                ],
                default="external",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="transactiontoken",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("mpesa", "M-Pesa"),
                    ("mastercard", "MasterCard (Debit or Credit Card)"),
                    ("amex", "American Express"),
                    ("discover", "Discover Card"),
                    ("western_union", "Western Union"),
                    ("stripe", "Stripe"),
                    ("cashapp", "Cash App"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("square", "Square"),
                    ("bank_transfer", "Bank Transfer"),
                    ("skrill", "Skrill"),
                    ("neteller", "Neteller"),
                    ("alipay", "Alipay"),
                    ("wechat_pay", "WeChat Pay"),
                    ("jcb", "JCB"),
                    ("diners_club", "Diner's Club"),
                    ("unionpay", "UnionPay"),
                    ("maestro", "Maestro"),
                    ("visa", "Visa"),
                    ("venmo", "Venmo"),
                    ("gcash", "G-Cash"),
                    ("comrade_balance", "Qomrade Balance"),
                ],
                default="paypal",
                max_length=2000,
            ),
        ),
    ]
