# Generated by Django 5.2.11 on 2026-02-26 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0008_customuser_date_of_birth_and_more"),
        ("Payment", "0012_alter_paymentprofile_payment_option_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Membership"),
                            ("standard", "Standard Membership"),
                            ("premium", "Premium Membersip"),
                            ("gold", "Gold Membership"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_student", models.BooleanField(default=False)),
                ("group_size", models.IntegerField(default=1)),
                ("demand_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.5)),
                ("notification_count", models.IntegerField(default=0)),
                ("supply_score", models.FloatField(default=0.0)),
                ("price_action", models.FloatField(default=0.0)),
                ("notify_action", models.FloatField(default=0.0)),
                ("promo_action", models.FloatField(default=0.0)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("model_version", models.CharField(default="v1", max_length=50)),
                ("is_exploration", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_events",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="Payment_pri_user_id_587f26_idx",
                    ),
                    models.Index(fields=["tier"], name="Payment_pri_tier_4dc567_idx"),
                    models.Index(
                        fields=["-created_at"], name="Payment_pri_created_a5ec5a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="student_verification/ids/"
                    ),
                ),
                (
                    "admission_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="student_verification/admission/",
                    ),
                ),
                (
                    "transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="student_verification/transcripts/",
                    ),
                ),
                (
                    "school_email",
                    models.EmailField(
                        blank=True,
                        help_text="Must be a valid .edu or .ac.xx email",
                        max_length=254,
                    ),
                ),
                ("institution_name", models.CharField(max_length=500)),
                ("student_number", models.CharField(blank=True, max_length=100)),
                ("expected_graduation", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_verification",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_students",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="Payment_stu_user_id_6c4aaf_idx"
                    ),
                    models.Index(
                        fields=["status"], name="Payment_stu_status_94541d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPricingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumulative_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("purchase_frequency", models.FloatField(default=0.0)),
                (
                    "avg_transaction_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("login_frequency", models.FloatField(default=0.0)),
                ("session_duration_avg", models.FloatField(default=0.0)),
                ("pages_per_session", models.FloatField(default=0.0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Membership"),
                            ("standard", "Standard Membership"),
                            ("premium", "Premium Membersip"),
                            ("gold", "Gold Membership"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("is_student", models.BooleanField(default=False)),
                ("group_memberships_count", models.IntegerField(default=0)),
                ("days_since_registration", models.IntegerField(default=0)),
                ("current_discount_rate", models.FloatField(default=0.0)),
                ("price_sensitivity", models.FloatField(default=0.5)),
                ("churn_risk", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_features",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tier"], name="Payment_use_tier_592f53_idx"),
                    models.Index(
                        fields=["is_student"], name="Payment_use_is_stud_037813_idx"
                    ),
                ],
            },
        ),
    ]
