# Generated by Django 5.2.11 on 2026-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0014_product_allow_group_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="sales_channel",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("in_store", "In-Store/Offline"),
                    ("pop_up", "Pop-up Market"),
                ],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
