# Generated by Django 5.2.11 on 2026-03-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0015_order_is_offline_order_sales_channel_product_sku_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="entity_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kitty_groups",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="entity_object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Group"),
                    ("piggy_bank", "Piggy Bank Group"),
                    ("kitty", "Entity Kitty"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
