# Generated by Django 5.2.11 on 2026-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0016_paymentgroups_entity_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(default="product", max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
