# Generated by Django 5.2.11 on 2026-03-22 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0017_orderitem_item_type_orderitem_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCheckoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "items_payload",
                    models.JSONField(
                        default=list, help_text="Cart items and checkout payload"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved & Processed"),
                            ("rejected", "Rejected"),
                            ("failed", "Processing Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approvals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approved_checkouts",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_requests",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_checkouts",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "rejections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rejected_checkouts",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
        ),
    ]
