# Generated by Django 5.2.11 on 2026-03-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0018_groupcheckoutrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="group_covers/"),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="payment_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="Payment.paymentgroups",
            ),
        ),
    ]
