# Generated by Django 5.2.11 on 2026-03-25 20:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0019_paymentgroups_cover_photo_and_more"),
        ("Rooms", "0006_roomtyping"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="auto_create_room",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="linked_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_payment_group",
                to="Rooms.room",
            ),
        ),
        migrations.CreateModel(
            name="GroupJoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Why do you want to join? Include portfolio details."
                    ),
                ),
                (
                    "portfolio_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured portfolio info"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_join_requests",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group", "status"],
                        name="Payment_gro_group_i_d0ca8f_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="Payment_gro_request_e68f96_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="Payment_gro_created_8268d5_idx"
                    ),
                ],
                "unique_together": {("group", "requester")},
            },
        ),
        migrations.CreateModel(
            name="GroupVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("investment", "Investment Decision"),
                            ("savings", "Savings Decision"),
                            ("withdrawal", "Withdrawal Request"),
                            ("purchase", "Purchase Approval"),
                            ("expansion", "Expansion / Scaling"),
                            ("remuneration", "Remuneration / Payout"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Voting"),
                            ("passed", "Passed"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_votes",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "votes_abstain",
                    models.ManyToManyField(
                        blank=True,
                        related_name="voted_abstain",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "votes_against",
                    models.ManyToManyField(
                        blank=True,
                        related_name="voted_against",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "votes_for",
                    models.ManyToManyField(
                        blank=True,
                        related_name="voted_for",
                        to="Payment.paymentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["group", "status"],
                        name="Payment_gro_group_i_d83908_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="Payment_gro_created_bf222d_idx"
                    ),
                ],
            },
        ),
    ]
