# Generated by Django 5.2.11 on 2026-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0020_paymentgroups_auto_create_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupjoinrequest",
            name="application_answers",
            field=models.JSONField(
                blank=True, default=dict, help_text="Answers to custom group questions"
            ),
        ),
        migrations.AddField(
            model_name="groupjoinrequest",
            name="has_paid_entry_fee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="custom_application_questions",
            field=models.JSONField(
                blank=True, default=list, help_text="List of questions for applicants"
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="entry_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="entry_fee_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="groupjoinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
