# Generated by Django 5.2.11 on 2026-03-27 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0011_customuser_username_and_more"),
        ("Payment", "0021_groupjoinrequest_application_answers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("tv", "TV & Streaming"),
                            ("airtime", "Airtime & Data"),
                            ("internet", "Internet"),
                            ("school_fees", "School Fees"),
                            ("rent", "Rent"),
                            ("government", "Government Services"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="bill_providers/"
                    ),
                ),
                (
                    "account_label",
                    models.CharField(default="Account Number", max_length=100),
                ),
                (
                    "account_format",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for account validation",
                        max_length=200,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=10
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, default=0.015, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        help_text="Insurance company name", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("asset", "Asset Protection"),
                            ("crop", "Crop Insurance"),
                            ("device", "Device / Phone"),
                            ("travel", "Travel"),
                            ("funeral", "Funeral Cover"),
                            ("education", "Education Plan"),
                            ("business", "Business Insurance"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "premium_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Premium per period", max_digits=10
                    ),
                ),
                (
                    "premium_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("one_time", "One-Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Maximum coverage", max_digits=12
                    ),
                ),
                (
                    "deductible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("waiting_period_days", models.IntegerField(default=0)),
                (
                    "terms",
                    models.TextField(blank=True, help_text="Terms and conditions"),
                ),
                (
                    "benefits",
                    models.JSONField(
                        blank=True, default=list, help_text="List of coverage benefits"
                    ),
                ),
                (
                    "exclusions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of exclusions"
                    ),
                ),
                ("is_group_product", models.BooleanField(default=False)),
                ("min_group_size", models.IntegerField(default=0)),
                ("icon", models.CharField(default="🛡️", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="from-teal-500 to-emerald-600", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["category", "premium_amount"],
            },
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly interest rate %",
                        max_digits=6,
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("min_tenure_months", models.IntegerField(default=1)),
                ("max_tenure_months", models.IntegerField(default=24)),
                ("requires_guarantor", models.BooleanField(default=False)),
                ("guarantors_required", models.IntegerField(default=0)),
                (
                    "min_credit_score",
                    models.IntegerField(
                        default=0, help_text="Minimum credit score required"
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Processing fee %",
                        max_digits=6,
                    ),
                ),
                (
                    "late_penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Late payment penalty % per month",
                        max_digits=6,
                    ),
                ),
                ("is_group_loan", models.BooleanField(default=False)),
                (
                    "eligible_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of eligible membership tiers",
                    ),
                ),
                ("icon", models.CharField(default="💰", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="from-blue-500 to-cyan-600", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["interest_rate"],
            },
        ),
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "escrow_type",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace Purchase"),
                            ("gig", "Gig / Freelance"),
                            ("p2p", "Peer-to-Peer"),
                            ("group_investment", "Group Investment"),
                            ("custom", "Custom"),
                        ],
                        default="marketplace",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "escrow_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fee_rate",
                    models.DecimalField(decimal_places=4, default=0.02, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("funded", "Funded"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("released", "Released"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        blank=True, default=list, help_text="List of milestone objects"
                    ),
                ),
                ("delivery_proof", models.TextField(blank=True)),
                ("release_conditions", models.TextField(blank=True)),
                ("funded_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_as_buyer",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_as_seller",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscrowDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of evidence URLs/descriptions",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved_buyer", "Resolved — Buyer Wins"),
                            ("resolved_seller", "Resolved — Seller Wins"),
                            ("settled", "Settled — Split"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raised_disputes",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="Payment.escrowtransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("claimed", "Claimed"),
                            ("cancelled", "Cancelled"),
                            ("lapsed", "Lapsed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "premium_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_premiums_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("beneficiaries", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_policies",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="Payment.insuranceproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_claimed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_approved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.TextField()),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supporting documents/photos",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_claims",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="Payment.insurancepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tenure_months", models.IntegerField()),
                ("purpose", models.TextField(blank=True)),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_repayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "processing_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("credit_score_at_application", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("repaying", "Repaying"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_loans",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "guarantors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guaranteed_loans",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="Payment.loanproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="Payment.loanapplication",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.transactiontoken",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="BillPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=200)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("amex", "American Express"),
                            ("discover", "Discover Card"),
                            ("western_union", "Western Union"),
                            ("stripe", "Stripe"),
                            ("cashapp", "Cash App"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("square", "Square"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skrill", "Skrill"),
                            ("neteller", "Neteller"),
                            ("alipay", "Alipay"),
                            ("wechat_pay", "WeChat Pay"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                            ("comrade_balance", "Qomrade Balance"),
                        ],
                        default="comrade_balance",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.transactiontoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="Payment.billprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="Payment_bil_user_id_e8cdee_idx",
                    ),
                    models.Index(
                        fields=["status"], name="Payment_bil_status_856d0e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=300, help_text="Score from 100-900"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        blank=True, default=dict, help_text="Breakdown of score factors"
                    ),
                ),
                ("savings_score", models.IntegerField(default=0)),
                ("repayment_score", models.IntegerField(default=0)),
                ("group_score", models.IntegerField(default=0)),
                ("transaction_score", models.IntegerField(default=0)),
                ("tenure_score", models.IntegerField(default=0)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_score",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["score"], name="Payment_cre_score_6689ca_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["buyer", "status"], name="Payment_esc_buyer_i_1673c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["seller", "status"], name="Payment_esc_seller__1f011d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["-created_at"], name="Payment_esc_created_555549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["user", "status"], name="Payment_ins_user_id_17b90c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["user", "status"], name="Payment_loa_user_id_721a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["-created_at"], name="Payment_loa_created_1d42e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepayment",
            index=models.Index(
                fields=["loan", "status"], name="Payment_loa_loan_id_92b676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepayment",
            index=models.Index(
                fields=["due_date"], name="Payment_loa_due_dat_c9036e_idx"
            ),
        ),
    ]
