# Generated by Django 5.2.11 on 2026-03-30 23:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0006_investorprofile"),
        ("Payment", "0022_billprovider_insuranceproduct_loanproduct_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "donor_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("group", "Group")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "donation_mode",
                    models.CharField(
                        choices=[
                            ("lump_sum", "Lump Sum (Group dictates once)"),
                            ("individual_share", "Individual Share (Portion-based)"),
                            (
                                "independent_quote",
                                "Independent Quoting (Each member quotes)",
                            ),
                        ],
                        default="lump_sum",
                        help_text="How group members contribute to this donation",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_object_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of recipient",
                        max_length=500,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("next_due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for group contributions",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("collecting", "Collecting Contributions"),
                            ("submitted", "Submitted to Recipient"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("submitted", "Submitted to Recipient"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="GroupInvestment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "quoting_mode",
                    models.CharField(
                        choices=[
                            (
                                "lump_sum",
                                "Lump Sum (One member proposes, group approves)",
                            ),
                            (
                                "proportional",
                                "Proportional Quoting (Each quotes, profits split by ratio)",
                            ),
                            (
                                "independent",
                                "Independent (Each invests alone, no coordination)",
                            ),
                        ],
                        default="proportional",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_returns",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "net_profit_loss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quoting", "Members Are Quoting"),
                            ("collecting", "Collecting Payments"),
                            ("invested", "Invested"),
                            ("matured", "Matured / Returns Available"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="quoting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quoted_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Auto-calculated based on proportional contribution",
                        max_digits=8,
                    ),
                ),
                (
                    "allocated_returns",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Quote Submitted"),
                            ("confirmed", "Payment Confirmed"),
                            ("paid", "Paid / Invested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="accrued_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total interest earned so far",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="contribution_mode",
            field=models.CharField(
                choices=[
                    ("equal", "Equal Contributions"),
                    ("proportional", "Proportional Contributions"),
                ],
                default="equal",
                help_text="How group members contribute (equal or proportional)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Annual interest rate % (for fixed_deposit type)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="last_interest_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="penalty_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Early withdrawal penalty % (for fixed_deposit type)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="savings_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal Piggy Bank"),
                    ("locked", "Locked Savings"),
                    ("fixed_deposit", "Fixed Deposit"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="grouptarget",
            index=models.Index(
                fields=["savings_type"], name="Payment_gro_savings_f0ad3a_idx"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="approval_vote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_approval",
                to="Payment.groupvote",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="donor_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="recipient_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_donations",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="donationcontribution",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="Payment.donation",
            ),
        ),
        migrations.AddField(
            model_name="donationcontribution",
            name="donor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_contribution_records",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="donationcontribution",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_contributions",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="donationcontribution",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_contributions",
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="approval_vote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investment_approval",
                to="Payment.groupvote",
            ),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="capital_venture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_investments",
                to="Funding.capitalventure",
            ),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_investments",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="investment_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_investments",
                to="Funding.investmentopportunity",
            ),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="payment_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_investments",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="group_investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="Payment.groupinvestment",
            ),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investment_quotes",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investment_quotes",
                to="Payment.transactiontoken",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor_profile", "status"],
                name="Payment_don_donor_p_f96a84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["payment_group", "status"],
                name="Payment_don_payment_faddf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["-created_at"], name="Payment_don_created_89379a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationcontribution",
            index=models.Index(
                fields=["donation", "status"], name="Payment_don_donatio_e0a5df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationcontribution",
            index=models.Index(
                fields=["donor_profile"], name="Payment_don_donor_p_eb768a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupinvestment",
            index=models.Index(
                fields=["payment_group", "status"],
                name="Payment_gro_payment_416c6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupinvestment",
            index=models.Index(
                fields=["-created_at"], name="Payment_gro_created_d5fcdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentquote",
            index=models.Index(
                fields=["group_investment", "status"],
                name="Payment_inv_group_i_dd7e01_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="investmentquote",
            unique_together={("group_investment", "member")},
        ),
    ]
