# Generated by Django 5.2.11 on 2026-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0023_donation_donationcontribution_groupinvestment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceoffering",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("appointment", "Appointment (e.g. In-person/Remote session)"),
                    ("call_service", "Call Service (e.g. Phone consultation)"),
                    ("online_sale", "Online Sale (e.g. Digital download)"),
                ],
                default="appointment",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="serviceoffering",
            name="setup_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores specific fields: delay_minutes, break_minutes, max_bookings, tags, call_number",
            ),
        ),
    ]
