# Generated by Django 5.2.11 on 2026-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0024_serviceoffering_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("internal", "Internal (Group Only)"),
                    ("external", "External (Public)"),
                ],
                default="external",
                max_length=20,
            ),
        ),
    ]
