# Generated by Django 5.2.11 on 2026-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0025_donation_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="category",
            field=models.CharField(
                default="General charity",
                help_text="e.g., Health, Education, Relief",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="name",
            field=models.CharField(default="Untitled Campaign", max_length=255),
        ),
    ]
