# Generated by Django 5.2.11 on 2026-04-02 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0012_customuser_onboarding_completed"),
        ("Payment", "0026_donation_category_donation_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("tv", "TV & Streaming"),
                            ("airtime", "Airtime & Data"),
                            ("internet", "Internet"),
                            ("school_fees", "School Fees"),
                            ("rent", "Rent"),
                            ("government", "Government Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("account_number", models.CharField(max_length=255)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("external_mpesa", "M-Pesa (External)"),
                            ("external_bank", "Bank Transfer (External)"),
                            ("internal_wallet", "Qomrade Wallet (Internal)"),
                        ],
                        default="external_mpesa",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Optional notes or description"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_providers",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillStandingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_standing_orders",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_orders",
                        to="Payment.userserviceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userserviceprovider",
            index=models.Index(
                fields=["user", "category"], name="Payment_use_user_id_5c864d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billstandingorder",
            index=models.Index(
                fields=["user", "status"], name="Payment_bil_user_id_e261b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billstandingorder",
            index=models.Index(
                fields=["start_date"], name="Payment_bil_start_d_1bd89c_idx"
            ),
        ),
    ]
