# Generated by Django 5.2.11 on 2026-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0027_userserviceprovider_billstandingorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userserviceprovider",
            name="destination_account",
            field=models.CharField(
                blank=True,
                help_text="Paybill, Till Number, Bank Account, etc.",
                max_length=255,
                null=True,
            ),
        ),
    ]
