# Generated by Django 5.2.11 on 2026-04-07 12:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0028_userserviceprovider_destination_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#6366f1",
                help_text="Hex accent colour for UI theming, e.g. #6366f1",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="investment_pitch",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Investment or donation pitch description",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="joining_minimum",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum wallet balance required to join",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="loan_proposition",
            field=models.TextField(
                blank=True, default="", help_text="Loan offering/proposition details"
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent group (expansion of)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_groups",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.CreateModel(
            name="GroupPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="group_posts/"),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "reactions",
                    models.JSONField(
                        blank=True, default=dict, help_text='{"👍": [user_id,...], ...}'
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_posts",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupPostReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_replies",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Payment.grouppost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "target_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "proportion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="% of total target",
                        max_digits=5,
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["group", "order"], name="Payment_gro_group_i_cd04ad_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="grouppost",
            index=models.Index(
                fields=["group", "-created_at"], name="Payment_gro_group_i_6dcef9_idx"
            ),
        ),
    ]
