# Generated by Django 5.2.11 on 2026-04-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0029_paymentgroups_accent_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grouptarget",
            options={"ordering": ["-created_at"]},
        ),
    ]
