# Generated by Django 5.2.11 on 2026-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0030_alter_grouptarget_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvestment",
            name="pitch_visibility",
            field=models.CharField(
                choices=[("internal", "Members Only"), ("public", "Public Pitch")],
                default="internal",
                max_length=20,
            ),
        ),
    ]
