# Generated by Django 5.2.11 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0031_groupinvestment_pitch_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvestment",
            name="contribution_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="groupinvestment",
            name="gains_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="contribution_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="gains_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investmentquote",
            name="gains_distribution_preference",
            field=models.CharField(
                choices=[
                    ("compound_in_group", "Compound within Group Pool"),
                    (
                        "direct_to_wallet",
                        "Send proportionally to individual Direct Wallet",
                    ),
                ],
                default="compound_in_group",
                max_length=30,
            ),
        ),
    ]
