# Generated by Django 5.2.11 on 2026-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0032_groupinvestment_contribution_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="payment_gateway",
            field=models.CharField(
                blank=True,
                default="wallet",
                help_text="wallet, stripe, flutterwave, pesapal, paypal",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe PaymentIntent ID or external gateway transaction ref",
                max_length=255,
            ),
        ),
    ]
