# Generated by Django 5.2.11 on 2026-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0033_escrowtransaction_payment_gateway_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="is_forwardable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="is_shareable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="post_type",
            field=models.CharField(
                default="general",
                help_text="general, announcement, poll, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_group_posts",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="grouppostreply",
            name="reactions",
            field=models.JSONField(
                blank=True, default=dict, help_text='{"👍": [user_id,...], ...}'
            ),
        ),
    ]
