# Generated by Django 5.2.11 on 2026-04-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0034_grouppost_is_forwardable_grouppost_is_shareable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupcheckoutrequest",
            name="approval_notes",
            field=models.TextField(
                blank=True, help_text="Notes provided during approval"
            ),
        ),
        migrations.AddField(
            model_name="groupcheckoutrequest",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Locks the request from further edits once voting starts",
            ),
        ),
        migrations.AddField(
            model_name="groupcheckoutrequest",
            name="rejection_notes",
            field=models.TextField(blank=True, help_text="Reason for rejection"),
        ),
        migrations.AddField(
            model_name="groupcheckoutrequest",
            name="snapshots",
            field=models.JSONField(
                default=dict,
                help_text="Immutable snapshot of items and amount at time of lock",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="approval_threshold",
            field=models.IntegerField(
                default=51, help_text="Percentage of members required to approve"
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="hierarchy_mode",
            field=models.BooleanField(
                default=False, help_text="If True, follows a hierarchy for approvals"
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="transaction_trigger_role",
            field=models.CharField(
                choices=[("admin", "Admin Only"), ("member", "Any Member")],
                default="admin",
                max_length=20,
            ),
        ),
    ]
