# Generated by Django 5.2.11 on 2026-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0035_groupcheckoutrequest_approval_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroupmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="capacity_category",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("gold", "Gold"),
                ],
                default="free",
                help_text="Auto-upgraded based on member count.",
                max_length=20,
            ),
        ),
    ]
