# Generated by Django 5.2.11 on 2026-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0036_sprint4_capacity_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("group", "Group Only"),
                    ("members", "Members Only"),
                    ("public", "Public"),
                ],
                default="group",
                help_text="Who can see this piggy bank",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="rules_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Group rules and guidelines displayed to members",
            ),
        ),
    ]
