# Generated by Django 5.2.11 on 2026-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0038_sprint6_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppostreply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="Payment.grouppostreply",
            ),
        ),
        migrations.AddField(
            model_name="grouppostreply",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_group_replies",
                to="Payment.paymentprofile",
            ),
        ),
    ]
