# Generated by Django 5.2.11 on 2026-05-01 17:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0039_grouppostreply_parent_reply_grouppostreply_upvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="owning_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_establishments",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="allow_partial_withdrawal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="immature_exit_penalty_rate",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="is_lifetime",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="is_round_contribution_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="round_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="round_assignment_method",
            field=models.CharField(
                choices=[
                    ("random", "Random assignment each round"),
                    ("sequential", "Sequential (by join date)"),
                    ("manual", "Manual selection"),
                ],
                default="random",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="round_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("one_time", "One Time"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="round_persistence_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentgroups",
            name="round_persistence_mode",
            field=models.CharField(
                choices=[
                    ("once", "Single cycle (ends when everyone gets paid)"),
                    ("fixed_rounds", "Fixed number of rounds"),
                    ("forever", "Runs indefinitely"),
                ],
                default="once",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BenefitDistributionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distribution_criteria",
                    models.CharField(
                        choices=[
                            ("equal", "Equal split among all members"),
                            (
                                "contribution_proportional",
                                "Proportional to total contributions",
                            ),
                            (
                                "ownership_proportional",
                                "Proportional to ownership/shares (investment groups)",
                            ),
                            ("hybrid", "Mix of equal and proportional"),
                        ],
                        default="contribution_proportional",
                        max_length=30,
                    ),
                ),
                (
                    "payout_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate upon availability"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("manual", "Manual approval required"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum amount before payout is triggered",
                        max_digits=12,
                    ),
                ),
                (
                    "auto_reinvest_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-reinvest if below this amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "wallet_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Percentage sent to member wallets",
                        max_digits=5,
                    ),
                ),
                (
                    "group_retain_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage retained in group pool",
                        max_digits=5,
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Require member approval for distributions",
                    ),
                ),
                (
                    "approval_threshold",
                    models.IntegerField(
                        default=51,
                        help_text="Percentage of members required to approve (if approval required)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Rule priority (lower = higher priority)"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_rules",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefit Distribution Rule",
                "verbose_name_plural": "Benefit Distribution Rules",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(help_text="Round sequence number"),
                ),
                (
                    "contribution_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount each member contributes",
                        max_digits=12,
                    ),
                ),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total collected in this round",
                        max_digits=12,
                    ),
                ),
                ("award_date", models.DateTimeField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateTimeField(help_text="When this round starts collecting"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="When this round ends", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active - Collecting"),
                            ("completed", "Completed - Awarded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_method",
                    models.CharField(
                        choices=[
                            ("random", "Random assignment each round"),
                            ("sequential", "Sequential (by join date)"),
                            ("manual", "Manual selection"),
                        ],
                        default="random",
                        help_text="How to assign recipient for each round",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awarded_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_rounds",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_contributions",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "ordering": ["-round_number"],
            },
        ),
        migrations.CreateModel(
            name="RoundMemberContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contribution_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount contributed", max_digits=12
                    ),
                ),
                (
                    "contribution_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this contribution"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_member_contributions",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="If contributing for another member",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions_on_behalf",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_contributions",
                        to="Payment.roundcontribution",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_contributions",
                        to="Payment.transactiontoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-contribution_date"],
            },
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="contributions",
            field=models.ManyToManyField(
                related_name="participated_rounds",
                through="Payment.RoundMemberContribution",
                through_fields=("round", "member"),
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount to withdraw", max_digits=12
                    ),
                ),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[
                            ("excess_contribution", "Excess of expected average"),
                            ("maturity", "Group maturity reached"),
                            ("emergency", "Emergency withdrawal"),
                            ("partial", "Partial withdrawal (ongoing participation)"),
                            ("exit", "Full exit from group"),
                        ],
                        default="excess_contribution",
                        help_text="Type of withdrawal",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for withdrawal")),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="withdrawal_documents/"
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0, help_text="Hierarchy level of requester (0 = top)"
                    ),
                ),
                (
                    "requires_hierarchy_approval",
                    models.BooleanField(
                        default=False, help_text="Whether hierarchy approval is needed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                (
                    "early_withdrawal_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Penalty for early withdrawal (if applicable)",
                        max_digits=12,
                    ),
                ),
                (
                    "immature_exit_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Deduction for immature exit (2% as per requirements)",
                        max_digits=12,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_withdrawals",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "destination_wallet",
                    models.ForeignKey(
                        help_text="Destination wallet (member's personal wallet)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_destinations",
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_requests",
                        to="Payment.transactiontoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Request",
                "verbose_name_plural": "Withdrawal Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupSettingsChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        help_text="Type of setting being changed (e.g., contribution_amount, round_frequency)",
                        max_length=100,
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        help_text="Human-readable description of what is changing"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Previous setting values"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Proposed setting values"
                    ),
                ),
                (
                    "impact_summary",
                    models.TextField(
                        blank=True,
                        help_text="Auto-generated text explaining the effects of this change",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_vote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_change",
                        to="Payment.groupvote",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_change_requests",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_settings_changes",
                        to="Payment.paymentgroupmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_group", "status"],
                        name="Payment_gro_payment_208b8c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="roundmembercontribution",
            index=models.Index(
                fields=["round", "member"], name="Payment_rou_round_i_15d21a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roundmembercontribution",
            unique_together={("round", "member")},
        ),
        migrations.AddIndex(
            model_name="roundcontribution",
            index=models.Index(
                fields=["payment_group", "status"],
                name="Payment_rou_payment_5895a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roundcontribution",
            index=models.Index(
                fields=["-created_at"], name="Payment_rou_created_b56d9e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roundcontribution",
            unique_together={("payment_group", "round_number")},
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["payment_group", "status"],
                name="Payment_wit_payment_d28fb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["requester", "status"], name="Payment_wit_request_4b8b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["-created_at"], name="Payment_wit_created_adc6b8_idx"
            ),
        ),
    ]
