# Generated by Django 5.2.11 on 2026-05-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0040_establishment_owning_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_contributions_on_behalf",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="Payment.paymentgroupmember",
            ),
        ),
    ]
