# Generated by Django 5.2.11 on 2026-05-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0041_contribution_on_behalf_of_alter_contribution_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="is_kitty",
            field=models.BooleanField(
                default=False, help_text="If True, this is a specialized sub-fund/kitty"
            ),
        ),
    ]
