# Generated by Django 5.2.11 on 2026-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0042_paymentgroups_is_kitty"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsettingschangerequest",
            name="voter_sentiments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="groupsettingschangerequest",
            name="votes_against",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupsettingschangerequest",
            name="votes_for",
            field=models.IntegerField(default=0),
        ),
    ]
