# Generated by Django 5.2.11 on 2026-05-02 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0043_groupsettingschangerequest_voter_sentiments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundcontribution",
            name="approval_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="approvals",
            field=models.ManyToManyField(
                blank=True,
                related_name="approved_rounds",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="rejections",
            field=models.ManyToManyField(
                blank=True,
                related_name="rejected_rounds",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.CreateModel(
            name="RoundPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_number",
                    models.PositiveIntegerField(
                        help_text="Position in the sequence (1, 2, 3...)"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chama_positions",
                        to="Payment.paymentgroupmember",
                    ),
                ),
                (
                    "payment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chama_positions",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "ordering": ["position_number"],
                "unique_together": {("payment_group", "position_number")},
            },
        ),
    ]
