# Generated by Django 5.2.11 on 2026-05-03 09:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0044_roundcontribution_approval_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouptarget",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="paymentgroupmember",
            name="role",
        ),
        migrations.AddField(
            model_name="paymentgroupmember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="GroupTypeChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_type", models.CharField(max_length=20)),
                ("new_type", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_change_logs",
                        to="Payment.paymentgroups",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
