# Generated by Django 5.2.11 on 2026-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0045_add_payment_group_member_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitdistributionrule",
            name="approval_threshold",
            field=models.IntegerField(
                default=51, help_text="Percentage of members required to approve"
            ),
        ),
        migrations.AlterField(
            model_name="groupcheckoutrequest",
            name="approval_notes",
            field=models.TextField(
                blank=True, help_text="Notes from members who approved"
            ),
        ),
        migrations.AlterField(
            model_name="groupcheckoutrequest",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Prevents editing once voting starts"
            ),
        ),
        migrations.AlterField(
            model_name="groupcheckoutrequest",
            name="rejection_notes",
            field=models.TextField(
                blank=True, help_text="Notes from members who rejected"
            ),
        ),
        migrations.AlterField(
            model_name="groupcheckoutrequest",
            name="snapshots",
            field=models.JSONField(
                default=dict,
                help_text="Immutable snapshot of checkout details at lock time",
            ),
        ),
        migrations.AlterField(
            model_name="grouppost",
            name="reactions",
            field=models.JSONField(
                blank=True, default=dict, help_text='{"thumbs_up": [user_id,...], ...}'
            ),
        ),
        migrations.AlterField(
            model_name="grouppostreply",
            name="reactions",
            field=models.JSONField(
                blank=True, default=dict, help_text='{"thumbs_up": [user_id,...], ...}'
            ),
        ),
        migrations.AlterField(
            model_name="paymentgroups",
            name="is_lifetime",
            field=models.BooleanField(
                default=False, help_text="Group runs indefinitely"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="early_withdrawal_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Penalty for early withdrawal",
                max_digits=12,
            ),
        ),
    ]
