# Generated by Django 5.2.11 on 2026-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0046_alter_benefitdistributionrule_approval_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("pending", "Pending - Awaiting Start"),
                    ("active", "Active - Collecting"),
                    ("completed", "Completed - Awarded"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
