# Generated by Django 5.2.11 on 2026-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0047_alter_roundcontribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for the donation campaign",
                null=True,
                upload_to="donation_covers/",
            ),
        ),
    ]
