# Generated by Django 5.2.11 on 2026-05-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0048_add_cover_image_to_donation"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="organization_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_organizations",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="organization_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Details about the organization - name, address, etc.",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="organization_object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
