# Generated by Django 5.2.11 on 2026-05-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0049_add_organization_to_donation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roundposition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="previous_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_rounds",
                to="Payment.roundcontribution",
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="round_name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for this round (unique per group)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="use_previous_positions",
            field=models.BooleanField(
                default=False, help_text="Use positions from previous round"
            ),
        ),
        migrations.AddField(
            model_name="roundposition",
            name="round",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific round this position is for (null = global/default)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_positions",
                to="Payment.roundcontribution",
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="assignment_method",
            field=models.CharField(
                choices=[
                    ("random", "Random assignment each round"),
                    ("sequential", "Sequential (by position)"),
                    ("manual", "Manual selection"),
                ],
                default="random",
                help_text="How to assign recipient for each round",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roundposition",
            unique_together={("payment_group", "round", "position_number")},
        ),
    ]
