# Generated by Django 5.2.11 on 2026-05-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0050_add_round_name_and_round_positions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roundmembercontribution",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="award_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="claim_destination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wallet", "Qomrade Wallet"),
                    ("mpesa", "M-Pesa"),
                    ("bank", "Bank Transfer"),
                    ("card", "Card"),
                ],
                default="wallet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="claim_status",
            field=models.CharField(
                choices=[
                    ("not_ready", "Not Ready"),
                    ("unclaimed", "Unclaimed - Ready to Claim"),
                    ("claimed", "Claimed"),
                    ("processing", "Processing Payout"),
                ],
                default="not_ready",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="contribution_frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                    ("custom_days", "Custom (Days)"),
                ],
                default="monthly",
                help_text="How often members contribute",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="currency",
            field=models.CharField(
                default="KES", help_text="Currency code (KES, USD, etc.)", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="current_cycle",
            field=models.PositiveIntegerField(
                default=1, help_text="Current cycle number (which member is receiving)"
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="frequency_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Custom frequency interval in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="next_contribution_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next contribution cycle is due",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="start_condition",
            field=models.CharField(
                choices=[
                    ("all_members", "All Members Must Approve"),
                    ("threshold", "Approval Threshold (%)"),
                ],
                default="threshold",
                help_text="Condition to start the round",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="total_cycles_completed",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of fully completed cycles"
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="total_generated",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cumulative amount generated across all cycles",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="voting_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for members to approve/reject",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roundmembercontribution",
            name="cycle_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Which cycle this contribution belongs to"
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="assignment_method",
            field=models.CharField(
                choices=[
                    ("random", "Random assignment each round"),
                    ("sequential", "Sequential (by position)"),
                    ("manual", "Manual selection"),
                ],
                default="random",
                help_text="How to assign recipient order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="awarded_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Current cycle recipient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="awarded_rounds",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="contribution_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount each member contributes per cycle",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("pending", "Pending - Awaiting Start"),
                    ("active", "Active - Collecting"),
                    ("completed", "Completed - All Cycles Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roundcontribution",
            name="total_collected",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total collected in current cycle",
                max_digits=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roundmembercontribution",
            unique_together={("round", "member", "cycle_number")},
        ),
        migrations.AddIndex(
            model_name="roundmembercontribution",
            index=models.Index(
                fields=["round", "cycle_number"], name="Payment_rou_round_i_6214b3_idx"
            ),
        ),
    ]
