# Generated by Django 5.2.11 on 2026-05-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0052_remove_grouptypechangelog_changed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppostreply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="Payment.grouppostreply",
            ),
        ),
    ]
