# Generated by Django 5.2.11 on 2026-05-07 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0053_grouppostreply_parent_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="flexible_max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="flexible_min_gap_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="last_withdrawal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="withdrawal_mode",
            field=models.CharField(
                choices=[
                    ("free", "Free Withdrawal"),
                    ("locked", "Locked (No early withdrawal)"),
                    ("flexible", "Flexible (Limited amount/time)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PiggyBankConversionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted/Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_vote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.groupvote",
                    ),
                ),
                (
                    "piggy_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_requests",
                        to="Payment.grouptarget",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentgroupmember",
                    ),
                ),
            ],
        ),
    ]
