# Generated by Django 5.2.11 on 2026-05-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0054_grouptarget_flexible_max_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="Payment.grouptarget",
            ),
        ),
    ]
