# Generated by Django 5.2.11 on 2026-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0055_contribution_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="can_share",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_group_posts",
                to="Payment.paymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="grouppostreply",
            name="reactions",
            field=models.JSONField(
                blank=True, default=dict, help_text='{"👍": [user_id,...], ...}'
            ),
        ),
        migrations.AddField(
            model_name="grouppostreply",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_group_replies",
                to="Payment.paymentprofile",
            ),
        ),
    ]
