# Generated by Django 5.2.11 on 2026-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0056_grouppost_can_share_grouppost_upvotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgroups",
            name="rules_text",
            field=models.TextField(
                blank=True, default="", help_text="Official group rules and regulations"
            ),
        ),
    ]
