# Generated by Django 5.2.11 on 2026-05-09 14:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0057_paymentgroups_rules_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="transaction_category",
            field=models.CharField(default="transfer", max_length=200),
        ),
    ]
