# Generated by Django 5.2.11 on 2026-05-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0058_transactionhistory_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="authorization_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentauthorization",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="verification_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Payment.paymentverification",
            ),
        ),
    ]
