# Generated by Django 5.2.11 on 2026-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0059_alter_transactionhistory_authorization_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiontoken",
            name="reversal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("in_review", "In Review"),
                    ("verified", "Verified"),
                    ("declined", "Declined"),
                    ("authorized", "Authorized"),
                    ("settled", "Settled"),
                    ("reversed", "Reversed"),
                    ("expired", "Expired"),
                ],
                default="completed",
                max_length=200,
            ),
        ),
    ]
