# Generated by Django 5.2.11 on 2026-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0060_transactiontoken_reversal_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprofile",
            name="preferred_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
