# Generated by Django 5.2.11 on 2026-05-13 04:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0014_profile_country_code_profile_preferred_currency"),
        ("Payment", "0061_paymentprofile_preferred_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundcontribution",
            name="allowed_swap_cycles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cycles where swapping is allowed (e.g., [1, 2] means can swap before cycles 1 and 2)",
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="contribution_day_of_week",
            field=models.IntegerField(
                blank=True,
                help_text="Day of week for contributions (0=Monday, 6=Sunday)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="contribution_window_days",
            field=models.IntegerField(
                default=3,
                help_text="Days before/after contribution day to allow contributions",
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="position_swap_requests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Track position swap requests between members",
            ),
        ),
        migrations.AddField(
            model_name="roundcontribution",
            name="scheduled_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When contributions officially begin after approval",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProviderRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("bill_provider", "Bill Provider"),
                            ("insurance_provider", "Insurance Provider"),
                            ("loan_provider", "Loan Provider"),
                            ("utility_provider", "Utility Provider"),
                            ("financial_service", "Financial Service"),
                            ("government_service", "Government Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("business_email", models.EmailField(max_length=254)),
                ("business_phone", models.CharField(max_length=30)),
                ("business_address", models.TextField()),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("tv", "TV & Streaming"),
                            ("airtime", "Airtime & Data"),
                            ("internet", "Internet"),
                            ("school_fees", "School Fees"),
                            ("rent", "Rent"),
                            ("government", "Government Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="provider_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "min_transaction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "max_transaction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=12
                    ),
                ),
                (
                    "supported_payment_methods",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("pending_documents", "Pending Documents"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_create_kitty",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create a kitty for this provider",
                    ),
                ),
                ("kitty_name", models.CharField(blank=True, max_length=255)),
                (
                    "kitty_target_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_payment_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_link",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_providers",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_registrations",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_license", "Business License"),
                            ("tax_certificate", "Tax Certificate"),
                            ("identity_proof", "Identity Proof"),
                            ("address_proof", "Address Proof"),
                            ("bank_details", "Bank Account Details"),
                            ("regulatory_approval", "Regulatory Approval"),
                            ("kyc", "KYC Document"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="provider_documents/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_provider_documents",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="Payment.providerregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Provider Admin"),
                            ("support", "Customer Support"),
                            ("applications", "Applications Handler"),
                            ("transactions", "Transactions Manager"),
                            ("queries", "Query Handler"),
                            ("compliance", "Compliance Officer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Approval"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("can_handle_queries", models.BooleanField(default=True)),
                ("can_review_applications", models.BooleanField(default=False)),
                ("can_manage_transactions", models.BooleanField(default=False)),
                ("can_approve_claims", models.BooleanField(default=False)),
                (
                    "max_transaction_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("assigned_categories", models.JSONField(blank=True, default=list)),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                ("email_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff_members",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_staff_roles",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("application", "Application Status"),
                            ("transaction", "Transaction Issue"),
                            ("claim", "Claim Inquiry"),
                            ("document", "Document Query"),
                            ("technical", "Technical Support"),
                            ("general", "General Inquiry"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending_response", "Pending Response"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Related application, transaction, or claim ID",
                        max_length=100,
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("satisfaction_rating", models.IntegerField(blank=True, null=True)),
                ("satisfaction_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_queries",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_queries",
                        to="Payment.providerstaff",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_queries",
                        to="Payment.providerstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("service_enrollment", "Service Enrollment"),
                            ("insurance_policy", "Insurance Policy"),
                            ("loan_application", "Loan Application"),
                            ("account_setup", "Account Setup"),
                        ],
                        max_length=30,
                    ),
                ),
                ("application_data", models.JSONField(default=dict)),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("submitted_documents", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("pending_documents", "Pending Documents"),
                            ("pending_payment", "Pending Payment"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("processing_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_application",
                        to="Payment.loanapplication",
                    ),
                ),
                (
                    "linked_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_application",
                        to="Payment.insurancepolicy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_applications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to="Payment.providerstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("commission", "Commission"),
                            ("payout", "Payout"),
                            ("adjustment", "Adjustment"),
                            ("fee", "Fee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provider_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "platform_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("mastercard", "MasterCard (Debit or Credit Card)"),
                            ("amex", "American Express"),
                            ("discover", "Discover Card"),
                            ("western_union", "Western Union"),
                            ("stripe", "Stripe"),
                            ("cashapp", "Cash App"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("square", "Square"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skrill", "Skrill"),
                            ("neteller", "Neteller"),
                            ("alipay", "Alipay"),
                            ("wechat_pay", "WeChat Pay"),
                            ("jcb", "JCB"),
                            ("diners_club", "Diner's Club"),
                            ("unionpay", "UnionPay"),
                            ("maestro", "Maestro"),
                            ("visa", "Visa"),
                            ("venmo", "Venmo"),
                            ("gcash", "G-Cash"),
                            ("comrade_balance", "Qomrade Balance"),
                        ],
                        default="comrade_balance",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("settled", "Settled"),
                            ("reversed", "Reversed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_transaction",
                        to="Payment.transactiontoken",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_transactions",
                        to="Payment.providerstaff",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_transactions",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("application_update", "Application Update"),
                            ("transaction_complete", "Transaction Complete"),
                            ("claim_update", "Claim Update"),
                            ("document_required", "Document Required"),
                            ("system_alert", "System Alert"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="Payment.providerapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_notifications",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="Payment.providertransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("bill_payment", "Bill Payment"),
                            ("insurance", "Insurance"),
                            ("loan", "Loan"),
                            ("savings", "Savings"),
                            ("investment", "Investment"),
                            ("utility", "Utility"),
                            ("subscription", "Subscription"),
                            ("membership", "Membership"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("tv", "TV & Streaming"),
                            ("airtime", "Airtime & Data"),
                            ("internet", "Internet"),
                            ("school_fees", "School Fees"),
                            ("rent", "Rent"),
                            ("government", "Government Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        default="fixed",
                        help_text="fixed, variable, percentage, free",
                        max_length=20,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=12
                    ),
                ),
                ("min_tenure_days", models.IntegerField(default=0)),
                ("max_tenure_days", models.IntegerField(default=365)),
                ("eligibility_criteria", models.JSONField(blank=True, default=dict)),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("terms_conditions", models.TextField(blank=True)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("icon", models.CharField(default="📦", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="from-blue-500 to-blue-600", max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_products/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("auto_link_kitty", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_kitty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_service_products",
                        to="Payment.paymentgroups",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_products",
                        to="Payment.providerregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="providertransaction",
            name="service_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="Payment.serviceproduct",
            ),
        ),
        migrations.AddField(
            model_name="providerapplication",
            name="service_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="Payment.serviceproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="providerregistration",
            index=models.Index(
                fields=["user", "status"], name="Payment_pro_user_id_269fcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerregistration",
            index=models.Index(
                fields=["provider_type"], name="Payment_pro_provide_b51270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerregistration",
            index=models.Index(
                fields=["category"], name="Payment_pro_categor_656dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerstaff",
            index=models.Index(
                fields=["provider", "status"], name="Payment_pro_provide_3c2a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerstaff",
            index=models.Index(
                fields=["user", "role"], name="Payment_pro_user_id_6e42e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerstaff",
            unique_together={("provider", "user")},
        ),
        migrations.AddIndex(
            model_name="providerquery",
            index=models.Index(
                fields=["provider", "status"], name="Payment_pro_provide_382c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerquery",
            index=models.Index(
                fields=["assigned_to", "status"], name="Payment_pro_assigne_874c60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerquery",
            index=models.Index(
                fields=["user", "-created_at"], name="Payment_pro_user_id_ce3b86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providernotification",
            index=models.Index(
                fields=["provider", "is_read"], name="Payment_pro_provide_bd948f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providernotification",
            index=models.Index(
                fields=["user", "-created_at"], name="Payment_pro_user_id_de5c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceproduct",
            index=models.Index(
                fields=["provider", "status"], name="Payment_ser_provide_12ddd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceproduct",
            index=models.Index(
                fields=["service_type", "is_active"],
                name="Payment_ser_service_ef9cc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceproduct",
            index=models.Index(
                fields=["category"], name="Payment_ser_categor_8af4c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providertransaction",
            index=models.Index(
                fields=["provider", "-created_at"],
                name="Payment_pro_provide_234cf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providertransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="Payment_pro_user_id_694117_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providertransaction",
            index=models.Index(fields=["status"], name="Payment_pro_status_9bcff0_idx"),
        ),
        migrations.AddIndex(
            model_name="providertransaction",
            index=models.Index(
                fields=["reference_number"], name="Payment_pro_referen_541193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerapplication",
            index=models.Index(
                fields=["provider", "status"], name="Payment_pro_provide_f70c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerapplication",
            index=models.Index(
                fields=["user", "-created_at"], name="Payment_pro_user_id_46db75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerapplication",
            index=models.Index(
                fields=["application_type"], name="Payment_pro_applica_4b3f74_idx"
            ),
        ),
    ]
