# Generated by Django 5.2.11 on 2026-05-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0062_roundcontribution_allowed_swap_cycles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="piggybankconversionrequest",
            name="approval_vote",
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="approval_mode",
            field=models.CharField(
                choices=[
                    ("unanimous", "Unanimous - All must approve"),
                    ("majority", "Majority - Approvers move, rest get refund"),
                    ("any", "Any - Anyone can approve and form new group"),
                ],
                default="unanimous",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="approving_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="approving_conversion_requests",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="conversion_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Conversion - All funds to group"),
                    ("split", "Split - Form new subgroup with approvers"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="new_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_from_conversion",
                to="Payment.paymentgroups",
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="new_group_name",
            field=models.CharField(
                blank=True,
                help_text="Name for new subgroup if splitting",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="new_piggy_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversion_parent",
                to="Payment.grouptarget",
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="new_piggy_name",
            field=models.CharField(
                blank=True,
                help_text="Name for new piggy bank in new group",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="new_piggy_target",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target amount for new piggy bank",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Reason for conversion request"
            ),
        ),
        migrations.AddField(
            model_name="piggybankconversionrequest",
            name="rejecting_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="rejecting_conversion_requests",
                to="Payment.paymentgroupmember",
            ),
        ),
        migrations.AddField(
            model_name="transactiontoken",
            name="piggy_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="Payment.grouptarget",
            ),
        ),
        migrations.AlterField(
            model_name="piggybankconversionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("converted", "Converted/Archived"),
                    ("partial", "Partially Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactiontoken",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                    ("deposit", "Deposit"),
                    ("transfer", "Transfer"),
                    ("bid", "Bid"),
                    ("donation", "Donation"),
                    ("subscription", "Subscription"),
                    ("fee", "Fee"),
                    ("contribution", "Contribution"),
                    ("piggy_bank_contribution", "Piggy Bank Contribution"),
                    ("piggy_bank_withdrawal", "Piggy Bank Withdrawal"),
                    ("other", "Other"),
                ],
                default="purchase",
                max_length=200,
            ),
        ),
    ]
