# Generated by Django 5.2.11 on 2026-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0063_piggy_bank_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="automation_action",
            field=models.CharField(
                choices=[
                    ("none", "Do Nothing"),
                    ("wallet", "Transfer to My Wallet"),
                    ("group_fund", "Add to Group Fund"),
                    ("product", "Purchase a Product"),
                    ("service", "Purchase a Service"),
                    ("investment", "Invest in Opportunity"),
                    ("course", "Buy Course/Masterclass"),
                    ("group_join", "Join Group (Pay Fee)"),
                    ("donation", "Make Donation"),
                    ("custom", "Custom Automation"),
                ],
                default="wallet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to use for automation (default: full balance)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_executed",
            field=models.BooleanField(
                default=False, help_text="Whether automation has been executed"
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_target_id",
            field=models.CharField(
                blank=True, help_text="ID of the target item", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_target_name",
            field=models.CharField(
                blank=True, help_text="Name of target for display", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_target_type",
            field=models.CharField(
                blank=True,
                help_text="Type of target (product, service, investment, course, group)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="automation_trigger",
            field=models.CharField(
                choices=[
                    ("none", "No Automation"),
                    ("maturity", "On Maturity Date"),
                    ("withdrawal", "On Withdrawal"),
                    ("goal_achieved", "When Goal is Achieved"),
                    ("manual", "Manual Trigger Only"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Visible to everyone"),
                    ("group", "Group - Visible to group members only"),
                    ("private", "Private - Visible to owner only"),
                ],
                default="group",
                help_text="Who can see this piggy bank",
                max_length=20,
            ),
        ),
    ]
