# Generated by Django 5.2.11 on 2026-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0064_piggy_bank_automation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptarget",
            name="automation_target_id",
            field=models.CharField(
                blank=True, help_text="ID of the target item", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="grouptarget",
            name="automation_target_name",
            field=models.CharField(
                blank=True,
                help_text="Name of target for display",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grouptarget",
            name="automation_target_type",
            field=models.CharField(
                blank=True,
                help_text="Type of target (product, service, investment, course, group)",
                max_length=50,
                null=True,
            ),
        ),
    ]
