# Generated by Django 5.2.11 on 2026-05-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0065_fix_automation_nulls"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="max_withdrawal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount that can be withdrawn at once",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="max_withdrawals_per_day",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of withdrawals per day (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="min_withdrawal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount that can be withdrawn at once",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="require_min_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum balance that must remain in piggy bank",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="require_min_contribution_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Must have contributed at least this amount total",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="require_min_member_age_days",
            field=models.IntegerField(
                default=0,
                help_text="Member must be in group for this many days before withdrawing",
            ),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="require_min_savings_period_days",
            field=models.IntegerField(
                default=0,
                help_text="Must save for this many days before first withdrawal",
            ),
        ),
        migrations.AlterField(
            model_name="transactiontoken",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                    ("deposit", "Deposit"),
                    ("transfer", "Transfer"),
                    ("bid", "Bid"),
                    ("donation", "Donation"),
                    ("subscription", "Subscription"),
                    ("fee", "Fee"),
                    ("contribution", "Contribution"),
                    ("savings_deposit", "Savings Deposit"),
                    ("savings_withdrawal", "Savings Withdrawal"),
                    ("savings_withdrawal_penalty", "Savings Withdrawal with Penalty"),
                    ("piggy_bank_contribution", "Piggy Bank Savings"),
                    ("piggy_bank_withdrawal", "Piggy Bank Withdrawal"),
                    ("other", "Other"),
                ],
                default="purchase",
                max_length=200,
            ),
        ),
    ]
