# Generated by Django 5.2.11 on 2026-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0066_piggy_withdrawal_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowdispute",
            name="escalated",
            field=models.BooleanField(
                default=False, help_text="True if escalated to platform staff"
            ),
        ),
    ]
