# Generated by Django 5.2.11 on 2026-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0067_escrowdispute_escalated"),
    ]

    operations = [
        migrations.AddField(
            model_name="standingorder",
            name="approval_votes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of member IDs who approved"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="automation_type",
            field=models.CharField(
                choices=[
                    ("contribute", "Contribute"),
                    ("save", "Save"),
                    ("purchase", "Purchase"),
                    ("withdraw", "Withdraw"),
                    ("loan_repayment", "Loan Repayment"),
                    ("insurance", "Insurance"),
                    ("bills", "Bills & Airtime"),
                    ("investment", "Investment"),
                    ("donation", "Donation"),
                ],
                default="contribute",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="execution_day",
            field=models.IntegerField(
                default=1, help_text="Day of month (1-28) for monthly"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="execution_day_of_week",
            field=models.IntegerField(
                blank=True,
                help_text="Day of week: 0=Mon .. 6=Sun (weekly/fortnight)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="execution_time_end",
            field=models.TimeField(
                blank=True,
                help_text="End of execution window (or same as start for exact)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="execution_time_start",
            field=models.TimeField(
                blank=True, help_text="Start of execution window", null=True
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="rejection_votes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of member IDs who rejected"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Scheduled start date (after approval)", null=True
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_vote", "Pending Vote"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("paused", "Paused / Deactivated"),
                    ("rejected", "Rejected"),
                ],
                default="pending_vote",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="target_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the target entity",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="target_name",
            field=models.CharField(
                blank=True,
                help_text="Display name of the target",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="target_type",
            field=models.CharField(
                blank=True,
                help_text="kitty, piggy_bank, loan, product, insurance, donation, investment, group",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="withdrawal_current_index",
            field=models.IntegerField(
                default=0, help_text="Current position in the sequential cycle"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="withdrawal_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Members at Once"),
                    ("sequential", "Sequential / Rotating"),
                    ("selected", "Selected Members"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="withdrawal_recipients",
            field=models.JSONField(
                blank=True, default=list, help_text="Member IDs receiving withdrawal"
            ),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="withdrawal_sequence",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered member IDs for sequential mode",
            ),
        ),
        migrations.AlterField(
            model_name="standingorder",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnight", "Fortnight (14 days)"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(fields=["status"], name="Payment_sta_status_5c7287_idx"),
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(
                fields=["automation_type"], name="Payment_sta_automat_5ff848_idx"
            ),
        ),
    ]
