# Generated by Django 5.2.11 on 2026-05-23 11:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0014_profile_country_code_profile_preferred_currency"),
        ("Payment", "0068_standingorder_approval_votes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "service_quality",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "responsiveness",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "value_for_money",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="User has completed a transaction with this provider",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Review is visible to public"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="Payment.providerregistration",
                    ),
                ),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to="Payment.providerapplication",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to="Payment.providertransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_ratings",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-created_at"],
                        name="Payment_pro_provide_685eaa_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="Payment_pro_user_id_381b85_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_approved"],
                        name="Payment_pro_provide_d58e7d_idx",
                    ),
                ],
                "unique_together": {("provider", "user", "related_transaction")},
            },
        ),
    ]
