# Generated by Django 5.2.11 on 2026-05-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0070_piggybankactionrequest_piggybankactionrequestvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="balance_after",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
