# Generated by Django 5.2.11 on 2026-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0072_transactiontoken_balance_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="billstandingorder",
            name="consecutive_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billstandingorder",
            name="next_run_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="consecutive_failures",
            field=models.IntegerField(default=0),
        ),
    ]
