# Generated by Django 5.2.11 on 2026-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0073_billstandingorder_consecutive_failures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="group_member_balance_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Member's specific balance or contribution total within the group at time of transaction",
                max_digits=12,
                null=True,
            ),
        ),
    ]
