# Generated by Django 5.2.11 on 2026-06-01 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0074_transactionhistory_group_member_balance_after"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiggyBankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("contribution", "Contribution"),
                            ("withdrawal", "Withdrawal"),
                            ("member_joined", "Member Joined"),
                            ("member_left", "Member Left"),
                            ("approval_requested", "Approval Requested"),
                            ("approval_approved", "Approval Approved"),
                            ("approval_rejected", "Approval Rejected"),
                            ("conversion", "Conversion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "piggy_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piggy_events",
                        to="Payment.grouptarget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["piggy_bank", "event_type"],
                        name="Payment_pig_piggy_b_887be2_idx",
                    ),
                    models.Index(
                        fields=["piggy_bank", "-created_at"],
                        name="Payment_pig_piggy_b_f2bbfa_idx",
                    ),
                ],
            },
        ),
    ]
