# Generated by Django 5.2.11 on 2026-06-03 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0076_piggybankactionrequest_merge_and_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptarget",
            name="leave_inconvenience_fee_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="leave_requires_vote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grouptarget",
            name="leave_vote_waives_penalty",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="piggybankactionrequest",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("extend_maturity", "Extend Maturity Date"),
                    ("withdraw", "Withdraw Amount"),
                    ("dissolve", "Dissolve Piggy Bank"),
                    ("merge", "Merge Piggy Banks"),
                    ("leave", "Leave Piggy Bank"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PiggyBankMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_contributed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.paymentprofile",
                    ),
                ),
                (
                    "piggy_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piggy_members",
                        to="Payment.grouptarget",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["piggy_bank"], name="Payment_pig_piggy_b_9201c0_idx"
                    ),
                    models.Index(
                        fields=["payment_profile"],
                        name="Payment_pig_payment_3c9c1f_idx",
                    ),
                ],
                "unique_together": {("piggy_bank", "payment_profile")},
            },
        ),
    ]
