# Generated by Django 5.2.11 on 2026-06-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0078_backfill_piggybankmembers"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerregistration",
            name="account_format",
            field=models.CharField(
                blank=True,
                help_text='Regex pattern for account number validation (e.g., "^[0-9]{10}$")',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="providerregistration",
            name="account_label",
            field=models.CharField(
                default="Account Number",
                help_text='Label for the account field shown to users (e.g., "Meter Number", "Policy Number")',
                max_length=100,
            ),
        ),
    ]
