# Generated by Django 5.2.11 on 2026-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0079_providerregistration_account_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerregistration",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("bill_provider", "Bill Provider"),
                    ("insurance_provider", "Insurance Provider"),
                    ("loan_provider", "Loan Provider"),
                    ("utility_provider", "Utility Provider"),
                    ("financial_service", "Financial Service"),
                    ("government_service", "Government Service"),
                    ("course_provider", "Course Provider"),
                ],
                max_length=50,
            ),
        ),
    ]
