# Generated by Django 5.2.11 on 2026-06-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0080_alter_providerregistration_provider_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceproduct",
            name="provider_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insurance_products",
                to="Payment.providerregistration",
            ),
        ),
        migrations.AlterField(
            model_name="insuranceproduct",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Insurance company name (legacy — use provider_registration)",
                max_length=200,
            ),
        ),
    ]
