# Generated by Django 5.2.11 on 2026-06-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0081_insuranceproduct_provider_registration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="provider_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_products",
                to="Payment.providerregistration",
            ),
        ),
    ]
