# Generated by Django 5.2.11 on 2026-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0082_loanproduct_provider_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowtransaction",
            name="payment_gateway",
            field=models.CharField(
                blank=True,
                default="wallet",
                help_text="wallet, stripe, paystack, flutterwave, pesapal, paypal",
                max_length=30,
            ),
        ),
    ]
