# Generated by Django 5.2.11 on 2026-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0083_alter_escrowtransaction_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontoken',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
