# Generated by Django 5.1.7 on 2025-11-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0047_rename_institution_defaultroom_inst_or_org_name_and_more"),
        ("Specialization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specialization_rooms",
                to="Rooms.room",
            ),
        ),
    ]
