# Generated by Django 5.1.7 on 2026-01-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="A431A4415C", editable=False, max_length=200, unique=True
            ),
        ),
    ]
