# Generated by Django 5.1.7 on 2026-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="B91076C335", editable=False, max_length=200, unique=True
            ),
        ),
    ]
