# Generated by Django 5.1.7 on 2025-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0003_remove_specializationroom_added_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specializationroom",
            name="members_type",
            field=models.CharField(
                choices=[
                    ("individuals", "Individuals"),
                    ("rooms", "Rooms"),
                    ("rooms_and_individuals", "Both Rooms and Individuals"),
                ],
                default="individuals",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="95954A2AAC", editable=False, max_length=200, unique=True
            ),
        ),
    ]
