# Generated by Django 5.1.7 on 2025-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0004_specializationroom_members_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="467C50EAC0", editable=False, max_length=200, unique=True
            ),
        ),
    ]
