# Generated by Django 5.1.7 on 2026-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0005_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="C8C4CB854B", editable=False, max_length=200, unique=True
            ),
        ),
    ]
