# Generated by Django 5.1.7 on 2025-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0005_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="078D9FA515", editable=False, max_length=200, unique=True
            ),
        ),
    ]
