# Generated by Django 5.1.7 on 2026-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0006_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="9E250E7BC0", editable=False, max_length=200, unique=True
            ),
        ),
    ]
