# Generated by Django 5.1.7 on 2026-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0007_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="CC03F073AC", editable=False, max_length=200, unique=True
            ),
        ),
    ]
