# Generated by Django 5.1.7 on 2026-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0007_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="F5F405B956", editable=False, max_length=200, unique=True
            ),
        ),
    ]
