# Generated by Django 5.1.7 on 2025-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0007_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="5757996BDC", editable=False, max_length=200, unique=True
            ),
        ),
    ]
