# Generated by Django 5.2.11 on 2026-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0008_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="6EDA6C33A6", editable=False, max_length=200, unique=True
            ),
        ),
    ]
