# Generated by Django 5.2.11 on 2026-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0009_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="53AAD83C17", editable=False, max_length=200, unique=True
            ),
        ),
    ]
