# Generated by Django 5.1.7 on 2026-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0009_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="2F51FE3DC2", editable=False, max_length=200, unique=True
            ),
        ),
    ]
