# Generated by Django 5.1.7 on 2025-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0011_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="AD82D72F2B", editable=False, max_length=200, unique=True
            ),
        ),
    ]
