# Generated by Django 5.2.11 on 2026-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0011_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="BE5C514413", editable=False, max_length=200, unique=True
            ),
        ),
    ]
