# Generated by Django 5.2.11 on 2026-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0012_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="331D2E82A4", editable=False, max_length=200, unique=True
            ),
        ),
    ]
