# Generated by Django 5.2.11 on 2026-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0013_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="8D94F31A1E", editable=False, max_length=200, unique=True
            ),
        ),
    ]
