# Generated by Django 5.2.11 on 2026-03-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0014_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="EA3DF2633E", editable=False, max_length=200, unique=True
            ),
        ),
    ]
