# Generated by Django 5.1.7 on 2025-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0014_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="specializationroom",
            name="related_specialization_rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_specialization_rooms",
                to="Specialization.specializationroom",
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="0CEEF0768A", editable=False, max_length=200, unique=True
            ),
        ),
    ]
