# Generated by Django 5.2.11 on 2026-03-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0015_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="2D7E9753B3", editable=False, max_length=200, unique=True
            ),
        ),
    ]
