# Generated by Django 5.1.7 on 2025-11-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Specialization",
            "0015_specializationroom_related_specialization_rooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="related_specialization_rooms",
            field=models.ManyToManyField(
                blank=True, to="Specialization.specializationroom"
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="5322FC7BDB", editable=False, max_length=200, unique=True
            ),
        ),
    ]
