# Generated by Django 5.1.7 on 2025-11-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Specialization",
            "0016_alter_specializationroom_related_specialization_rooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="C22023F32D", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="PositionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Specialization.specialization",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Specialization.stack",
                    ),
                ),
            ],
        ),
    ]
