# Generated by Django 5.2.11 on 2026-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0017_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="stack",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="81C334E02D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
