# Generated by Django 5.1.7 on 2025-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0017_alter_specializationroom_room_code_positiontracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="36ADA6EDF8", editable=False, max_length=200, unique=True
            ),
        ),
    ]
