# Generated by Django 5.2.11 on 2026-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0018_specialization_image_url_stack_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="B4BDD65081", editable=False, max_length=200, unique=True
            ),
        ),
    ]
