# Generated by Django 5.1.7 on 2025-12-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        (
            "Specialization",
            "0019_specialization_admins_specialization_members_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="BDED267FC3", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="created_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="created_specializations",
                to="Authentication.profile",
            ),
        ),
    ]
