# Generated by Django 5.1.7 on 2025-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0020_remove_specialization_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="F25E3A106B", editable=False, max_length=200, unique=True
            ),
        ),
    ]
