# Generated by Django 5.1.7 on 2025-12-03 06:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        ("Specialization", "0021_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="4A932D4F33", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer_name", models.CharField(max_length=50000)),
                (
                    "certificate_file",
                    models.FileField(upload_to="specialization/certificates/"),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.profile",
                    ),
                ),
                (
                    "specialization",
                    models.ManyToManyField(
                        blank=True, to="Specialization.specialization"
                    ),
                ),
                (
                    "stack",
                    models.ManyToManyField(blank=True, to="Specialization.stack"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(upload_to="specialization/certificates/issued/"),
                ),
                ("issued_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "issued_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.profile",
                    ),
                ),
                (
                    "specialization",
                    models.ManyToManyField(
                        blank=True, to="Specialization.specialization"
                    ),
                ),
                (
                    "stack",
                    models.ManyToManyField(blank=True, to="Specialization.stack"),
                ),
            ],
        ),
    ]
