# Generated by Django 5.2.11 on 2026-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0021_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specialization",
            name="learning_type",
            field=models.CharField(
                choices=[
                    ("specialization", "Specialization"),
                    ("course", "Course"),
                    ("masterclass", "Masterclass"),
                ],
                default="specialization",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="39B6E7CE4C", editable=False, max_length=200, unique=True
            ),
        ),
    ]
