# Generated by Django 5.1.7 on 2025-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Specialization",
            "0022_alter_specializationroom_room_code_certificate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="specializationroom",
            name="operation_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("under_review", "Under Review"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sensored", "Sensored"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="specializationroom",
            name="text_priority",
            field=models.CharField(
                choices=[
                    ("admins_only", "Admins Only"),
                    ("admins_moderators_only", "Admins and Moderators Only"),
                    ("all_members", "All Members"),
                    ("creator_only", "Creator Only"),
                ],
                default="creator",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="08C6B72169", editable=False, max_length=200, unique=True
            ),
        ),
    ]
