# Generated by Django 5.2.11 on 2026-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Specialization",
            "0022_specialization_is_paid_specialization_learning_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="DB5A61D778", editable=False, max_length=200, unique=True
            ),
        ),
    ]
