# Generated by Django 5.2.11 on 2026-03-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0023_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="C8FC21E675", editable=False, max_length=200, unique=True
            ),
        ),
    ]
