# Generated by Django 5.1.7 on 2026-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0023_specializationroom_operation_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="443EAE5990", editable=False, max_length=200, unique=True
            ),
        ),
    ]
