# Generated by Django 5.1.7 on 2026-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0024_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="5F87B82D37", editable=False, max_length=200, unique=True
            ),
        ),
    ]
