# Generated by Django 5.2.11 on 2026-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0024_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="BDFBA9A1CB", editable=False, max_length=200, unique=True
            ),
        ),
    ]
