# Generated by Django 5.2.11 on 2026-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0025_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="26895B6BAF", editable=False, max_length=200, unique=True
            ),
        ),
    ]
