# Generated by Django 5.2.11 on 2026-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0027_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="475B0F8B05", editable=False, max_length=200, unique=True
            ),
        ),
    ]
