# Generated by Django 5.2.11 on 2026-04-04 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0012_customuser_onboarding_completed"),
        ("Specialization", "0029_alter_specializationroom_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="auto_generate",
            field=models.BooleanField(
                default=True, help_text="Auto-issue on completion"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("completion", "Certificate of Completion"),
                    ("distinction", "Certificate with Distinction"),
                    ("custom", "Custom Certificate"),
                ],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="min_score",
            field=models.PositiveIntegerField(
                default=70, help_text="Min quiz score for distinction"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="template_html",
            field=models.TextField(
                blank=True, help_text="HTML template for auto-generated certs"
            ),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="average_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_instances",
                to="Specialization.certificate",
            ),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="grade",
            field=models.CharField(
                blank=True, help_text="e.g. A, B+, Pass", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="hours_completed",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="verification_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                blank=True, null=True, upload_to="specialization/certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="issuer_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="issuedcertificate",
            name="certificate_file",
            field=models.FileField(
                blank=True, null=True, upload_to="specialization/certificates/issued/"
            ),
        ),
        migrations.AlterField(
            model_name="issuedcertificate",
            name="issued_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="received_certificates",
                to="Authentication.profile",
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="BDC7DCA65A", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Text / Article"),
                            ("audio", "Audio / Podcast"),
                            ("image", "Image / Infographic"),
                            ("code", "Code Snippet"),
                            ("file", "Downloadable File"),
                            ("embed", "External Embed"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, help_text="Rich text / markdown content"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube / Vimeo / direct link",
                        max_length=500,
                    ),
                ),
                ("audio_url", models.URLField(blank=True, max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "file_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="specialization/lessons/files/"
                    ),
                ),
                (
                    "code_snippet",
                    models.TextField(
                        blank=True, help_text="Code content with language tag"
                    ),
                ),
                (
                    "code_language",
                    models.CharField(blank=True, default="python", max_length=50),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="External resource link", max_length=500
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveIntegerField(default=10)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Can be viewed without enrollment"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Requires payment to unlock"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="Specialization.stack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("stack", "order")},
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("after_lesson", "After a Lesson"),
                            ("end_of_module", "End of Module Test"),
                            ("final_exam", "Final Exam for Specialization"),
                        ],
                        default="end_of_module",
                        max_length=20,
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70, help_text="Minimum % to pass"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="Specialization.lesson",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="Specialization.specialization",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="Specialization.stack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=list)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="Specialization.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                            ("code_challenge", "Code Challenge"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of choice objects for MC/TF",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True, help_text="For short answer / code challenge"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Shown after answering"),
                ),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "code_template",
                    models.TextField(
                        blank=True, help_text="Starter code for code challenges"
                    ),
                ),
                (
                    "code_language",
                    models.CharField(blank=True, default="python", max_length=50),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Specialization.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("free", "Free Access"),
                            ("paid", "Paid & Unlocked"),
                            ("locked", "Payment Required"),
                            ("trial", "Trial Access"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="Specialization.specialization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "specialization")},
            },
        ),
        migrations.CreateModel(
            name="LearnerProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="Specialization.lesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
