# Generated by Django 5.2.11 on 2026-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0030_certificate_auto_generate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="86F225259E", editable=False, max_length=200, unique=True
            ),
        ),
    ]
