# Generated by Django 5.2.11 on 2026-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0031_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="5CF1A21BBC", editable=False, max_length=200, unique=True
            ),
        ),
    ]
