# Generated by Django 5.2.11 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0032_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="68DCA45D88", editable=False, max_length=200, unique=True
            ),
        ),
    ]
