# Generated by Django 5.2.11 on 2026-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0034_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="4E5DF1BEB4", editable=False, max_length=200, unique=True
            ),
        ),
    ]
