# Generated by Django 5.2.11 on 2026-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0036_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="5D0588A97D", editable=False, max_length=200, unique=True
            ),
        ),
    ]
