# Generated by Django 5.2.11 on 2026-06-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0081_insuranceproduct_provider_registration_and_more"),
        ("Specialization", "0039_alter_specializationroom_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specializations",
                to="Payment.providerregistration",
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="6E81CF9427", editable=False, max_length=200, unique=True
            ),
        ),
    ]
