# Generated by Django 5.2.11 on 2026-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0040_specialization_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="stack_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of stack IDs for drag-and-drop arrangement",
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="E7B8BC3D7F", editable=False, max_length=200, unique=True
            ),
        ),
    ]
