# Generated by Django 5.2.11 on 2026-06-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0041_specialization_stack_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="74547A4C8D", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="LessonContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("code", "Code"),
                            ("file", "File"),
                            ("embed", "Embed"),
                            ("quiz", "Quiz Reference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text / Code / Caption content"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Video / Audio / Image / Embed URL",
                        max_length=500,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="specialization/blocks/"
                    ),
                ),
                (
                    "code_language",
                    models.CharField(blank=True, default="plaintext", max_length=50),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="Specialization.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("lesson", "order")},
            },
        ),
    ]
