# Generated by Django 5.2.11 on 2026-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0042_alter_specializationroom_room_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color for lesson",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="lessoncontentblock",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color for this content block",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color for course card",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="stack",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color for module card",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="D4180CA554", editable=False, max_length=200, unique=True
            ),
        ),
    ]
