# Generated by Django 5.2.11 on 2026-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0043_lesson_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="E0019A4D75", editable=False, max_length=200, unique=True
            ),
        ),
    ]
