# Generated by Django 5.2.11 on 2026-06-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0044_lesson_slug_alter_specializationroom_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allow_back_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Allow going back to previous questions. Auto-disabled when per_question timer is set.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="display_mode",
            field=models.CharField(
                choices=[("whole", "Whole Test"), ("one_by_one", "One at a Time")],
                default="whole",
                help_text="Show all questions at once or one per page",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="pass_mark_to_continue",
            field=models.BooleanField(
                default=False,
                help_text="Must achieve passing score to unlock next lesson/module",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="show_results_immediately",
            field=models.BooleanField(
                default=True,
                help_text="Show pass/fail and answers right after submission",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_per_question",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seconds per question when timer_mode is per_question",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="timer_mode",
            field=models.CharField(
                choices=[("per_test", "Per Test"), ("per_question", "Per Question")],
                default="per_test",
                help_text="Timer applies to entire test or each question",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="lock_for_unenrolled",
            field=models.BooleanField(
                default=True, help_text="Lessons locked for unenrolled students"
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="sequential_locking",
            field=models.BooleanField(
                default=False,
                help_text="Must complete previous lesson/module before accessing next",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="skip_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Disable skipping lessons; progress must be sequential",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time limit for entire test in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="C31C42D143", editable=False, max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                            ("peer_review", "Peer Review"),
                            ("reflection", "Reflection"),
                        ],
                        default="assignment",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("submission_required", models.BooleanField(default=False)),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days from enrollment to complete",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="Specialization.stack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("setup_guide", models.TextField(blank=True)),
                ("expected_output", models.TextField(blank=True)),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {label, url} objects",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="Specialization.stack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ActivitySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="specialization/activities/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="Specialization.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("activity", "user")},
            },
        ),
    ]
