# Generated by Django 5.2.11 on 2026-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Specialization",
            "0045_quiz_allow_back_navigation_quiz_display_mode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="content_blocks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {type, content, url, caption, order} blocks",
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="content_blocks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {type, content, url, caption, order} blocks",
            ),
        ),
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="49FCF3267F", editable=False, max_length=200, unique=True
            ),
        ),
    ]
