# Generated by Django 5.2.11 on 2026-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialization", "0046_activity_content_blocks_lab_content_blocks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializationroom",
            name="room_code",
            field=models.CharField(
                default="4A40D8E4AD", editable=False, max_length=200, unique=True
            ),
        ),
    ]
