# Generated by Django 5.2.11 on 2026-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialization', '0048_alter_certificate_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializationroom',
            name='room_code',
            field=models.CharField(default='75B81B8411', editable=False, max_length=200, unique=True),
        ),
    ]
