# Generated by Django 5.1.7 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QomAI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="model_used",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preferred_model",
            field=models.CharField(default="qwen-7b", max_length=255),
        ),
    ]
