# Generated by Django 5.1.7 on 2026-02-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Opinions", "0002_opinion_institution_opinion_organisation"),
        ("Rooms", "0005_alter_defaultroom_room_code_alter_room_organisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opinion",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="Rooms.room",
            ),
        ),
    ]
