# Generated by Django 5.2.11 on 2026-02-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Opinions",
            "0004_story_storyview_story_opinions_st_created_2d73c6_idx_and_more",
        ),
        ("Payment", "0012_alter_paymentprofile_payment_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="establishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="Payment.establishment",
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="poster_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner/Creator"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                help_text="Role of poster within the entity at time of posting",
                max_length=20,
                null=True,
            ),
        ),
    ]
