# Generated by Django 5.2.11 on 2026-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Opinions", "0005_opinion_establishment_opinion_poster_role"),
        ("Rooms", "0006_roomtyping"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="tagged_rooms",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_in_opinions", to="Rooms.room"
            ),
        ),
    ]
