# Generated by Django 5.2.11 on 2026-03-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0008_institution_portal_password_and_more"),
        ("Opinions", "0006_opinion_tagged_rooms"),
        ("Organisation", "0008_organisation_portal_password_and_more"),
        ("Payment", "0015_order_is_offline_order_sales_channel_product_sku_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinioncomment",
            name="establishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinion_comments",
                to="Payment.establishment",
            ),
        ),
        migrations.AddField(
            model_name="opinioncomment",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinion_comments",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="opinioncomment",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinion_comments",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="opinioncomment",
            name="poster_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner/Creator"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                help_text="Role of poster within the entity at time of posting",
                max_length=20,
                null=True,
            ),
        ),
    ]
