import random
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from QNotes.models import QNote

SAMPLE_NOTES = [
    "Just realized my plants have better communication skills than most people I know. They just vibe.**Literally.**",
    "Hot take: pineapple on pizza is actually a **masterpiece** of flavor engineering.",
    "I tried meditation today. My brain said 'best I can do is a to-do list from 2019.'",
    "If you can't find me, I'm probably staring at the ceiling questioning every life choice that led me here.",
    "**Pro tip:** Sometimes the best productivity hack is admitting you won't be productive today. *Freedom.*",
    "Someone said 'follow your dreams' so I followed them to the fridge. No regrets.",
    "New fear unlocked: your playlist shuffles and the song that plays is the exact mood you *didn't* want to confront.",
    "There are two types of people: those who organize their books by color, and those who are **chaos gremlins**.",
    "If my life was a movie, the critics would say 'confusing plot, questionable decisions, great soundtrack.'",
    "I'm not procrastinating, I'm conducting **extensive research** on the structural integrity of my ceiling.",
    "*Imagine* having your life together. Couldn't be me. But I'm happy for whoever that is. 👉",
    "My GPS and I have a toxic relationship. It says 'turn left,' I turn right. We both suffer.",
    "Therapy thought: maybe my toxic trait is expecting my coffee to fix everything. *It still does though.*",
    "I need a 48-hour day just to catch up on sleep I lost from staying up too late.",
    "**Breaking news:** local person dramatically sighs for the 47th time today. More at 11.",
    "If adulthood is just paying bills and being tired, who signed me up for this subscription?",
    "The amount of effort it takes to be 'social' could power a small city. *Leave me alone.*",
    "Current status: running on caffeine, chaos, and the faint hope that tomorrow will be better.",
    "I wish my brain came with a 'mute' button for 3 AM existential crises.",
    "I'm in my **'I don't know what I'm doing but I look confident'** era.",
    "Why do I feel personally attacked by my alarm clock every single morning?",
    "My comfort show is playing, my snacks are ready, and the outside world doesn't exist. *Heaven.*",
    "If you don't laugh at your own jokes, who will? *Exactly.*",
    "I'm convinced my WiFi signal has a personal vendetta against me.",
    "Trying to fold fitted sheets is my ultimate villain origin story.",
    "Emotional support water bottle. It's a thing. *Don't judge me.*",
    "The phrase 'it is what it is' is doing **heavy lifting** in my daily vocabulary.",
    "Memory of a goldfish, heart of a lion, sleep schedule of a raccoon.",
    "My internal monologue should come with a **parental advisory** sticker.",
    "Warning: I'm currently operating on **low battery mode** (emotionally and literally).",
    "**Hot take:** The best conversations happen after midnight when nobody remembers them.",
    "I'm not saying I'm a genius, but I did figure out how to use 3 apps at once to avoid one task.",
    "If my life had a loading screen, it would say 'please wait... indefinitely.'",
    "Sometimes I surprise myself with how **dramatic** I can be over minor inconveniences.",
    "My spirit animal is a half-empty coffee mug that's been microwaved 3 times.",
    "The older I get, the more I appreciate a really good nap. **God-tier naps.**",
    "I need to start a support group for people who overthink themselves into paralysis.",
    "**No thoughts**, just vibes. And also 47 tabs open in my brain.",
    "My to-do list is less of a list and more of a **suggestion box** that I ignore.",
    "I'm exactly 3 bad days away from becoming a hermit in the woods.",
    "Head empty, only #mood playlists and intrusive thoughts.",
    "**Mood:** Staring at the wall while my brain buffers like old YouTube.",
    "I've mastered the art of looking busy while doing absolutely nothing.",
    "My brain at 3 AM: 'Let's replay every embarrassing moment from 2014.'",
    "Adulting is just googling how to do basic tasks and pretending you knew all along.",
    "I want someone to look at me the way I look at a fresh bag of chips.",
    "**Life update:** Still figuring it out. Will report back when I do.",
    "My patience level is directly proportional to how well I've slept. *Spoiler: I haven't.*",
    "Why is it that the best ideas come at 2 AM when you can't act on them?",
    "I've unlocked a new achievement: emotional damage speedrun any%.",
    "If I had a dollar for every time I said 'I'll do it later,' I'd be rich enough to pay someone else to do it.",
    "My comfort zone and I are in a **serious relationship.** Please don't disturb us.",
    "The audacity of my alarm clock to go off when I'm clearly in the middle of a good dream.",
    "**Plot twist:** My life is a series of plot twists that lead nowhere.",
    "I'm in my **character development** arc. It's mostly just me sleeping.",
    "If being tired was a sport, I'd be an Olympic gold medalist.",
    "Therapy is expensive, so I just talk to my cat now. *She gets it.*",
    "I've reached the point where 'I'll sleep when I'm dead' is no longer a joke.",
    "My toxic trait is thinking I can function on 4 hours of sleep. *I cannot.*",
    "**Spoiler alert:** I did not get my life together today. Maybe tomorrow.",
    "I'm not lazy, I'm in **energy conservation mode.** It's eco-friendly.",
    "The urge to just start fresh with a new identity somewhere far away. *Anyone else?*",
    "My brain is a beautiful chaos of unfinished thoughts and forgotten",
    "I need a vacation from my vacation. The math isn't mathing.",
    "**Current mood:** A mix of 'I got this' and 'who allowed this.'",
    "My social battery is currently in the negatives. Please charge later.",
    "I've been adulting for years and I still don't know what I'm doing. *Fake it till you make it.*",
    "The Venn diagram of 'things I want to do' and 'things I actually do' is just two separate circles.",
    "I wish my ability to procrastinate was as strong as my ability to worry. *Wait, no.*",
    "I'm not ignoring you, I'm just saving my energy for important things. *Like sleep.*",
    "The most dangerous phrase in my vocabulary: 'I'll do it in 5 minutes.'",
    "**Mental health check:** Is this anxiety, or am I just hungry? *Both probably.*",
    "I've become a professional at avoiding my problems. It's a **full-time job.**",
    "My internal monologue needs a **content warning** for excessive sass.",
    "I'm starting to think my circadian rhythm is actually just chaotic neutral.",
    "**Life hack:** Lower your expectations and you'll never be disappointed. *Works every time.*",
    "The amount of brain power I use to overthink simple decisions could power a small country.",
    "I'm not saying I'm addicted to caffeine, but my blood type is basically 'espresso.'",
    "My ability to zone out during important conversations is **unmatched.**",
    "**Unpopular opinion:** The best part of the day is when you finally get to take off your bra/jeans.",
    "I have the emotional range of a teaspoon and the anxiety of a superhero.",
    "My life is a series of 'what if' scenarios that never play out.",
    "I need to stop treating my bed like a magnet that I can't escape from.",
    "**Update:** Still not a morning person. Will retest tomorrow.",
    "My brain feels like a browser with 47 tabs open and 3 of them are frozen.",
    "The older I get, the more I appreciate silence. *Blessed silence.*",
    "I've reached the 'I don't care what anyone thinks' stage. *It's freeing.*",
    "My default response to everything: 'I'll think about it.' *I won't.*",
    "**Current state:** A complex mix of exhaustion, ambition, and the desire to eat cookies in bed.",
    "I'm in my feelings era. It's messy, but the outfits are great.",
    "The struggle between wanting to be productive and wanting to do nothing is **real.**",
    "My life philosophy is based entirely on quotes I read on the internet. *Working great so far.*",
    "I wish my brain would stop replaying that embarrassing thing I said 7 years ago.",
    "I'm not antisocial, I'm just selectively social. *The selection is very limited.*",
    "**New rule:** No major decisions after 10 PM. My 10 PM self is a reckless dreamer.",
    "I need a personalized hype person to follow me around and tell me I'm doing great.",
    "My ability to find things in the last place I look is **uncanny.** *Because I stop looking.*",
    "I'm not weird, I'm a **limited edition.** *Only one of me, thankfully.*",
    "**Life update:** Still vibing, despite the chaos. *That's a win.*",
    "My brain's favorite activity is thinking about all the things I should be doing instead of doing them.",
    "If my life was a Netflix series, it would be a **critically acclaimed** one-season wonder.",
    "I've achieved a new level of tired where even coffee says 'good luck with that.'",
    "The amount of emotional baggage I carry would exceed the airline weight limit.",
    "**Hot take:** Overthinking is just my brain's favorite hobby. *I'm a professional.*",
    "I need a manual for my own brain because I have no idea what's going on up there.",
    "My spirit is willing, but my flesh is weak and also very sleepy.",
    "I'm not saying I'm a drama queen, but I did cry over a commercial yesterday.",
    "**Life motto:** 'It's fine.' *It's not fine, but we move.*",
    "I wish I could Ctrl+Z my life decisions sometimes.",
    "My comfort zone is a fortress and I'm not coming out. *Ever.*",
    "I'm in a committed relationship with my bed. It understands me.",
    "My brain's processing speed: dial-up in a 5G world.",
    "**Breaking:** Local person successfully completed one task today. Celebrations underway.",
    "I need to create a playlist called 'songs that make me feel like the main character.'",
    "My toxic trait is giving advice I don't follow myself. *But it's good advice though.*",
    "If sarcasm was a superpower, I'd be an Avenger.",
    "**Mood:** A gentle reminder that I don't have to have it all figured out. *But it would be nice.*",
    "I've reached the point in my life where I actively look forward to going to bed early.",
    "My brain is like a bad WiFi signal — sometimes it connects, mostly it doesn't.",
    "I'm not dramatic. I'm just **emotionally expressive.** *There's a difference.*",
    "Life is a series of 'one more episode' decisions that ruin my sleep schedule.",
    "**Real talk:** Some days the only thing that gets me through is the thought of my bed.",
    "I'm in my 'healing era' but healing requires effort and I'm tired.",
    "My default emotional state is a slight sense of impending doom mixed with mild hunger.",
    "I've mastered the art of pretending I have everything under control. *Oscar-worthy.*",
    "**Life advice:** Sometimes you just need to laugh at the absurdity of it all.",
    "My brain during a serious conversation: 'lol remember that funny cat video.'",
    "If overthinking was an Olympic sport, I'd be a gold medalist with a world record.",
    "I need to stop saying 'I'm fine' when I'm clearly not. *Therapy is working.*",
    "**Current mood:** Tired of being tired. It's a whole new level of exhaustion.",
    "My life feels like a side quest that I accidentally made the main quest.",
    "I've learned that 'I'll sleep when I'm dead' is not a flex. *Sleep is a flex.*",
    "The amount of emotional support I require rivals that of a small army.",
    "**Hot take:** Being an adult is just having a to-do list that never ends.",
    "I'm convinced that my bed is the only place where I can truly be myself.",
    "My journey to self-improvement is a series of 2 steps forward, 1 step back, and a nap.",
    "**Life update:** Currently accepting applications for a personal assistant to manage my life.",
    "I need a warning label on my forehead: 'May suddenly need alone time.'",
    "My internal dialogue sounds like a motivational speaker and a pessimist having an argument.",
    "The struggle is real, but so is my ability to ignore it. *For now.*",
    "**Mood:** A complicated mix of 'I got this' and 'I need a hug.'",
    "I've unlocked the achievement: 'Professional Procrastinator Level 100.'",
    "My spirit animal is a sloth on a coffee break. *Living the dream.*",
    "The amount of emotional labor I do should be a paid position.",
    "**Breaking news:** Local person still figuring things out. More at 11.",
    "My comfort zone is my happy place. Don't try to drag me out.",
    "I need a reboot button for my brain. It's currently stuck on a loading screen.",
    "**Life truth:** The best conversations are the ones that go absolutely nowhere.",
    "I'm not lazy, I'm in **power-saving mode.** It's a feature, not a bug.",
    "My thought process: 'What if... nevermind, that's too much effort.'",
    "I've reached a point where I need a vacation from my thoughts.",
    "**Real talk:** Self-care is sometimes just doing nothing and not feeling guilty about it.",
    "My brain is a beautiful, chaotic mess of ideas that never see the light of day.",
    "**Update:** Still surviving. That's the goal. *One day at a time.*",
    "The older I get, the more I appreciate the small wins. *Like finding a matching sock.*",
    "My life philosophy can be summed up in 3 words: 'We'll see what happens.'",
    "I need a hobby that doesn't involve staring at a screen. *Suggestions welcome.*",
    "**Mood:** Trying to be optimistic but my brain keeps showing me the fine print.",
    "If anxiety was a currency, I'd be a billionaire. *Thanks, brain.*",
    "I've accepted that my life will always be a work in progress. *And that's okay.*",
    "My ability to procrastinate is matched only by my ability to feel guilty about it.",
    "**Life hack:** Sometimes 'good enough' is actually perfect. *Let it go.*",
    "I'm not ignoring my responsibilities, I'm just prioritizing my peace. *It's called self-care.*",
    "My brain's favorite game is 'what's that sound?' at 3 AM.",
    "I need to frame 'progress, not perfection' somewhere I can see it every day.",
    "**Current status:** Existing. That counts for something, right?",
    "My internal monologue runs on sarcasm and spite. *It's efficient.*",
    "The amount of time I spend thinking about what I should be doing is time I could be doing it.",
    "**Hot take:** Healing isn't linear. Some days you're thriving, other days you're surviving.",
    "I've learned that it's okay to not be okay. *But it still sucks.*",
    "My ability to worry is unmatched. I worry about not worrying enough.",
    "**Life lesson:** Sometimes the bravest thing you can do is ask for help.",
    "I'm in my 'glow up' era but it's mostly just me sleeping more.",
    "My brain processes emotions like a dial-up connection in a fiber optic world.",
    "I need a manual for 'how to adult' because I think I missed that chapter.",
    "**Mood today:** A gentle reminder that rest is productive too.",
    "If my thoughts were tweets, I'd be trending for all the wrong reasons.",
    "I've stopped trying to have it all together. Now I just aim for 'functional.'",
    "The older I get, the more I understand the appeal of staying in on a Friday night.",
    "**Real talk:** The little things are the big things. *Don't forget that.*",
    "My spirit animal is a half-wilted plant that somehow keeps surviving.",
    "I need to stop treating my bed like a crime scene I'm escaping from every morning.",
    "**Life update:** Still learning to be kind to myself. It's a process.",
    "My brain's default setting is 'what could go wrong?' *Very helpful, thanks.*",
    "I've mastered the art of looking like I know what I'm doing. *Spoiler: I don't.*",
    "The amount of energy it takes to be 'on' all day is exhausting. *I'm tired.*",
    "**Hot take:** Your 20s are just paid internship for figuring out life.",
    "I'm convinced that my anxiety is just my brain trying to protect me from myself.",
    "My journey is my own, and I'm learning to be okay with that. *Some days.*",
    "**Mood:** Trying to be a better version of myself, one small step at a time.",
    "I need to remember that I'm doing my best, and that's enough.",
]

COLORS = ['#FFD700', '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4',
          '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F', '#BB8FCE']


class Command(BaseCommand):
    help = 'Populate 200 QNotes with sample content'

    def add_arguments(self, parser):
        parser.add_argument('--count', type=int, default=200, help='Number of notes to create')

    def handle(self, *args, **options):
        count = options['count']
        User = get_user_model()
        users = list(User.objects.all())
        if not users:
            self.stderr.write(self.style.ERROR('No users found. Create a user first.'))
            return

        notes = []
        for i in range(count):
            content = random.choice(SAMPLE_NOTES)
            color = random.choice(COLORS)
            author = random.choice(users)
            notes.append(QNote(
                author=author,
                content=content,
                color=color,
            ))

        QNote.objects.bulk_create(notes, batch_size=100)
        self.stdout.write(self.style.SUCCESS(f'Created {count} QNotes successfully.'))
