# Generated by Django 5.2.15 on 2026-07-17 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QNotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QNoteCommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="qnote",
            new_name="QNotes_qnot_created_a83734_idx",
            old_name="qnotes_qnot_created_8d1954_idx",
        ),
        migrations.RenameIndex(
            model_name="qnote",
            new_name="QNotes_qnot_is_acti_062a61_idx",
            old_name="qnotes_qnot_is_acti_27d80e_idx",
        ),
        migrations.AddField(
            model_name="qnotecomment",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="qnotecommentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="QNotes.qnotecomment",
            ),
        ),
        migrations.AddField(
            model_name="qnotecommentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qnotecommentlike",
            unique_together={("comment", "user")},
        ),
    ]
