# Generated by Django 5.1.7 on 2026-02-03 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "provider",
                    models.CharField(
                        help_text="Institution offering this", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock Market"),
                            ("mmf", "Money Market Fund"),
                            ("bond", "Government/Corp Bond"),
                            ("lending", "P2P Lending"),
                            ("crypto", "Cryptocurrency"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "expected_return",
                    models.CharField(help_text="e.g. '12% p.a.'", max_length=100),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link to external platform or internal action",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Investment Opportunities",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("agri", "Agriculture"),
                            ("fin", "Finance"),
                            ("retail", "Retail"),
                            ("health", "Healthcare"),
                            ("educ", "Education"),
                            ("energy", "Energy"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_logos/"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea Phase"),
                            ("mvp", "MVP (Prototype)"),
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("growth", "Growth"),
                        ],
                        default="idea",
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="funding_docs/")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("license", "Business License"),
                            ("pitch_deck", "Pitch Deck"),
                            ("financials", "Financial Statements"),
                            ("legal", "Legal Contract"),
                            ("patent", "Patent/IP"),
                            ("kpi", "KPI Report"),
                            ("other", "Other Supporting Doc"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="Funding.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_needed", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "equity_offered",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage equity offered",
                        max_digits=5,
                    ),
                ),
                (
                    "use_of_funds",
                    models.TextField(help_text="How will the funds be used?"),
                ),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Funding"),
                            ("closing", "Closing Soon"),
                            ("funded", "Fully Funded"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_requests",
                        to="Funding.business",
                    ),
                ),
            ],
        ),
    ]
