# Generated by Django 5.1.7 on 2026-02-03 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalVenture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("institution_id", models.UUIDField(blank=True, null=True)),
                ("total_fund", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "available_fund",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "investment_criteria",
                    models.TextField(
                        help_text="What types of businesses this fund invests in"
                    ),
                ),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_investment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="charity_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fundraising goal",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="charity_raised",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount raised so far",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="is_charity",
            field=models.BooleanField(
                default=False, help_text="Is this a charity/non-profit?"
            ),
        ),
        migrations.AddField(
            model_name="fundingdocument",
            name="is_viewable",
            field=models.BooleanField(
                default=False, help_text="Only True if scan passed"
            ),
        ),
        migrations.AddField(
            model_name="fundingdocument",
            name="scan_result",
            field=models.JSONField(
                blank=True, help_text="Detailed scan results from APIs", null=True
            ),
        ),
        migrations.AddField(
            model_name="fundingdocument",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Scan"),
                    ("scanning", "Scanning"),
                    ("clean", "Clean"),
                    ("malware", "Malware Detected"),
                    ("nsfw_rejected", "NSFW Content Rejected"),
                    ("error", "Scan Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fundingdocument",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FundingNegotiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_founder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="Funding.fundingrequest",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_investor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("funding_request", "investor")},
            },
        ),
        migrations.CreateModel(
            name="FundingResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("offer", "Investment Offer"),
                            ("question", "Question"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "offer_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "equity_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="Funding.fundingrequest",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="negotiation_attachments/"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="Funding.fundingnegotiation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VentureBid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposed_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "proposed_equity",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("terms", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("negotiating", "In Negotiation"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venture_bids",
                        to="Funding.fundingrequest",
                    ),
                ),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="Funding.capitalventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("interested", "👀 Interested"),
                            ("promising", "🚀 Promising"),
                            ("caution", "⚠️ Caution"),
                            ("like", "👍 Like"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="Funding.fundingrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("funding_request", "user")},
            },
        ),
    ]
