# Generated by Django 5.1.7 on 2026-02-09 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0002_capitalventure_business_charity_goal_and_more"),
        ("Institution", "0005_institutionmember_title"),
        (
            "Organisation",
            "0004_remove_board_organistaion_remove_centre_organistaion_and_more",
        ),
        ("Rooms", "0005_alter_defaultroom_room_code_alter_room_organisation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capitalventure",
            name="institution_id",
        ),
        migrations.RemoveField(
            model_name="capitalventure",
            name="organization_id",
        ),
        migrations.AddField(
            model_name="capitalventure",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_ventures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capitalventure",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_ventures",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="capitalventure",
            name="investment_focus",
            field=models.CharField(
                blank=True,
                help_text="e.g. Tech, Agriculture, Healthcare",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="capitalventure",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="capitalventure",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_ventures",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="negotiation_room",
            field=models.ForeignKey(
                blank=True,
                help_text="Room for negotiations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funding_requests",
                to="Rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="target_venture",
            field=models.ForeignKey(
                blank=True,
                help_text="Target funding organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_requests",
                to="Funding.capitalventure",
            ),
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fundingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("due_diligence", "Due Diligence"),
                    ("negotiating", "Negotiating"),
                    ("approved", "Approved"),
                    ("funded", "Fully Funded"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FundingRequestReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Review notes or feedback"),
                ),
                (
                    "documents_requested",
                    models.TextField(
                        blank=True, help_text="Additional documents requested"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "documents_reviewed",
                    models.ManyToManyField(
                        blank=True, related_name="reviews", to="Funding.fundingdocument"
                    ),
                ),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Funding.fundingrequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funding.capitalventure",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
