# Generated by Django 5.2.11 on 2026-02-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0003_funding_org_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentopportunity",
            name="type",
            field=models.CharField(
                choices=[
                    ("stock", "Stock Market"),
                    ("mmf", "Money Market Fund"),
                    ("bond_domestic", "Domestic Bond"),
                    ("bond_foreign", "Foreign Bond"),
                    ("lending", "P2P Lending"),
                    ("crypto", "Cryptocurrency"),
                    ("agency", "Investment Agency"),
                ],
                max_length=50,
            ),
        ),
    ]
