# Generated by Django 5.2.11 on 2026-03-14 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0004_alter_investmentopportunity_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalventure",
            name="custom_investment_form",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom investment agreement terms. Leave blank to use the default template.",
            ),
        ),
        migrations.CreateModel(
            name="InvestmentAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kyc_data",
                    models.JSONField(
                        default=dict,
                        help_text="KYC data submitted during signing (name, id, nationality, etc.)",
                    ),
                ),
                ("digital_signature", models.CharField(max_length=500)),
                ("terms_version", models.CharField(default="v1", max_length=50)),
                (
                    "custom_terms_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the enterprise custom terms at time of signing",
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=True)),
                ("risk_acknowledged", models.BooleanField(default=True)),
                ("ethical_compliance", models.BooleanField(default=True)),
                ("aml_compliance", models.BooleanField(default=True)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_agreements",
                        to="Funding.capitalventure",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
                "indexes": [
                    models.Index(
                        fields=["investor", "venture"],
                        name="Funding_inv_investo_c87e8d_idx",
                    )
                ],
                "unique_together": {("investor", "venture")},
            },
        ),
    ]
