# Generated by Django 5.2.11 on 2026-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0006_investorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="has_portal_password",
            field=models.BooleanField(
                default=False, help_text="Has an independent portal account password"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="True if official documents are verified"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="portal_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
