# Generated by Django 5.2.11 on 2026-03-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0007_business_has_portal_password_business_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
