# Generated by Django 5.2.11 on 2026-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0008_business_city_business_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="primary_destination",
            field=models.CharField(default="kitty", max_length=50),
        ),
        migrations.AddField(
            model_name="business",
            name="primary_percentage",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name="business",
            name="secondary_destination",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="secondary_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
