# Generated by Django 5.2.11 on 2026-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0009_business_primary_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="industry",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("agri", "Agriculture"),
                    ("fin", "Finance"),
                    ("retail", "Retail"),
                    ("health", "Healthcare"),
                    ("educ", "Education"),
                    ("energy", "Energy"),
                    ("events", "Event Organizer"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
