# Generated by Django 5.2.11 on 2026-04-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0010_alter_business_industry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentopportunity",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Investment Opportunities",
            },
        ),
    ]
