# Generated by Django 5.2.11 on 2026-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0011_alter_investmentopportunity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentopportunity",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Verified by platform admins"
            ),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="verification_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="investment_opportunities",
                to="Funding.fundingdocument",
            ),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
