# Generated by Django 5.2.11 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0012_investmentopportunity_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentopportunity",
            name="gain_intervals",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("biannual", "Biannually"),
                    ("annual", "Annually"),
                    ("maturity", "At Maturity"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="group_benefit_summary",
            field=models.TextField(
                blank=True, help_text="Why invest as a group vs individual", null=True
            ),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="maturity_period",
            field=models.CharField(
                blank=True,
                help_text="e.g. '12 Months', 'Open-Ended'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="min_group_entry",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="min_individual_entry",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investmentopportunity",
            name="potential_gains",
            field=models.CharField(
                blank=True,
                help_text="Detailed potential gains breakdown",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investmentopportunity",
            name="min_investment",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Legacy field, use min_individual_entry",
                max_digits=12,
            ),
        ),
    ]
