# Generated by Django 5.2.11 on 2026-05-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0013_investmentopportunity_gain_intervals_and_more"),
        ("Payment", "0042_paymentgroups_is_kitty"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="payment_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="Payment.paymentgroups",
            ),
        ),
    ]
