# Generated by Django 5.2.11 on 2026-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0014_business_payment_group"),
        ("Payment", "0042_paymentgroups_is_kitty"),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalventure",
            name="payment_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventures",
                to="Payment.paymentgroups",
            ),
        ),
    ]
