# Generated by Django 5.2.11 on 2026-06-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funding", "0015_capitalventure_payment_group"),
        ("Payment", "0078_backfill_piggybankmembers"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentopportunity",
            name="provider_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investment_opportunities",
                to="Payment.providerregistration",
            ),
        ),
        migrations.AlterField(
            model_name="investmentopportunity",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Institution offering this (legacy — use provider_registration)",
                max_length=255,
            ),
        ),
    ]
