# Generated by Django 5.1.7 on 2026-01-26 09:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("user_type", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled by User"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_deletion_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedUserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_user_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("user_type", models.CharField(max_length=100)),
                ("user_data", models.JSONField()),
                ("activity_summary", models.JSONField(default=dict)),
                ("deletion_reason", models.TextField()),
                ("deletion_request_id", models.IntegerField(null=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Archived User Data",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="ComradeAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="InstAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="InstStaff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("staff_role", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("dob", models.DateField(default=datetime.datetime.now)),
                ("interests", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "lecturer_id",
                    models.CharField(
                        default="LCT",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("faculty", models.CharField(default="General", max_length=200)),
                ("department", models.CharField(default="General", max_length=200)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=300)),
                ("interests", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="OrgAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="OrgStaff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("staff_role", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("dob", models.DateField(default=datetime.datetime.now)),
                ("nationality", models.CharField(max_length=300)),
                ("country_of_residence", models.CharField(max_length=300)),
                ("interests", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoleChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_role", models.CharField(max_length=100)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator (Comrade)"),
                            ("staff", "Staff"),
                            ("lecturer", "Lecturer"),
                            ("student", "Student"),
                            ("normal_user", "Normal User"),
                            ("moderator", "Moderator"),
                            ("student_admin", "Student Admin"),
                            ("institutional_admin", "Institutional Admin"),
                            ("institutional_staff", "Institutional Staff"),
                            ("organisational_admin", "Organisational Admin"),
                            ("organisational_staff", "Organisational Staff"),
                            ("author", "Author"),
                            ("editor", "Editor"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Explain why you need this role change"),
                ),
                (
                    "supporting_documents",
                    models.FileField(blank=True, null=True, upload_to="role_requests/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "admission_number",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("year_of_admission", models.IntegerField(default=2000)),
                ("year_of_study", models.IntegerField(default=1)),
                ("current_semester", models.IntegerField(default=1)),
                ("institution", models.CharField(max_length=2000)),
                ("faculty", models.CharField(max_length=2000)),
                ("course", models.CharField(max_length=2000)),
                ("expecte_year_of_graduation", models.IntegerField(default=2000)),
                ("created_on", models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("interests", models.JSONField(blank=True, default=list)),
                (
                    "show_email",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers Only"),
                            ("private", "Private"),
                        ],
                        default="followers",
                        max_length=20,
                    ),
                ),
                (
                    "show_phone",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers Only"),
                            ("private", "Private"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "allow_messages",
                    models.CharField(
                        choices=[
                            ("anyone", "Anyone"),
                            ("followers", "Followers Only"),
                            ("none", "No One"),
                        ],
                        default="followers",
                        max_length=20,
                    ),
                ),
                ("show_activity_status", models.BooleanField(default=True)),
                ("show_read_receipts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                (
                    "other_names",
                    models.CharField(default="N/A", max_length=200, null=True),
                ),
                ("last_name", models.CharField(max_length=200)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator (Comrade)"),
                            ("staff", "Staff"),
                            ("lecturer", "Lecturer"),
                            ("student", "Student"),
                            ("normal_user", "Normal User"),
                            ("moderator", "Moderator"),
                            ("student_admin", "Student Admin"),
                            ("institutional_admin", "Institutional Admin"),
                            ("institutional_staff", "Institutional Staff"),
                            ("organisational_admin", "Organisational Admin"),
                            ("organisational_staff", "Organisational Staff"),
                            ("author", "Author"),
                            ("editor", "Editor"),
                        ],
                        default="student",
                        max_length=200,
                    ),
                ),
                ("phone_number", models.CharField(default="0123456789", max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_student_admin", models.BooleanField(default=False)),
                ("is_inst_admin", models.BooleanField(default=False)),
                ("is_inst_staff", models.BooleanField(default=False)),
                ("is_org_admin", models.BooleanField(default=False)),
                ("is_org_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_lecturer", models.BooleanField(default=False)),
                ("is_student", models.BooleanField(default=True)),
                ("is_moderator", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_author", models.BooleanField(default=False)),
                ("is_editor", models.BooleanField(default=False)),
                ("is_normal_user", models.BooleanField(default=False)),
                ("profile_completed", models.BooleanField(default=False)),
                ("totp_enabled", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=32, null=True)),
                ("totp_verified", models.BooleanField(default=False)),
                ("totp_backup_codes", models.TextField(blank=True, null=True)),
                ("login_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("login_otp_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "password_reset_otp_secret",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "password_reset_otp_expires",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sms_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("sms_otp_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_otp",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "registration_otp_expires",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("pending_deletion", "Pending Deletion"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("deletion_reason", models.TextField(blank=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
