# Generated by Django 5.1.7 on 2025-11-02 12:14

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "admission_number",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("year_of_admission", models.IntegerField(default=1)),
                ("year_of_study", models.IntegerField(default=1)),
                ("current_semester", models.IntegerField(default=1)),
                ("faculty", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OrgStaff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("staff_role", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("dob", models.DateField()),
                ("nationality", models.CharField(max_length=300)),
                ("country_of_residence", models.CharField(max_length=300)),
                ("interests", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "current_inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_inst_branch_staff",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "current_institution",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_inst_staff",
                        to="Institution.institution",
                    ),
                ),
                (
                    "current_org_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_branch_staff",
                        to="Organisation.orgbranch",
                    ),
                ),
                (
                    "current_organisation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_staff",
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "previous_inst_branch",
                    models.ManyToManyField(
                        related_name="previous_inst_branch_staff",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "previous_institutions",
                    models.ManyToManyField(
                        related_name="previous_inst_staff", to="Institution.institution"
                    ),
                ),
                (
                    "previous_org_branch",
                    models.ManyToManyField(
                        related_name="previous_branch_staff",
                        to="Organisation.orgbranch",
                    ),
                ),
                (
                    "previous_organisations",
                    models.ManyToManyField(
                        related_name="previous_staff", to="Organisation.organisation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.orgstaff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                (
                    "middle_name",
                    models.CharField(default="N/A", max_length=200, null=True),
                ),
                ("last_name", models.CharField(max_length=200)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator (Comrade)"),
                            ("staff", "Staff"),
                            ("lecturer", "Lecturer"),
                            ("student", "Student"),
                            ("student_admin", "Student Admin"),
                            ("institutional_admin", "Institutional Admin"),
                            ("institutional_staff", "Institutional Staff"),
                            ("organisational_admin", "Organisational Admin"),
                            ("organisational_staff", "Organisational Staff"),
                        ],
                        default="student",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
