# Generated by Django 5.1.1 on 2025-02-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=100, unique=True)),
                ('year_of_admission', models.IntegerField()),
                ('faculty', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
