# Generated by Django 5.1.6 on 2025-07-01 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.student')),
            ],
        ),
    ]
