# Generated by Django 5.1.7 on 2025-11-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
