# Generated by Django 5.1.7 on 2026-01-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0001_initial"),
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inststaff",
            name="inst_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Institution.instbranch"
            ),
        ),
        migrations.AddField(
            model_name="inststaff",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="inststaff",
            name="previous_inst_branch",
            field=models.ManyToManyField(
                related_name="previous_inst_branch_admins", to="Institution.instbranch"
            ),
        ),
        migrations.AddField(
            model_name="inststaff",
            name="previous_institutions",
            field=models.ManyToManyField(
                related_name="previous_inst_admins", to="Institution.institution"
            ),
        ),
        migrations.AddField(
            model_name="instadmin",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.inststaff",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="current_inst_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_branch_staff",
                to="Institution.instbranch",
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="current_institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_staff",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="current_org_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_branch_staff",
                to="Organisation.orgbranch",
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="current_organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_staff",
                to="Organisation.organisation",
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="previous_inst_branch",
            field=models.ManyToManyField(
                related_name="previous_inst_branch_staff", to="Institution.instbranch"
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="previous_institutions",
            field=models.ManyToManyField(
                related_name="previous_inst_staff", to="Institution.institution"
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="previous_org_branch",
            field=models.ManyToManyField(
                related_name="previous_branch_staff", to="Organisation.orgbranch"
            ),
        ),
        migrations.AddField(
            model_name="orgstaff",
            name="previous_organisations",
            field=models.ManyToManyField(
                related_name="previous_staff", to="Organisation.organisation"
            ),
        ),
        migrations.AddField(
            model_name="orgadmin",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.orgstaff",
            ),
        ),
    ]
