# Generated by Django 5.1.7 on 2026-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0002_initial"),
        ("Events", "0001_initial"),
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked_events",
            field=models.ManyToManyField(
                blank=True, related_name="events_blocked_by", to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_institutions",
            field=models.ManyToManyField(
                blank=True,
                related_name="insts_blocked_by",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="orgs_blocked_by",
                to="Organisation.organisation",
            ),
        ),
    ]
