# Generated by Django 5.1.7 on 2025-11-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_alter_customuser_managers"),
        ("Institution", "0002_cafeteria_counselling_hostel_library_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstStaff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("staff_role", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("dob", models.DateField()),
                ("interests", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "previous_inst_branch",
                    models.ManyToManyField(
                        related_name="previous_inst_branch_admins",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "previous_institutions",
                    models.ManyToManyField(
                        related_name="previous_inst_admins",
                        to="Institution.institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.studentadmin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.inststaff",
                    ),
                ),
            ],
        ),
    ]
