# Generated by Django 5.1.7 on 2025-11-07 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_inststaff_instadmin"),
        ("Institution", "0002_cafeteria_counselling_hostel_library_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_inst_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_inst_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_lecturer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_org_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_org_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_student_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="department",
            field=models.CharField(default="General", max_length=200),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="faculty",
            field=models.CharField(default="General", max_length=200),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="institution",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(
                default="LCT",
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator (Comrade)"),
                    ("staff", "Staff"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("moderator", "Moderator"),
                    ("student_admin", "Student Admin"),
                    ("institutional_admin", "Institutional Admin"),
                    ("institutional_staff", "Institutional Staff"),
                    ("organisational_admin", "Organisational Admin"),
                    ("organisational_staff", "Organisational Staff"),
                ],
                default="student",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
