# Generated by Django 5.1.7 on 2026-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="registration_otp_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
