# Generated by Django 5.2.11 on 2026-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
