# Generated by Django 5.1.7 on 2025-11-17 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_moderator"),
        ("Events", "0017_event_deadline_reached_alter_event_booking_deadline_and_more"),
        ("Institution", "0002_cafeteria_counselling_hostel_library_and_more"),
        ("Organisation", "0002_rename_created_at_organisation_created_on_and_more"),
        ("Rooms", "0018_alter_defaultroom_room_code_alter_room_room_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "blocked_events",
                    models.ManyToManyField(
                        blank=True, related_name="events_blocked_by", to="Events.event"
                    ),
                ),
                (
                    "blocked_institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="insts_blocked_by",
                        to="Institution.institution",
                    ),
                ),
                (
                    "blocked_organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="orgs_blocked_by",
                        to="Organisation.organisation",
                    ),
                ),
                (
                    "blocked_rooms",
                    models.ManyToManyField(
                        blank=True, related_name="rooms_blocked_by", to="Rooms.room"
                    ),
                ),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
