# Generated by Django 5.2.11 on 2026-02-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_customuser_is_online_customuser_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator (Comrade)"),
                    ("staff", "Staff"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("normal_user", "Normal User"),
                    ("moderator", "Moderator"),
                    ("student_admin", "Student Admin"),
                    ("institutional_admin", "Institutional Admin"),
                    ("institutional_staff", "Institutional Staff"),
                    ("organisational_admin", "Organisational Admin"),
                    ("organisational_staff", "Organisational Staff"),
                    ("author", "Author"),
                    ("editor", "Editor"),
                    ("creator", "Creator"),
                ],
                default="student",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="rolechangerequest",
            name="requested_role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator (Comrade)"),
                    ("staff", "Staff"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("normal_user", "Normal User"),
                    ("moderator", "Moderator"),
                    ("student_admin", "Student Admin"),
                    ("institutional_admin", "Institutional Admin"),
                    ("institutional_staff", "Institutional Staff"),
                    ("organisational_admin", "Organisational Admin"),
                    ("organisational_staff", "Organisational Staff"),
                    ("author", "Author"),
                    ("editor", "Editor"),
                    ("creator", "Creator"),
                ],
                max_length=100,
            ),
        ),
    ]
