# Generated by Django 5.1.7 on 2026-01-15 14:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_customuser_registration_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_normal_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator (Comrade)"),
                    ("staff", "Staff"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("normal_user", "Normal User"),
                    ("moderator", "Moderator"),
                    ("student_admin", "Student Admin"),
                    ("institutional_admin", "Institutional Admin"),
                    ("institutional_staff", "Institutional Staff"),
                    ("organisational_admin", "Organisational Admin"),
                    ("organisational_staff", "Organisational Staff"),
                    ("author", "Author"),
                    ("editor", "Editor"),
                ],
                default="student",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=300)),
                ("interests", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_role", models.CharField(max_length=100)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator (Comrade)"),
                            ("staff", "Staff"),
                            ("lecturer", "Lecturer"),
                            ("student", "Student"),
                            ("normal_user", "Normal User"),
                            ("moderator", "Moderator"),
                            ("student_admin", "Student Admin"),
                            ("institutional_admin", "Institutional Admin"),
                            ("institutional_staff", "Institutional Staff"),
                            ("organisational_admin", "Organisational Admin"),
                            ("organisational_staff", "Organisational Staff"),
                            ("author", "Author"),
                            ("editor", "Editor"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Explain why you need this role change"),
                ),
                (
                    "supporting_documents",
                    models.FileField(blank=True, null=True, upload_to="role_requests/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_role_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
