# Generated by Django 5.1.7 on 2026-01-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_customuser_registration_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_otp_expires',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_otp_expires',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_backup_codes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_verified',
        ),
    ]
