# Generated by Django 5.1.7 on 2026-01-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_customuser_is_normal_user_and_more'),
        ('Authentication', '0006_remove_customuser_registration_otp_and_more'),
    ]

    operations = [
    ]
