# Generated by Django 5.1.7 on 2025-11-20 17:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 861391)
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator (Comrade)"),
                    ("staff", "Staff"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("moderator", "Moderator"),
                    ("student_admin", "Student Admin"),
                    ("institutional_admin", "Institutional Admin"),
                    ("institutional_staff", "Institutional Staff"),
                    ("organisational_admin", "Organisational Admin"),
                    ("organisational_staff", "Organisational Staff"),
                    ("author", "Author"),
                    ("editor", "Editor"),
                ],
                default="student",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Authentication.profile"
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 20, 20, 21, 12, 860217)
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 20, 20, 21, 12, 860653)
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
    ]
