# Generated by Django 5.2.11 on 2026-02-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0007_alter_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
