# Generated by Django 5.1.7 on 2025-11-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0007_moderator_created_on_moderator_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 36, 37, 179851)
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 36, 37, 180303)
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 36, 37, 180753)
            ),
        ),
    ]
