# Generated by Django 5.2.11 on 2026-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0008_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_researcher",
            field=models.BooleanField(default=False),
        ),
    ]
