# Generated by Django 5.2.11 on 2026-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0009_customuser_is_researcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hobbies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="religion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_experience",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
