# Generated by Django 5.1.7 on 2025-11-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0009_alter_author_created_on_alter_editor_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 435235)
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 435655)
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 436077)
            ),
        ),
    ]
