# Generated by Django 5.2.11 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0010_userprofile_certifications_userprofile_hobbies_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="Authenticat_usernam_8294a1_idx"
            ),
        ),
    ]
