# Generated by Django 5.1.7 on 2025-11-21 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0010_alter_author_created_on_alter_editor_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 996481)
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 996894)
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 13, 997288)
            ),
        ),
    ]
