# Generated by Django 5.1.7 on 2025-11-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0011_alter_author_created_on_alter_editor_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="editor",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="dob",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="dob",
            field=models.DateField(auto_now_add=True),
        ),
    ]
