# Generated by Django 5.2.11 on 2026-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0011_customuser_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
