# Generated by Django 5.1.7 on 2025-11-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0012_alter_author_created_on_alter_editor_created_on_and_more",
        ),
        ("Institution", "0004_alter_admindep_created_at_and_more"),
        (
            "Organisation",
            "0008_alter_board_created_on_alter_centre_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Authentication.profile"
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Authentication.profile"
            ),
        ),
        migrations.AlterField(
            model_name="instadmin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.inststaff",
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="inst_branch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Institution.instbranch"
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="institution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="institution",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="orgadmin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.orgstaff",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_inst_branch",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_branch_staff",
                to="Institution.instbranch",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_institution",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_staff",
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_org_branch",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_branch_staff",
                to="Organisation.orgbranch",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_organisation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_staff",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="studentadmin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Authentication.student"
            ),
        ),
    ]
