# Generated by Django 5.2.11 on 2026-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0012_customuser_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_group_invites",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone"),
                    ("followers", "Followers Only"),
                    ("none", "No One"),
                ],
                default="followers",
                max_length=20,
            ),
        ),
    ]
