# Generated by Django 5.2.11 on 2026-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0013_userprofile_allow_group_invites"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country_code",
            field=models.CharField(
                blank=True, help_text="ISO 3166-1 alpha-2 country code", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_currency",
            field=models.CharField(
                blank=True, help_text="User's preferred display currency", max_length=3
            ),
        ),
    ]
