# Generated by Django 5.1.7 on 2025-11-22 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0013_alter_author_user_alter_editor_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instadmin",
            name="created_by",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="instadmin",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="orgadmin",
            name="created_by",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="orgadmin",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="studentadmin",
            name="created_by",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="studentadmin",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="dob",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="dob",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
