# Generated by Django 5.1.7 on 2025-11-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0014_instadmin_created_by_instadmin_created_on_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="middle_name",
            new_name="other_names",
        ),
    ]
