# Generated by Django 5.2.11 on 2026-06-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0014_profile_country_code_profile_preferred_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country_of_origin",
            field=models.CharField(
                blank=True, help_text="ISO 3166-1 alpha-2 country code", max_length=2
            ),
        ),
    ]
