# Generated by Django 5.2.11 on 2026-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0015_customuser_country_of_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_sponsor",
            field=models.BooleanField(default=False),
        ),
    ]
