# Generated by Django 5.1.7 on 2025-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0015_rename_middle_name_customuser_other_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default="0123456789", max_length=15),
        ),
    ]
