# Generated by Django 5.1.7 on 2025-11-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0016_remove_lecturer_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
    ]
