# Generated by Django 5.1.7 on 2025-11-23 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0017_remove_student_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created_on",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="student",
            name="expecte_year_of_graduation",
            field=models.IntegerField(default=2000, max_length=4),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_semester",
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="student",
            name="institution",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_admission",
            field=models.IntegerField(default=2000, max_length=4),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_study",
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
