# Generated by Django 5.1.7 on 2025-11-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0018_student_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_semester",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="expecte_year_of_graduation",
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_admission",
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_study",
            field=models.IntegerField(default=1),
        ),
    ]
