# Generated by Django 5.1.7 on 2025-11-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0020_comradeadmin"),
        ("Institution", "0004_alter_admindep_created_at_and_more"),
        (
            "Organisation",
            "0008_alter_board_created_on_alter_centre_created_on_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="instadmin",
            old_name="user",
            new_name="staff",
        ),
        migrations.RenameField(
            model_name="orgadmin",
            old_name="user",
            new_name="staff",
        ),
        migrations.RenameField(
            model_name="studentadmin",
            old_name="user",
            new_name="student",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_author",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_editor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="instadmin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="inst_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Institution.instbranch"
            ),
        ),
        migrations.AlterField(
            model_name="inststaff",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="orgadmin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_inst_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_branch_staff",
                to="Institution.instbranch",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_inst_staff",
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_org_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_branch_staff",
                to="Organisation.orgbranch",
            ),
        ),
        migrations.AlterField(
            model_name="orgstaff",
            name="current_organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_staff",
                to="Organisation.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="studentadmin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
