# Generated by Django 5.1.7 on 2026-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0022_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="login_otp_secret",
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
