# Generated by Django 5.2.11 on 2026-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeviceManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="Firebase Cloud Messaging token for push notifications",
                max_length=255,
                null=True,
            ),
        ),
    ]
