# Generated by Django 5.1.6 on 2025-07-01 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_student_current_semester_student_year_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 10, 50, 21, 403657))),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('not_sent', 'Not Sent')], default='pending', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.studentadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('not_sent', 'Not Sent')], default='pending', max_length=200)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 10, 50, 21, 388036))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('not_sent', 'Not Sent')], default='pending', max_length=200)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 10, 50, 21, 403657))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.student')),
                ('reference_text', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Announcements.text')),
            ],
        ),
    ]
