# Generated by Django 5.1.7 on 2026-01-07 09:06

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnouncementPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                ("schedule_time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "expiry_time",
                    models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("read_status", models.BooleanField(default=False)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Disqualified"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                (
                    "verification_time_stamp",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_enabled", models.BooleanField(default=True)),
                (
                    "notification_period",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("custom", "Custom Period"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("custom_period_hours", models.IntegerField(blank=True, null=True)),
                ("notify_in_app", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_push", models.BooleanField(default=True)),
                ("offline_notification", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("last_notification_sent", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                ("is_correct", models.BooleanField(default=False)),
                ("selected", models.BooleanField(default=False)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=5000)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=1)),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("content", models.FileField(upload_to="task_files/")),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="OfflineAnnouncementNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new", "New Announcement"),
                            ("update", "Announcement Updated"),
                            ("reminder", "Announcement Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("queued", models.BooleanField(default=True)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_push", models.BooleanField(default=False)),
                ("sent_via_app", models.BooleanField(default=False)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("scheduled_for", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("position", models.IntegerField(default=1)),
                ("description", models.TextField(max_length=5000)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("radio", "Single Choice Answers"),
                            ("check", "Multiple Choice Answers"),
                            ("text", "Text Answers"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=200,
                    ),
                ),
                ("has_subquestion", models.BooleanField(default=False)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(max_length=5000)),
                ("answer_file", models.FileField(upload_to="task_answers/")),
                ("score", models.FloatField(default=0.0)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reaction_type", models.CharField(max_length=100)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Reposts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(default="", max_length=5000)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="reposts/images"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="reposts/videos"),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAnnouncementConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("source_type", models.CharField(max_length=50)),
                ("source_title", models.CharField(max_length=300)),
                ("retain_source", models.BooleanField(default=True)),
                ("original_content", models.JSONField(default=dict)),
                ("converted_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("position", models.IntegerField(default=1)),
                ("description", models.TextField(max_length=5000)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("radio", "Single Choice Answers"),
                            ("check", "Multiple Choice Answers"),
                            ("text", "Text Answers"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=200,
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=5000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("full", "Full"),
                            ("unavailable", "Unavalible"),
                        ],
                        default="active",
                        max_length=200,
                    ),
                ),
                ("due_date", models.DateTimeField(default=datetime.datetime.now)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="TaskResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField(default=0.0)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
