# Generated by Django 5.1.7 on 2025-11-02 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 2, 15, 14, 42, 526060)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Disqualified"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 2, 15, 14, 42, 526904)
                    ),
                ),
                (
                    "verification_time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 2, 15, 14, 42, 526929)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 2, 15, 14, 42, 525364)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 2, 15, 14, 42, 524594)
                    ),
                ),
            ],
        ),
    ]
