# Generated by Django 5.1.7 on 2025-11-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Announcements", "0001_initial"),
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.studentadmin",
            ),
        ),
        migrations.AddField(
            model_name="announcementsrequest",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.student",
            ),
        ),
        migrations.AddField(
            model_name="announcementsrequest",
            name="verified_by",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.studentadmin",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.student",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.student",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="reference_text",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.text"
            ),
        ),
    ]
