# Generated by Django 5.1.7 on 2025-11-04 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0002_initial"),
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=5000)),
                ("is_correct", models.BooleanField(default=False)),
                ("selected", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="announcements",
            old_name="status",
            new_name="send_status",
        ),
        migrations.AddField(
            model_name="announcements",
            name="expiry_time",
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AddField(
            model_name="announcements",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcements",
            name="read_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 99595)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 99638)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 101074)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 101124)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 98912)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 4, 12, 51, 5, 98257)
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 4, 12, 51, 5, 102310)
                    ),
                ),
                (
                    "answers_type",
                    models.CharField(
                        choices=[
                            ("radio", "Single Choice Answers"),
                            ("check", "Multiple Choice Answers"),
                            ("text", "Text Answers"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=200,
                    ),
                ),
                (
                    "answer_file",
                    models.FileField(blank=True, null=True, upload_to="task_answers/"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="private",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 4, 12, 51, 5, 102478)
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "completed_on",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 4, 12, 51, 5, 102507)
                    ),
                ),
                (
                    "answer_text",
                    models.ManyToManyField(blank=True, to="Announcements.choice"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.studentadmin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reposts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(default="", max_length=5000)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="reposts/images"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="reposts/videos"),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 4, 12, 51, 5, 104048)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "announcement",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.student",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 4, 12, 51, 5, 104782)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("not_sent", "Not Sent"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                (
                    "announcement",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.student",
                    ),
                ),
                (
                    "repost",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.reposts",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.task",
                    ),
                ),
            ],
        ),
    ]
