# Generated by Django 5.1.7 on 2025-11-04 21:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Announcements",
            "0003_choice_rename_status_announcements_send_status_and_more",
        ),
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="content",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="answer_file",
        ),
        migrations.RemoveField(
            model_name="task",
            name="answer_text",
        ),
        migrations.RemoveField(
            model_name="task",
            name="answers_type",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_on",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 226852)
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("full", "Full"),
                    ("unavailable", "Unavalible"),
                ],
                default="active",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 222656)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 222806)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 223954)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 223880)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 231427)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 229352)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 230311)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 225065)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 225097)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 0, 5, 49, 228474)
            ),
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "completed_on",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 5, 0, 5, 49, 232528)
                    ),
                ),
                (
                    "tasks",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.task",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=5000)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("radio", "Single Choice Answers"),
                            ("check", "Multiple Choice Answers"),
                            ("text", "Text Answers"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 5, 0, 5, 49, 226024)
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("content", models.FileField(upload_to="task_files/")),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 5, 0, 5, 49, 227656)
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.question",
            ),
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(max_length=5000)),
                ("answer_file", models.FileField(upload_to="task_answers/")),
                ("score", models.FloatField(default=0.0)),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 5, 0, 5, 49, 233516)
                    ),
                ),
                (
                    "answer_choice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.choice",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.question",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.task",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentication.student",
                    ),
                ),
            ],
        ),
    ]
