# Generated by Django 5.1.7 on 2025-11-05 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0004_rename_content_task_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completedtask",
            old_name="tasks",
            new_name="task",
        ),
        migrations.AddField(
            model_name="question",
            name="has_subquestion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 470029)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 470134)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 470955)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 470911)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 473306)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 476711)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 473774)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 476086)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 472253)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 477286)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 474748)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 475420)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 471623)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 471641)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 8, 44, 41, 474238)
            ),
        ),
        migrations.CreateModel(
            name="SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=5000)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("radio", "Single Choice Answers"),
                            ("check", "Multiple Choice Answers"),
                            ("text", "Text Answers"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=200,
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 5, 8, 44, 41, 472787)
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Announcements.question",
                    ),
                ),
            ],
        ),
    ]
