# Generated by Django 5.2.11 on 2026-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Announcements",
            "0004_announcements_institution_announcements_organisation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="highlight_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
