# Generated by Django 5.1.7 on 2025-11-05 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0005_rename_tasks_completedtask_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 750229)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 750361)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 751285)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 751232)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 754449)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 759401)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 755143)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 758498)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 752918)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 760263)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 756576)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 757421)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 753728)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 752143)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 752166)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 5, 11, 54, 51, 755834)
            ),
        ),
    ]
