# Generated by Django 5.2.11 on 2026-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0005_announcements_views_comment_highlight_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("exam", "Exam"),
                    ("test", "Test"),
                    ("survey", "Survey"),
                    ("questionnaire", "Questionnaire"),
                    ("scheduling", "Scheduling"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("none", "Not Applicable"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
