# Generated by Django 5.2.11 on 2026-03-05 06:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0006_add_task_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timer_enabled", models.BooleanField(default=False)),
                ("timer_duration", models.DurationField(blank=True, null=True)),
                ("no_tab_leaving", models.BooleanField(default=False)),
                ("auto_submit_on_tab_change", models.BooleanField(default=False)),
                ("max_tab_switches", models.IntegerField(default=3)),
                ("auto_save", models.BooleanField(default=True)),
                ("one_take", models.BooleanField(default=False)),
                ("max_attempts", models.IntegerField(default=1)),
                ("record_video", models.BooleanField(default=False)),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("show_results_immediately", models.BooleanField(default=True)),
                ("questions_per_page", models.IntegerField(default=4)),
                ("passing_score", models.FloatField(default=0.0)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="Announcements.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("access", "Page Access"),
                            ("read", "Read/View"),
                            ("share", "Shared"),
                            ("react", "Reacted"),
                            ("start", "Started Task"),
                            ("submit", "Submitted"),
                            ("save_draft", "Saved Draft"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="Announcements.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "action"], name="Announcemen_task_id_0b9ffe_idx"
                    ),
                    models.Index(
                        fields=["task", "-created_at"],
                        name="Announcemen_task_id_38005f_idx",
                    ),
                ],
            },
        ),
    ]
