# Generated by Django 5.2.11 on 2026-03-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0007_tasksettings_taskanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("radio", "Single Choice Answers"),
                    ("check", "Multiple Choice Answers"),
                    ("short_text", "Short Text Answer"),
                    ("text", "Paragraph Text Answer"),
                    ("file", "Single File Upload"),
                    ("multiple_file", "Multiple File Upload"),
                ],
                default="text",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="answer_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.choice",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="answer_file",
            field=models.FileField(blank=True, null=True, upload_to="task_answers/"),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("radio", "Single Choice Answers"),
                    ("check", "Multiple Choice Answers"),
                    ("short_text", "Short Text Answer"),
                    ("text", "Paragraph Text Answer"),
                    ("file", "Single File Upload"),
                    ("multiple_file", "Multiple File Upload"),
                ],
                default="text",
                max_length=200,
            ),
        ),
    ]
