# Generated by Django 5.2.11 on 2026-03-05 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0008_alter_question_question_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="tasksettings",
            name="accept_late_submissions",
            field=models.BooleanField(default=False),
        ),
    ]
