# Generated by Django 5.2.11 on 2026-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0009_task_is_activity_task_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
