# Generated by Django 5.2.11 on 2026-03-08 07:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0010_task_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresponse",
            name="feedback",
            field=models.TextField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("under_review", "Under Review"),
                    ("complete", "Complete"),
                    ("confirmed", "Confirmed"),
                    ("graded", "Graded"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TaskGradingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_grade", models.BooleanField(default=False)),
                ("scheduled_grade_at", models.DateTimeField(blank=True, null=True)),
                ("grade_immediately", models.BooleanField(default=True)),
                ("max_score", models.FloatField(default=100.0)),
                ("grading_criteria", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_config",
                        to="Announcements.task",
                    ),
                ),
            ],
        ),
    ]
