# Generated by Django 5.1.7 on 2025-11-07 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0010_alter_announcements_schedule_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 521307)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 521414)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 522057)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 522017)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 525509)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 528914)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 525965)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 528119)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 524346)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 529491)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 526911)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 527493)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 524855)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 523420)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 523469)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 8, 2, 56, 15, 526422)
            ),
        ),
    ]
