# Generated by Django 5.2.11 on 2026-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0011_taskresponse_feedback_taskresponse_graded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer_text",
            field=models.TextField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="task",
            name="is_gradable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskgradingconfig",
            name="ai_grading_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskgradingconfig",
            name="score_release_mode",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediately after submission"),
                    ("on_due_date", "When due date passes"),
                    ("manual", "Manually by creator"),
                ],
                default="immediate",
                max_length=20,
            ),
        ),
    ]
