# Generated by Django 5.1.7 on 2025-11-09 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0012_alter_announcements_schedule_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 405468)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 405589)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 406355)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 406304)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 408947)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 412530)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 409458)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 411863)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 407694)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 413352)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 410534)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 411156)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 408249)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 407070)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 407090)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 5, 12, 410001)
            ),
        ),
    ]
