# Generated by Django 5.2.11 on 2026-03-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0013_comment_dislikes_comment_likes_comment_parent"),
        ("Research", "0008_researchproject_is_paid_researchproject_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="research_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_tasks",
                to="Research.researchproject",
            ),
        ),
    ]
