# Generated by Django 5.1.7 on 2025-11-09 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0013_alter_announcements_schedule_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 906084)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 906287)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 907548)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 907460)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 911690)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 918107)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 912481)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 916992)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 909940)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 923667)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 914160)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 915336)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 910861)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 908684)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 908715)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 9, 10, 7, 27, 913296)
            ),
        ),
    ]
