# Generated by Django 5.1.7 on 2025-11-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0018_fileresponse_position_and_more"),
        ("Events", "0013_alter_event_booking_deadline_alter_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pin",
            name="announcement",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="repost",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="task",
        ),
        migrations.AddField(
            model_name="pin",
            name="announcements",
            field=models.ManyToManyField(
                blank=True,
                related_name="pinned_announcements",
                to="Announcements.announcements",
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_events", to="Events.event"
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="reposts",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_reposts", to="Announcements.reposts"
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_tasks", to="Announcements.task"
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 829372)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 829479)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 830176)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 830136)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 832426)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 838149)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 832971)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 835140)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 831367)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 838755)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 833967)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 834518)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 831919)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 830806)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 830823)
            ),
        ),
        migrations.AlterField(
            model_name="taskresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 839406)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 14, 52, 16, 833470)
            ),
        ),
    ]
