# Generated by Django 5.1.7 on 2025-11-20 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0028_alter_announcements_schedule_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 741057)
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 741320)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 743721)
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verification_time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 743547)
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 749516)
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 770816)
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="completed_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 763127)
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 750740)
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 755640)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 746827)
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 764461)
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 768907)
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 752957)
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 754265)
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 748193)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 745516)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 745555)
            ),
        ),
        migrations.AlterField(
            model_name="taskresponse",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 765997)
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 751807)
            ),
        ),
    ]
