# Generated by Django 5.1.7 on 2025-11-28 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0032_alter_announcements_schedule_time_and_more"),
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        ("Events", "0032_event_activate_feedback_event_attendees_viewable_and_more"),
        ("Rooms", "0058_alter_defaultroom_room_code_alter_room_room_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="completedtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="reference_reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.reply",
            ),
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="send_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.student",
            ),
        ),
        migrations.AlterField(
            model_name="announcementsrequest",
            name="verified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.question",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="sub_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.subquestion",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.announcements",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="dm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Rooms.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.task",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.text",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.task"
            ),
        ),
        migrations.AlterField(
            model_name="completedtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.question",
            ),
        ),
        migrations.AlterField(
            model_name="fileresponse",
            name="sub_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.subquestion",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.task"
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="answer_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.choice",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="sub_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.subquestion",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.task"
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.announcements",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="dm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Rooms.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.task",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.text",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="reference_text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.text"
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentication.student",
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.announcements",
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.event",
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Announcements.task",
            ),
        ),
        migrations.AlterField(
            model_name="reposts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskresponse",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Announcements.task"
            ),
        ),
        migrations.AlterField(
            model_name="taskresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("not_sent", "Not Sent"),
                    ("draft", "Draft"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
