# Generated by Django 5.1.7 on 2026-01-03 12:52

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0033_comment_status_completedtask_status_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_enabled", models.BooleanField(default=True)),
                (
                    "notification_period",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("custom", "Custom Period"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("custom_period_hours", models.IntegerField(blank=True, null=True)),
                ("notify_in_app", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_push", models.BooleanField(default=True)),
                ("offline_notification", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("last_notification_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineAnnouncementNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new", "New Announcement"),
                            ("update", "Announcement Updated"),
                            ("reminder", "Announcement Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("queued", models.BooleanField(default=True)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_push", models.BooleanField(default=False)),
                ("sent_via_app", models.BooleanField(default=False)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("scheduled_for", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Announcements.announcementsubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAnnouncementConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("source_type", models.CharField(max_length=50)),
                ("source_title", models.CharField(max_length=300)),
                ("retain_source", models.BooleanField(default=True)),
                ("original_content", models.JSONField(default=dict)),
                ("converted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="Announcements.announcements",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_announcement_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("announcement", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="announcementsubscription",
            index=models.Index(
                fields=["user", "notification_enabled"],
                name="Announcemen_user_id_0979c1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementsubscription",
            unique_together={("user", "announcement")},
        ),
        migrations.AddIndex(
            model_name="offlineannouncementnotification",
            index=models.Index(
                fields=["queued", "scheduled_for"], name="Announcemen_queued_9f2c96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlineannouncementnotification",
            index=models.Index(
                fields=["user", "-created_at"], name="Announcemen_user_id_a1b39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceannouncementconversion",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="Announcemen_content_56df1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceannouncementconversion",
            index=models.Index(
                fields=["source_type", "-converted_at"],
                name="Announcemen_source__bbc60b_idx",
            ),
        ),
    ]
