# Generated by Django 5.1.7 on 2026-01-02 11:30

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "min_education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor Degree"),
                            ("master", "Master Degree"),
                            ("doctoral", "Doctoral Degree"),
                            ("any", "Any"),
                        ],
                        max_length=100,
                    ),
                ),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("required_experience", models.TextField(blank=True)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("location_requirements", models.TextField(blank=True)),
                ("language_requirements", models.JSONField(blank=True, default=list)),
                ("timezone_requirements", models.CharField(blank=True, max_length=100)),
                ("equipment_required", models.JSONField(blank=True, default=list)),
                ("software_required", models.JSONField(blank=True, default=list)),
                ("internet_speed", models.CharField(blank=True, max_length=100)),
                ("min_hours_per_week", models.FloatField(blank=True, null=True)),
                ("total_estimated_hours", models.FloatField(blank=True, null=True)),
                ("custom_criteria", models.JSONField(blank=True, default=dict)),
                ("target_participant_count", models.IntegerField(default=50)),
                ("min_participant_count", models.IntegerField(default=30)),
                ("max_participant_count", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "compensation_type",
                    models.CharField(
                        choices=[
                            ("none", "No Compensation"),
                            ("monetary", "Monetary"),
                            ("course_credit", "Course Credit"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "compensation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "compensation_currency",
                    models.CharField(default="USD", max_length=3),
                ),
                ("compensation_description", models.TextField(blank=True)),
                ("application_deadline", models.DateTimeField()),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_duration_hours",
                    models.FloatField(help_text="Estimated time commitment in hours"),
                ),
                ("estimated_duration_weeks", models.IntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                ("slots_available", models.IntegerField(default=10)),
                ("slots_filled", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirements",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Research.participantrequirements",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("seeking_participants", "Seeking Participants"),
                            ("in_progress", "In Progress"),
                            ("data_collection", "Data Collection"),
                            ("analysis", "Analysis"),
                            ("peer_review", "Peer Review"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ethics_approved", models.BooleanField(default=False)),
                (
                    "ethics_approval_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "consent_form",
                    models.FileField(
                        blank=True, null=True, upload_to="research/consent_forms/"
                    ),
                ),
                (
                    "irb_approval_document",
                    models.FileField(blank=True, null=True, upload_to="research/irb/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=200)),
                ("views", models.IntegerField(default=0)),
                (
                    "co_investigators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_research",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_research",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="invited",
                        max_length=50,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(blank=True, null=True)),
                ("consent_signature", models.CharField(blank=True, max_length=500)),
                ("joined_at", models.DateTimeField(default=datetime.datetime.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("hours_contributed", models.FloatField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("compensation_paid", models.BooleanField(default=False)),
                ("compensation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "compensation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "researcher_rating",
                    models.IntegerField(
                        blank=True, help_text="1-5 rating by researcher", null=True
                    ),
                ),
                ("participant_feedback", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Research.participantposition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="ResearchGuidelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_guidelines", models.TextField()),
                ("data_collection_guidelines", models.TextField()),
                ("privacy_policy", models.TextField()),
                ("withdrawal_policy", models.TextField()),
                ("communication_guidelines", models.TextField()),
                ("compensation_policy", models.TextField(blank=True)),
                ("data_usage_policy", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "research",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidelines",
                        to="Research.researchproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("methodology_rating", models.IntegerField(blank=True, null=True)),
                ("methodology_feedback", models.TextField(blank=True)),
                ("results_rating", models.IntegerField(blank=True, null=True)),
                ("results_feedback", models.TextField(blank=True)),
                ("conclusion_rating", models.IntegerField(blank=True, null=True)),
                ("conclusion_feedback", models.TextField(blank=True)),
                ("ethics_rating", models.IntegerField(blank=True, null=True)),
                ("ethics_feedback", models.TextField(blank=True)),
                ("general_comments", models.TextField(blank=True)),
                ("confidential_comments", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept"),
                            ("minor_revision", "Minor Revision"),
                            ("major_revision", "Major Revision"),
                            ("reject", "Reject"),
                        ],
                        max_length=50,
                    ),
                ),
                ("assigned_at", models.DateTimeField(default=datetime.datetime.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddField(
            model_name="participantrequirements",
            name="research",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="Research.researchproject",
            ),
        ),
        migrations.AddField(
            model_name="participantposition",
            name="research",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="Research.researchproject",
            ),
        ),
        migrations.CreateModel(
            name="ParticipantMatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(help_text="0-100 compatibility score"),
                ),
                ("matching_criteria", models.JSONField(default=dict)),
                ("age_match", models.FloatField(default=0)),
                ("education_match", models.FloatField(default=0)),
                ("experience_match", models.FloatField(default=0)),
                ("availability_match", models.FloatField(default=0)),
                ("location_match", models.FloatField(default=0)),
                ("matched_at", models.DateTimeField(default=datetime.datetime.now)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("participant_viewed", models.BooleanField(default=False)),
                ("participant_applied", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_matches",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
            },
        ),
        migrations.CreateModel(
            name="ResearchPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                ("full_paper", models.FileField(upload_to="research/publications/")),
                (
                    "supplementary_materials",
                    models.FileField(
                        blank=True, null=True, upload_to="research/supplementary/"
                    ),
                ),
                ("keywords", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                ("authors", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("open_access", "Open Access"),
                            ("institutional", "Institutional Access"),
                            ("restricted", "Restricted"),
                            ("private", "Private"),
                        ],
                        default="restricted",
                        max_length=50,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("views", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(default=0)),
                ("citations", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "research",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["status"], name="Research_re_status_aee636_idx"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(
                fields=["-created_at"], name="Research_re_created_d7e90c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(
                fields=["principal_investigator"], name="Research_re_princip_1850d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(
                fields=["is_published"], name="Research_re_is_publ_b89f7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchparticipant",
            index=models.Index(fields=["status"], name="Research_re_status_f94b71_idx"),
        ),
        migrations.AddIndex(
            model_name="researchparticipant",
            index=models.Index(
                fields=["research", "status"], name="Research_re_researc_91096e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchparticipant",
            index=models.Index(fields=["user"], name="Research_re_user_id_c28f1c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="researchparticipant",
            unique_together={("research", "user")},
        ),
        migrations.AddIndex(
            model_name="researchmilestone",
            index=models.Index(
                fields=["research", "sequence"], name="Research_re_researc_0a2b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peerreview",
            index=models.Index(
                fields=["research", "status"], name="Research_pe_researc_89b427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peerreview",
            index=models.Index(
                fields=["reviewer"], name="Research_pe_reviewe_dc1414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peerreview",
            index=models.Index(fields=["status"], name="Research_pe_status_e818d4_idx"),
        ),
        migrations.AddIndex(
            model_name="participantposition",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="Research_pa_is_acti_864547_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="participantposition",
            index=models.Index(
                fields=["application_deadline"], name="Research_pa_applica_19dc86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participantposition",
            index=models.Index(
                fields=["research"], name="Research_pa_researc_97d3ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participantmatching",
            index=models.Index(
                fields=["-match_score"], name="Research_pa_match_s_442958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participantmatching",
            index=models.Index(
                fields=["participant", "-match_score"],
                name="Research_pa_partici_0dd691_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="participantmatching",
            index=models.Index(
                fields=["research", "-match_score"],
                name="Research_pa_researc_20b4b0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participantmatching",
            unique_together={("participant", "research")},
        ),
        migrations.AddIndex(
            model_name="researchpublication",
            index=models.Index(
                fields=["-published_at"], name="Research_re_publish_94617a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchpublication",
            index=models.Index(
                fields=["is_public"], name="Research_re_is_publ_2ef23d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchpublication",
            index=models.Index(
                fields=["access_level"], name="Research_re_access__b2d2df_idx"
            ),
        ),
    ]
