# Generated by Django 5.2.11 on 2026-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0002_researchproject_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchpublication",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="researchpublication",
            name="fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Publication access fee",
                max_digits=10,
            ),
        ),
    ]
