# Generated by Django 5.2.11 on 2026-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0004_participantapplication_researchanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
