# Generated by Django 5.2.11 on 2026-03-08 10:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0005_researchproject_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantapplication",
            name="form_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Dynamic applicant form responses"
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "requirements_text",
                    models.TextField(blank=True, help_text="Overview of requirements"),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("participants", "Participants"),
                            ("team_members", "Team Members"),
                        ],
                        default="participants",
                        max_length=50,
                    ),
                ),
                (
                    "application_form",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Schema defining the multi-step application form questions/fields",
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "can_convert_to_opinion",
                    models.BooleanField(
                        default=True, help_text="Can be shared to opinions feed"
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recruitment_posts",
                        to="Research.participantposition",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_posts",
                        to="Research.researchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["research", "is_active"],
                        name="Research_re_researc_3a2f6d_idx",
                    ),
                    models.Index(
                        fields=["post_type"], name="Research_re_post_ty_e5df65_idx"
                    ),
                ],
            },
        ),
    ]
