# Generated by Django 5.2.11 on 2026-03-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0006_participantapplication_form_data_recruitmentpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("participants", "Participants"),
                    ("team_members", "Team Members"),
                    ("funding_requests", "Funding Requests"),
                    ("partners_sponsors", "Partners & Sponsors"),
                ],
                default="participants",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ResearcherApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="researcher_applications/resumes/",
                    ),
                ),
                (
                    "verification_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="researcher_applications/verification/",
                    ),
                ),
                ("qualifications", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
