# Generated by Django 5.2.11 on 2026-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0007_alter_recruitmentpost_post_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="requesting_funding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="seeking_participants",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="seeking_partners_sponsors",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="seeking_teams",
            field=models.BooleanField(default=False),
        ),
    ]
