# Generated by Django 5.2.11 on 2026-03-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0008_researchproject_is_paid_researchproject_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researchproject",
            old_name="ethics_approval_number",
            new_name="irb_approval_number",
        ),
        migrations.RenameField(
            model_name="researchproject",
            old_name="irb_approval_document",
            new_name="irb_document",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="consent_form",
        ),
        migrations.AddField(
            model_name="researchproject",
            name="consent_form_template",
            field=models.FileField(
                blank=True, null=True, upload_to="research/consent_templates/"
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="consent_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="ethics_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="requires_irb",
            field=models.BooleanField(default=False),
        ),
    ]
