# Generated by Django 5.1.7 on 2026-01-26 09:25

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_applying_for",
                    models.CharField(
                        choices=[
                            ("researcher", "Researcher"),
                            ("author", "Author"),
                            ("editor", "Editor"),
                            ("publisher", "Publisher"),
                            ("moderator", "Moderator"),
                            ("creator", "Creator"),
                            ("inst_staff", "Institutional Staff"),
                            ("org_staff", "Organizational Staff"),
                            ("lecturer", "Lecturer"),
                            ("student", "Student"),
                        ],
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("id_document", models.FileField(upload_to="credentials/identity/")),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver License"),
                            ("other", "Other Official ID"),
                        ],
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("qualification_documents", models.JSONField(blank=True, default=list)),
                (
                    "cv_resume",
                    models.FileField(
                        blank=True, null=True, upload_to="credentials/cv/"
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("years_of_experience", models.IntegerField(default=0)),
                ("experience_documents", models.JSONField(blank=True, default=list)),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("highest_degree", models.CharField(blank=True, max_length=100)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("alma_mater", models.CharField(blank=True, max_length=300)),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                (
                    "academic_transcripts",
                    models.FileField(
                        blank=True, null=True, upload_to="credentials/transcripts/"
                    ),
                ),
                ("publications", models.JSONField(blank=True, default=list)),
                ("google_scholar_url", models.URLField(blank=True)),
                (
                    "orcid",
                    models.CharField(blank=True, help_text="ORCID iD", max_length=100),
                ),
                ("h_index", models.IntegerField(blank=True, null=True)),
                ("total_citations", models.IntegerField(default=0)),
                ("professional_licenses", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("additional_info_required", "Additional Info Required"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("additional_info_request", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="BackgroundCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("criminal", "Criminal Record"),
                            ("employment", "Employment Verification"),
                            ("education", "Education Verification"),
                            ("reference", "Reference Check"),
                            ("identity", "Identity Verification"),
                            ("credit", "Credit Check"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear", "Clear"),
                            ("flagged", "Flagged"),
                            ("requires_review", "Requires Manual Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("requested_at", models.DateTimeField(default=datetime.datetime.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_background_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential_verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_checks",
                        to="UserManagement.credentialverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("entity_name", models.CharField(max_length=300)),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("role_granted", models.CharField(max_length=50)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("uses_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("institution", "Institution"),
                            ("organization", "Organization"),
                            ("room", "Room"),
                            ("specialization", "Specialization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("entity_name", models.CharField(max_length=300)),
                ("role_requested", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True)),
                ("credentials_submitted", models.JSONField(blank=True, default=dict)),
                ("approval_token", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=datetime.datetime.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="PresetUserAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=50)),
                ("preset_password", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("entity_name", models.CharField(max_length=300)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("user_type", models.CharField(blank=True, max_length=50)),
                ("activated", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("invitation_sent", models.BooleanField(default=False)),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preset_accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preset_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualification_type",
                    models.CharField(
                        choices=[
                            ("degree", "Academic Degree"),
                            ("certificate", "Professional Certificate"),
                            ("license", "Professional License"),
                            ("award", "Award/Recognition"),
                            ("training", "Professional Training"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("institution", models.CharField(max_length=300)),
                ("field", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor Degree"),
                            ("master", "Master Degree"),
                            ("doctoral", "Doctoral Degree"),
                            ("postdoctoral", "Postdoctoral"),
                            ("professional", "Professional Certification"),
                        ],
                        max_length=100,
                    ),
                ),
                ("year_obtained", models.IntegerField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("document", models.FileField(upload_to="qualifications/")),
                (
                    "credential_url",
                    models.URLField(blank=True, help_text="Link to verify online"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_qualifications",
                        to="UserManagement.credentialverification",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_other_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year_obtained"],
            },
        ),
        migrations.AddIndex(
            model_name="credentialverification",
            index=models.Index(
                fields=["user", "status"], name="UserManagem_user_id_dae1ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialverification",
            index=models.Index(
                fields=["status", "-submitted_at"], name="UserManagem_status_19221d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialverification",
            index=models.Index(
                fields=["role_applying_for"], name="UserManagem_role_ap_0b9569_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialverification",
            index=models.Index(
                fields=["reviewed_by"], name="UserManagem_reviewe_fda9d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundcheck",
            index=models.Index(
                fields=["user", "status"], name="UserManagem_user_id_7f78a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundcheck",
            index=models.Index(
                fields=["check_type", "status"], name="UserManagem_check_t_577594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitationlink",
            index=models.Index(fields=["token"], name="UserManagem_token_246c5a_idx"),
        ),
        migrations.AddIndex(
            model_name="invitationlink",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="UserManagem_entity__5a675c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationlink",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="UserManagem_is_acti_97aaa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["entity_type", "entity_id", "status"],
                name="UserManagem_entity__ba65df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["user", "status"], name="UserManagem_user_id_aba443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["approval_token"], name="UserManagem_approva_5d9a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presetuseraccount",
            index=models.Index(fields=["email"], name="UserManagem_email_965dd7_idx"),
        ),
        migrations.AddIndex(
            model_name="presetuseraccount",
            index=models.Index(
                fields=["activated", "expires_at"],
                name="UserManagem_activat_8aa42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presetuseraccount",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="UserManagem_entity__1e9aca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userqualification",
            index=models.Index(
                fields=["user", "verified"], name="UserManagem_user_id_a2cf4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userqualification",
            index=models.Index(
                fields=["qualification_type"], name="UserManagem_qualifi_db437a_idx"
            ),
        ),
    ]
