# Generated by Django 5.1.7 on 2026-01-07 09:06

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("branch_code", models.CharField(max_length=200, unique=True)),
                ("origin", models.CharField(blank=True, max_length=500)),
                ("abbreviation", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=200)),
                ("town", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution Branch",
                "verbose_name_plural": "Institution Branches",
            },
        ),
        migrations.CreateModel(
            name="AdminDep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("admin_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admin_dep_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_departments",
                        to="Institution.instbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Department",
                "verbose_name_plural": "Administrative Departments",
            },
        ),
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("finance_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_departments",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="finance_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Department",
                "verbose_name_plural": "Finance Departments",
            },
        ),
        migrations.CreateModel(
            name="HR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("hr_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_departments",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hr_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Department",
                "verbose_name_plural": "HR Departments",
            },
        ),
        migrations.CreateModel(
            name="ICT",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("ict_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ict_departments",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ict_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ICT Department",
                "verbose_name_plural": "ICT Departments",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("faculty_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faculty_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="Institution.instbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.CreateModel(
            name="InstDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("dep_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="Institution.faculty",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inst_department_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Department",
                "verbose_name_plural": "Institution Departments",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("school", "School"),
                            ("company", "Company"),
                            ("ngo", "Non-Governmental Organization"),
                            ("government", "Government Agency"),
                            ("research", "Research Institution"),
                            ("hospital", "Hospital/Medical"),
                            ("other", "Other"),
                        ],
                        default="university",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("website_verified", models.BooleanField(default=False)),
                (
                    "website_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "website_verification_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Submission"),
                            ("submitted", "Submitted for Review"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("documents_submitted", models.BooleanField(default=False)),
                ("documents_verified", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_public_signup", models.BooleanField(default=False)),
                ("require_email_domain", models.BooleanField(default=False)),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_institutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inst_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AddField(
            model_name="instbranch",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculties",
                to="Institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="admindep",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_departments",
                to="Institution.institution",
            ),
        ),
        migrations.CreateModel(
            name="InstitutionMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator/Owner"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("subscriber", "Subscriber"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("invitation_accepted", models.BooleanField(default=False)),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("invitation_expires_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="Institution.institution",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_institution_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionVerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration_cert", "Registration Certificate"),
                            ("tax_id", "Tax ID Document"),
                            ("proof_address", "Proof of Address"),
                            ("director_id", "Director ID"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("virus_scanned", models.BooleanField(default=False)),
                (
                    "virus_scan_result",
                    models.CharField(default="pending", max_length=50),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_documents",
                        to="Institution.institution",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionVerificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Institution Created"),
                            ("email_sent", "Email Verification Sent"),
                            ("email_verified", "Email Verified"),
                            ("website_verified", "Website Verified"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_verified", "Document Verified"),
                            ("submitted", "Submitted for Review"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("reactivated", "Reactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="Institution.institution",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Legal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("legal_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_departments",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="legal_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Department",
                "verbose_name_plural": "Legal Departments",
            },
        ),
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("marketing_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_departments",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="marketing_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Department",
                "verbose_name_plural": "Marketing Departments",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("school", "School"),
                            ("company", "Company"),
                            ("ngo", "Non-Governmental Organization"),
                            ("government", "Government Agency"),
                            ("research", "Research Institution"),
                            ("hospital", "Hospital/Medical"),
                            ("other", "Other"),
                        ],
                        default="company",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("website", models.URLField(blank=True, null=True)),
                ("website_verified", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Submission"),
                            ("submitted", "Submitted for Review"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.CreateModel(
            name="OtherInstitutionUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("unit_code", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_units",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_units",
                        to="Institution.institution",
                    ),
                ),
                (
                    "parent_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="child_units",
                        to="Institution.otherinstitutionunit",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="other_unit_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Other Institution Unit",
                "verbose_name_plural": "Other Institution Units",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("programme_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="Institution.instdepartment",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="programme_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
        migrations.CreateModel(
            name="RegistrarOffice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("registrar_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrar_offices",
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registrar_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrar Office",
                "verbose_name_plural": "Registrar Offices",
            },
        ),
        migrations.CreateModel(
            name="StudentAffairs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("stud_affairs_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_affairs",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_affairs",
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_affairs_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Affairs",
                "verbose_name_plural": "Student Affairs",
            },
        ),
        migrations.CreateModel(
            name="Counselling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("counselling_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="counselling_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stud_affairs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselling_services",
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselling Service",
                "verbose_name_plural": "Counselling Services",
            },
        ),
        migrations.CreateModel(
            name="CareerOffice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("career_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="career_office_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stud_affairs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_offices",
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Office",
                "verbose_name_plural": "Career Offices",
            },
        ),
        migrations.CreateModel(
            name="Admissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("admissions_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admissions_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stud_affairs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions_offices",
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admissions Office",
                "verbose_name_plural": "Admissions Offices",
            },
        ),
        migrations.CreateModel(
            name="SupportServices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "support_services_code",
                    models.CharField(max_length=500, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_services",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_services",
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="support_services_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Services",
                "verbose_name_plural": "Support Services",
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("security_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="security_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_units",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Service",
                "verbose_name_plural": "Security Services",
            },
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("library_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="library_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libraries",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
            },
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("hostel_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hostel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostels",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hostel",
                "verbose_name_plural": "Hostels",
            },
        ),
        migrations.CreateModel(
            name="HealthServices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("health_services_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="health_services_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_services",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Service",
                "verbose_name_plural": "Health Services",
            },
        ),
        migrations.CreateModel(
            name="Cafeteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("cafeteria_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cafeteria_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeterias",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cafeteria",
                "verbose_name_plural": "Cafeterias",
            },
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("transport_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transport_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_units",
                        to="Institution.supportservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Service",
                "verbose_name_plural": "Transport Services",
            },
        ),
        migrations.CreateModel(
            name="VCOffice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("office_code", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vc_offices",
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vc_offices",
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vc_office_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vice Chancellor Office",
                "verbose_name_plural": "Vice Chancellor Offices",
            },
        ),
        migrations.CreateModel(
            name="WebsiteVerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("dns", "DNS TXT Record"), ("meta", "Meta Tag")],
                        max_length=20,
                    ),
                ),
                ("verification_token", models.CharField(max_length=100)),
                ("verification_code", models.CharField(max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ssl_valid", models.BooleanField(default=False)),
                ("safe_browsing_passed", models.BooleanField(default=False)),
                ("domain_age_days", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_verifications",
                        to="Institution.institution",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="instdepartment",
            index=models.Index(
                fields=["faculty", "is_active"], name="Institution_faculty_bd2938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["status"], name="Institution_status_ca9fea_idx"),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["created_by"], name="Institution_created_799644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["email"], name="Institution_email_dd8ff7_idx"),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["-created_at"], name="Institution_created_cf4bf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instbranch",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_c60401_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instbranch",
            index=models.Index(
                fields=["branch_code"], name="Institution_branch__82cc85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faculty",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_debce9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="admindep",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_ce55b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionmember",
            index=models.Index(
                fields=["institution", "role"], name="Institution_institu_f62d0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionmember",
            index=models.Index(fields=["user"], name="Institution_user_id_fb7d36_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="institutionmember",
            unique_together={("institution", "user")},
        ),
        migrations.AddIndex(
            model_name="institutionverificationdocument",
            index=models.Index(
                fields=["institution", "document_type"],
                name="Institution_institu_852cf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionverificationdocument",
            index=models.Index(
                fields=["verified"], name="Institution_verifie_1ad839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionverificationlog",
            index=models.Index(
                fields=["institution", "-timestamp"],
                name="Institution_institu_21bdf8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionverificationlog",
            index=models.Index(fields=["action"], name="Institution_action_2cfe9b_idx"),
        ),
        migrations.AddIndex(
            model_name="otherinstitutionunit",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_fe6b87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(
                fields=["department", "is_active"],
                name="Institution_departm_a54ce6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentaffairs",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_54d23c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportservices",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_d83402_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vcoffice",
            index=models.Index(
                fields=["institution", "is_active"],
                name="Institution_institu_0d9f2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websiteverificationrequest",
            index=models.Index(
                fields=["institution", "-created_at"],
                name="Institution_institu_619965_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websiteverificationrequest",
            index=models.Index(
                fields=["verified"], name="Institution_verifie_bfa583_idx"
            ),
        ),
    ]
