# Generated by Django 5.1.7 on 2026-01-06 10:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstBranch",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "branch_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("origin", models.CharField(max_length=500)),
                ("abbreviation", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("town", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "inst_type",
                    models.CharField(
                        choices=[
                            ("business", "Business Enterprise"),
                            ("ngo", "Non-Governmental Organisation (NGO)"),
                            ("learning_inst", "Learning Institution"),
                            ("go", "Governmental Organisation"),
                            ("ministry", "Ministry Organisation"),
                            ("other", "Other"),
                        ],
                        default="learning_inst",
                        max_length=500,
                    ),
                ),
                ("origin", models.CharField(max_length=500)),
                ("abbreviation", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("town", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("academic_disc", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="AdminDep",
            fields=[
                (
                    "admin_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "finance_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HR",
            fields=[
                (
                    "hr_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ICT",
            fields=[
                (
                    "ict_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "faculty_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstDepartment",
            fields=[
                (
                    "dep_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "faculty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.faculty",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instbranch",
            name="institution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Institution.institution",
            ),
        ),
        migrations.CreateModel(
            name="Legal",
            fields=[
                (
                    "legal_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "marketing_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherInstitutionUnit",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "unit_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "parent_units",
                    models.ManyToManyField(
                        blank=True, to="Institution.otherinstitutionunit"
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "programme_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "faculty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instdepartment",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrarOffice",
            fields=[
                (
                    "registrar_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "admin_dep",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.admindep",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAffairs",
            fields=[
                (
                    "stud_affairs_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Counselling",
            fields=[
                (
                    "counselling_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerOffice",
            fields=[
                (
                    "career_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admissions",
            fields=[
                (
                    "admissions_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportServices",
            fields=[
                (
                    "support_services_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "security_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "library_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "hostel_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthServices",
            fields=[
                (
                    "health_services_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cafeteria",
            fields=[
                (
                    "cafeteria_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "transport_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VCOffice",
            fields=[
                (
                    "office_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
