# Generated by Django 5.1.7 on 2025-11-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafeteria",
            fields=[
                (
                    "cafeteria_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Counselling",
            fields=[
                (
                    "counselling_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.studentaffairs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "hostel_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "library_code",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "stud_affairs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.supportservices",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Couselling",
        ),
    ]
