# Generated by Django 5.1.7 on 2025-11-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0002_cafeteria_counselling_hostel_library_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherInstitutionUnit",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "unit_code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "inst_branch",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.instbranch",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Institution.institution",
                    ),
                ),
                (
                    "parent_units",
                    models.ManyToManyField(
                        blank=True, to="Institution.otherinstitutionunit"
                    ),
                ),
            ],
        ),
    ]
