# Generated by Django 5.1.7 on 2026-02-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0002_admindep_approval_status_admindep_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instdepartment",
            name="inst_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="Institution.instbranch",
            ),
        ),
        migrations.AddField(
            model_name="instdepartment",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="Institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="instdepartment",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="Institution.faculty",
            ),
        ),
    ]
