# Generated by Django 5.1.7 on 2026-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0004_admissions_inst_branch_admissions_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionmember",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Custom editable title (e.g. 'Dean of Faculty')",
                max_length=200,
            ),
        ),
    ]
