# Generated by Django 5.2.11 on 2026-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0005_institutionmember_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="cover_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="institution_covers/"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="institution_profiles/"
            ),
        ),
    ]
