# Generated by Django 5.2.11 on 2026-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0007_institution_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="portal_password",
            field=models.CharField(
                blank=True,
                help_text="Hashed portal password for entity account switching",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="portal_password_type",
            field=models.CharField(
                blank=True,
                choices=[("pin", "PIN (numeric)"), ("password", "Password")],
                default="pin",
                max_length=10,
            ),
        ),
    ]
