from django.contrib import admin
from Events.models import Event, EventCategory, EventAttendance, EventBudget, EventCategoryAssignment, EventCollaboration, EventFeedback, EventFeedbackResponse, EventFile, EventFollowUp, EventLogistics, EventMediaCoverage, EventPartnership, EventPhoto, EventPromotion, EventRegistration, EventReminder, EventSchedule, EventSession, EventSpeaker, EventSponsor, EventSponsorAgreement, EventSponsorBenefit, EventSponsorLogo, EventSponsorPackage, EventSponsorPayment, EventSponsorshipAgreementDocument, EventSponsorshipApplication, EventSponsorshipApproval, EventSponsorshipCertificate, EventSponsorshipContract, EventSponsorshipDowngrade, EventSponsorshipEvaluation, EventSponsorshipExtension, EventSponsorshipFeedback, EventSponsorshipHistory, EventSponsorshipInvoice, EventSponsorshipLetter, EventSponsorshipLevel, EventSponsorshipRecognition, EventSponsorshipRejection, EventSponsorshipRenewal, EventSponsorshipReport, EventSponsorshipTermination, EventSponsorshipTransfer, EventSponsorshipUpgrade, EventSurvey, EventSurveyQuestion, EventSurveyResponse, EventTag, EventTagAssignment, EventTicket, EventVideo

# Register your models here.
admin.site.register(Event)
admin.site.register(EventCategory)
admin.site.register(EventCategoryAssignment)
admin.site.register(EventAttendance)
admin.site.register(EventBudget)
admin.site.register(EventCollaboration)
admin.site.register(EventFeedback)
admin.site.register(EventFeedbackResponse)
admin.site.register(EventFile)
admin.site.register(EventFollowUp)
admin.site.register(EventMediaCoverage)
admin.site.register(EventPartnership)
admin.site.register(EventPhoto)
admin.site.register(EventPromotion)
admin.site.register(EventRegistration)
admin.site.register(EventReminder)
admin.site.register(EventLogistics)
admin.site.register(EventSchedule)
admin.site.register(EventSession)
admin.site.register(EventSpeaker)
admin.site.register(EventSponsor)
admin.site.register(EventSponsorAgreement)
admin.site.register(EventSponsorBenefit)
admin.site.register(EventSponsorLogo)
admin.site.register(EventSponsorPackage)
admin.site.register(EventSponsorPayment)
admin.site.register(EventSponsorshipAgreementDocument)
admin.site.register(EventSponsorshipApplication)
admin.site.register(EventSponsorshipApproval)
admin.site.register(EventSponsorshipCertificate)
admin.site.register(EventSponsorshipContract)
admin.site.register(EventSponsorshipDowngrade)
admin.site.register(EventSponsorshipEvaluation)
admin.site.register(EventSponsorshipExtension)
admin.site.register(EventSponsorshipFeedback)
admin.site.register(EventSponsorshipHistory)
admin.site.register(EventSponsorshipInvoice)
admin.site.register(EventSponsorshipLetter)
admin.site.register(EventSponsorshipLevel)
admin.site.register(EventSponsorshipRecognition)
admin.site.register(EventSponsorshipRejection)
admin.site.register(EventSponsorshipRenewal)
admin.site.register(EventSponsorshipReport)
admin.site.register(EventSponsorshipTermination)
admin.site.register(EventSponsorshipTransfer)
admin.site.register(EventSponsorshipUpgrade)
admin.site.register(EventSurvey)
admin.site.register(EventSurveyQuestion)
admin.site.register(EventSurveyResponse)
admin.site.register(EventTag)
admin.site.register(EventTagAssignment)
admin.site.register(EventTicket)
admin.site.register(EventVideo)


