# Generated by Django 5.1.7 on 2026-01-31 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_likes", models.BooleanField(default=True)),
                ("email_comments", models.BooleanField(default=True)),
                ("email_follows", models.BooleanField(default=True)),
                ("email_mentions", models.BooleanField(default=True)),
                ("email_reposts", models.BooleanField(default=True)),
                ("email_announcements", models.BooleanField(default=True)),
                ("push_likes", models.BooleanField(default=True)),
                ("push_comments", models.BooleanField(default=True)),
                ("push_follows", models.BooleanField(default=True)),
                ("push_mentions", models.BooleanField(default=True)),
                ("push_reposts", models.BooleanField(default=True)),
                ("push_announcements", models.BooleanField(default=True)),
                ("email_digest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("repost", "Repost"),
                            ("mention", "Mention"),
                            ("reply", "Reply"),
                            ("research_update", "Research Update"),
                            ("article_published", "Article Published"),
                            ("product_update", "Product Update"),
                            ("system", "System"),
                            ("announcement", "Announcement"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("content_id", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="Notificatio_recipie_af3b05_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="Notificatio_recipie_8bac12_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="Notificatio_notific_65eb51_idx",
                    ),
                ],
            },
        ),
    ]
