# Generated by Django 5.2.11 on 2026-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("repost", "Repost"),
                    ("mention", "Mention"),
                    ("reply", "Reply"),
                    ("research_update", "Research Update"),
                    ("article_published", "Article Published"),
                    ("product_update", "Product Update"),
                    ("system", "System"),
                    ("announcement", "Announcement"),
                    ("recommendation", "Recommendation"),
                    ("trending", "Trending"),
                    ("suggested", "Suggested"),
                    ("profile_view", "Profile View"),
                    ("new_post", "New Post"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
