# Generated by Django 5.2.11 on 2026-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifications", "0004_provider_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("repost", "Repost"),
                    ("mention", "Mention"),
                    ("reply", "Reply"),
                    ("research_update", "Research Update"),
                    ("article_published", "Article Published"),
                    ("product_update", "Product Update"),
                    ("system", "System"),
                    ("announcement", "Announcement"),
                    ("recommendation", "Recommendation"),
                    ("trending", "Trending"),
                    ("suggested", "Suggested"),
                    ("profile_view", "Profile View"),
                    ("new_post", "New Post"),
                    ("group_round", "Group Round"),
                    ("group_contribution", "Group Contribution"),
                    ("group_claim", "Group Claim"),
                    ("group_message", "Group Message"),
                    ("event_reminder", "Event Reminder"),
                    ("provider_application_submitted", "Application Submitted"),
                    ("provider_application_approved", "Application Approved"),
                    ("provider_application_rejected", "Application Rejected"),
                    (
                        "provider_application_requires_changes",
                        "Application Requires Changes",
                    ),
                    ("provider_query_response", "Query Response"),
                    ("provider_transaction_complete", "Transaction Complete"),
                    ("provider_transaction_refund", "Transaction Refund"),
                    ("provider_payout_received", "Payout Received"),
                    ("provider_document_approved", "Document Approved"),
                    ("provider_document_rejected", "Document Rejected"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
