# Generated by Django 5.1.6 on 2025-07-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('only_me', 'Only Me')], default='public', max_length=20)),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='', max_length=1000)),
                ('file_type', models.CharField(choices=[('media_link', 'Media Link'), ('text', 'Text'), ('image', 'Image file'), ('doc', 'Document File')], default='doc', max_length=20)),
                ('res_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('res_text', models.TextField(blank=True, max_length=50000, null=True)),
            ],
        ),
    ]
