# Generated by Django 5.1.7 on 2025-11-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("desc", models.TextField(default="", max_length=1000)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("media_link", "Media Link"),
                            ("text", "Text"),
                            ("image", "Image file"),
                            ("doc", "Document File"),
                        ],
                        default="doc",
                        max_length=20,
                    ),
                ),
                (
                    "res_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("res_text", models.TextField(blank=True, max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Resources.resource",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Rooms.room"
                    ),
                ),
            ],
        ),
    ]
