# Generated by Django 5.1.7 on 2026-01-06 10:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0003_initial"),
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visibility",
            fields=[
                (
                    "main_entity",
                    models.CharField(
                        choices=[
                            ("comrade", "Comrade"),
                            ("creator", "Creator"),
                            ("admins", "Entity Admins"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("resources", "Resources"),
                            ("rooms", "Rooms"),
                            ("default_rooms", "Default Rooms"),
                            ("direct_message_rooms", "Direct Message Rooms"),
                            ("organisations", "Organisations"),
                            ("organisation_branches", "Organisation Branches"),
                            ("departments", "Departments"),
                            ("sections", "Sections"),
                            ("committees", "Committees"),
                            ("units", "Units"),
                            ("programs", "Programs"),
                            ("projects", "Projects"),
                            ("centres", "Centres"),
                            ("teams", "Teams"),
                            ("divisions", "Divisions"),
                            ("boards", "Boards"),
                            ("institutes", "Institutes"),
                            ("other_organisation_units", "Other Organisation Units"),
                            ("institutions", "Institutions"),
                            ("institution_branches", "Institution Branches"),
                            ("faculties", "Faculties"),
                            ("vc_offices", "VC Offices"),
                            ("inst_departments", "Institution Departments"),
                            ("admin_deps", "Admin Departments"),
                            ("programmes", "Programmes"),
                            ("hrs", "HRs"),
                            ("admissions", "Admissions"),
                            ("health_services", "Health Services"),
                            ("securities", "Securities"),
                            ("student_affairs", "Student Affairs"),
                            ("support_services", "Support Services"),
                            ("finances", "Finances"),
                            ("marketings", "Marketings"),
                            ("legals", "Legals"),
                            ("icts", "ICTs"),
                            ("career_offices", "Career Offices"),
                            ("counsellings", "Counsellings"),
                            ("registrar_offices", "Registrar Offices"),
                            ("transports", "Transports"),
                            ("libraries", "Libraries"),
                            ("hostels", "Hostels"),
                            ("cafeterias", "Cafeterias"),
                            ("other_institution_units", "Other Institution Units"),
                            ("public", "Public"),
                        ],
                        default="resource",
                        max_length=1000,
                    ),
                ),
                (
                    "visibility_code",
                    models.CharField(
                        max_length=2000, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "operation_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("deleted", "Deleted"),
                            ("suspended", "Suspended"),
                            ("under_review", "Under Review"),
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sensored", "Sensored"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True)),
                ("expiry_time", models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_on", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=5000)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_links",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainVisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_visibility_changed_logs",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("only_me", "Only Me"),
                            ("rooms", "Rooms"),
                            ("default_rooms", "Default Rooms"),
                            ("direct_message_rooms", "Direct Message Rooms"),
                            ("organisations", "Organisations"),
                            ("organisation_branches", "Organisation Branches"),
                            ("departments", "Departments"),
                            ("sections", "Sections"),
                            ("committees", "Committees"),
                            ("units", "Units"),
                            ("programs", "Programs"),
                            ("projects", "Projects"),
                            ("centres", "Centres"),
                            ("teams", "Teams"),
                            ("divisions", "Divisions"),
                            ("boards", "Boards"),
                            ("institutes", "Institutes"),
                            ("other_organisation_units", "Other Organisation Units"),
                            ("institutions", "Institutions"),
                            ("institution_branches", "Institution Branches"),
                            ("faculties", "Faculties"),
                            ("vc_offices", "VC Offices"),
                            ("inst_departments", "Institution Departments"),
                            ("admin_deps", "Admin Departments"),
                            ("programmes", "Programmes"),
                            ("hrs", "HRs"),
                            ("admissions", "Admissions"),
                            ("health_services", "Health Services"),
                            ("securities", "Securities"),
                            ("student_affairs", "Student Affairs"),
                            ("support_services", "Support Services"),
                            ("finances", "Finances"),
                            ("marketings", "Marketings"),
                            ("legals", "Legals"),
                            ("icts", "ICTs"),
                            ("career_offices", "Career Offices"),
                            ("counsellings", "Counsellings"),
                            ("registrar_offices", "Registrar Offices"),
                            ("transports", "Transports"),
                            ("libraries", "Libraries"),
                            ("hostels", "Hostels"),
                            ("cafeterias", "Cafeterias"),
                            ("other_institution_units", "Other Institution Units"),
                            ("public", "Public"),
                        ],
                        default="public",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("desc", models.TextField(default="", max_length=1000)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("media_link", "Media Link"),
                            ("text", "Text"),
                            ("image", "Image file"),
                            ("doc", "Document File"),
                        ],
                        default="doc",
                        max_length=20,
                    ),
                ),
                (
                    "res_file",
                    models.FileField(blank=True, null=True, upload_to="resources/docs"),
                ),
                ("res_text", models.TextField(blank=True, null=True)),
                ("res_link", models.URLField(blank=True, null=True)),
                (
                    "price_tag",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("created_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_resources",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_resources",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edited_resources",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_deps",
                    models.ManyToManyField(blank=True, to="Institution.admindep"),
                ),
                (
                    "admissions",
                    models.ManyToManyField(blank=True, to="Institution.admissions"),
                ),
                ("boards", models.ManyToManyField(blank=True, to="Organisation.board")),
                (
                    "cafeterias",
                    models.ManyToManyField(blank=True, to="Institution.cafeteria"),
                ),
                (
                    "career_offices",
                    models.ManyToManyField(blank=True, to="Institution.careeroffice"),
                ),
                (
                    "centres",
                    models.ManyToManyField(blank=True, to="Organisation.centre"),
                ),
                (
                    "committees",
                    models.ManyToManyField(blank=True, to="Organisation.committee"),
                ),
                (
                    "counsellings",
                    models.ManyToManyField(blank=True, to="Institution.counselling"),
                ),
            ],
        ),
    ]
