# Generated by Django 5.1.7 on 2026-01-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Authentication", "0003_initial"),
        ("Events", "0002_initial"),
        ("Institution", "0001_initial"),
        ("Organisation", "0001_initial"),
        ("Resources", "0001_initial"),
        ("Rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcevisibility",
            name="default_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="departments",
            field=models.ManyToManyField(blank=True, to="Organisation.department"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="direct_message_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="divisions",
            field=models.ManyToManyField(blank=True, to="Organisation.division"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="events",
            field=models.ManyToManyField(blank=True, to="Events.event"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="faculties",
            field=models.ManyToManyField(blank=True, to="Institution.faculty"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="finances",
            field=models.ManyToManyField(blank=True, to="Institution.finance"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="health_services",
            field=models.ManyToManyField(blank=True, to="Institution.healthservices"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="hostels",
            field=models.ManyToManyField(blank=True, to="Institution.hostel"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="hrs",
            field=models.ManyToManyField(blank=True, to="Institution.hr"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="icts",
            field=models.ManyToManyField(blank=True, to="Institution.ict"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="inst_departments",
            field=models.ManyToManyField(blank=True, to="Institution.instdepartment"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institutes",
            field=models.ManyToManyField(blank=True, to="Organisation.institute"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institution_branches",
            field=models.ManyToManyField(blank=True, to="Institution.instbranch"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institutions",
            field=models.ManyToManyField(blank=True, to="Institution.institution"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="legals",
            field=models.ManyToManyField(blank=True, to="Institution.legal"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="libraries",
            field=models.ManyToManyField(blank=True, to="Institution.library"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="marketings",
            field=models.ManyToManyField(blank=True, to="Institution.marketing"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="Organisation.organisation"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="organistion_branches",
            field=models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="other_institution_units",
            field=models.ManyToManyField(
                blank=True, to="Institution.otherinstitutionunit"
            ),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="other_organisation_units",
            field=models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="programmes",
            field=models.ManyToManyField(blank=True, to="Institution.programme"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="programs",
            field=models.ManyToManyField(blank=True, to="Organisation.program"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="projects",
            field=models.ManyToManyField(blank=True, to="Organisation.project"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="registrar_offices",
            field=models.ManyToManyField(blank=True, to="Institution.registraroffice"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="resource",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_visibility",
                to="Resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.room"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="sections",
            field=models.ManyToManyField(blank=True, to="Organisation.section"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="securities",
            field=models.ManyToManyField(blank=True, to="Institution.security"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="student_affairs",
            field=models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="support_services",
            field=models.ManyToManyField(blank=True, to="Institution.supportservices"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="teams",
            field=models.ManyToManyField(blank=True, to="Organisation.team"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="transports",
            field=models.ManyToManyField(blank=True, to="Institution.transport"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="units",
            field=models.ManyToManyField(blank=True, to="Organisation.unit"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="users_with_access",
            field=models.ManyToManyField(blank=True, to="Authentication.profile"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="vc_offices",
            field=models.ManyToManyField(blank=True, to="Institution.vcoffice"),
        ),
        migrations.AddField(
            model_name="mainvisibilitylog",
            name="new_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_main_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AddField(
            model_name="mainvisibilitylog",
            name="previous_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_main_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="admin_deps",
            field=models.ManyToManyField(blank=True, to="Institution.admindep"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="admissions",
            field=models.ManyToManyField(blank=True, to="Institution.admissions"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="boards",
            field=models.ManyToManyField(blank=True, to="Organisation.board"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="cafeterias",
            field=models.ManyToManyField(blank=True, to="Institution.cafeteria"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="career_offices",
            field=models.ManyToManyField(blank=True, to="Institution.careeroffice"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="centres",
            field=models.ManyToManyField(blank=True, to="Organisation.centre"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="committees",
            field=models.ManyToManyField(blank=True, to="Organisation.committee"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="counsellings",
            field=models.ManyToManyField(blank=True, to="Institution.counselling"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="default_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="departments",
            field=models.ManyToManyField(blank=True, to="Organisation.department"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="direct_message_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="divisions",
            field=models.ManyToManyField(blank=True, to="Organisation.division"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="events",
            field=models.ManyToManyField(blank=True, to="Events.event"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="faculties",
            field=models.ManyToManyField(blank=True, to="Institution.faculty"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="finances",
            field=models.ManyToManyField(blank=True, to="Institution.finance"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="health_services",
            field=models.ManyToManyField(blank=True, to="Institution.healthservices"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="hostels",
            field=models.ManyToManyField(blank=True, to="Institution.hostel"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="hrs",
            field=models.ManyToManyField(blank=True, to="Institution.hr"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="icts",
            field=models.ManyToManyField(blank=True, to="Institution.ict"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="inst_departments",
            field=models.ManyToManyField(blank=True, to="Institution.instdepartment"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="institutes",
            field=models.ManyToManyField(blank=True, to="Organisation.institute"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="institution_branches",
            field=models.ManyToManyField(blank=True, to="Institution.instbranch"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="institutions",
            field=models.ManyToManyField(blank=True, to="Institution.institution"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="legals",
            field=models.ManyToManyField(blank=True, to="Institution.legal"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="libraries",
            field=models.ManyToManyField(blank=True, to="Institution.library"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="marketings",
            field=models.ManyToManyField(blank=True, to="Institution.marketing"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="Organisation.organisation"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="organistion_branches",
            field=models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="other_institution_units",
            field=models.ManyToManyField(
                blank=True, to="Institution.otherinstitutionunit"
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="other_organisation_units",
            field=models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="programmes",
            field=models.ManyToManyField(blank=True, to="Institution.programme"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="programs",
            field=models.ManyToManyField(blank=True, to="Organisation.program"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="projects",
            field=models.ManyToManyField(blank=True, to="Organisation.project"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="registrar_offices",
            field=models.ManyToManyField(blank=True, to="Institution.registraroffice"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="main_visibility_resources",
                to="Resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.room"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="sections",
            field=models.ManyToManyField(blank=True, to="Organisation.section"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="securities",
            field=models.ManyToManyField(blank=True, to="Institution.security"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="student_affairs",
            field=models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="support_services",
            field=models.ManyToManyField(blank=True, to="Institution.supportservices"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="teams",
            field=models.ManyToManyField(blank=True, to="Organisation.team"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="transports",
            field=models.ManyToManyField(blank=True, to="Institution.transport"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="units",
            field=models.ManyToManyField(blank=True, to="Organisation.unit"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="users_with_access",
            field=models.ManyToManyField(blank=True, to="Authentication.profile"),
        ),
        migrations.AddField(
            model_name="visibility",
            name="vc_offices",
            field=models.ManyToManyField(blank=True, to="Institution.vcoffice"),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visibility_changed_logs",
                to="Authentication.profile",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="new_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="previous_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_logs",
                to="Resources.resource",
            ),
        ),
    ]
