# Generated by Django 5.2.11 on 2026-02-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0002_article_institution_article_organisation"),
        (
            "Opinions",
            "0004_story_storyview_story_opinions_st_created_2d73c6_idx_and_more",
        ),
        ("Research", "0003_researchpublication_currency_researchpublication_fee"),
        ("Resources", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="linked_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_resources",
                to="Articles.article",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="linked_opinion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_resources",
                to="Opinions.opinion",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="linked_research",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_resources",
                to="Research.researchproject",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("announcement_requested", "Announcement Requested"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
