# Generated by Django 5.1.7 on 2025-11-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0002_resourcevisibility_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcevisibility",
            name="resource",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Resources.resource"
            ),
        ),
    ]
