# Generated by Django 5.1.7 on 2025-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0003_alter_resourcevisibility_resource"),
        ("Rooms", "0009_alter_defaultroom_room_code_alter_room_room_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcevisibility",
            name="room",
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="default_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.room"),
        ),
    ]
