# Generated by Django 5.2.11 on 2026-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0003_resource_category_resource_linked_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibility",
            name="main_entity",
            field=models.CharField(
                choices=[
                    ("comrade", "Qomrade"),
                    ("creator", "Creator"),
                    ("admins", "Entity Admins"),
                    ("admins_moderators", "Admins and Moderators"),
                    ("resources", "Resources"),
                    ("rooms", "Rooms"),
                    ("default_rooms", "Default Rooms"),
                    ("direct_message_rooms", "Direct Message Rooms"),
                    ("organisations", "Organisations"),
                    ("organisation_branches", "Organisation Branches"),
                    ("departments", "Departments"),
                    ("sections", "Sections"),
                    ("committees", "Committees"),
                    ("units", "Units"),
                    ("programs", "Programs"),
                    ("projects", "Projects"),
                    ("centres", "Centres"),
                    ("teams", "Teams"),
                    ("divisions", "Divisions"),
                    ("boards", "Boards"),
                    ("institutes", "Institutes"),
                    ("other_organisation_units", "Other Organisation Units"),
                    ("institutions", "Institutions"),
                    ("institution_branches", "Institution Branches"),
                    ("faculties", "Faculties"),
                    ("vc_offices", "VC Offices"),
                    ("inst_departments", "Institution Departments"),
                    ("admin_deps", "Admin Departments"),
                    ("programmes", "Programmes"),
                    ("hrs", "HRs"),
                    ("admissions", "Admissions"),
                    ("health_services", "Health Services"),
                    ("securities", "Securities"),
                    ("student_affairs", "Student Affairs"),
                    ("support_services", "Support Services"),
                    ("finances", "Finances"),
                    ("marketings", "Marketings"),
                    ("legals", "Legals"),
                    ("icts", "ICTs"),
                    ("career_offices", "Career Offices"),
                    ("counsellings", "Counsellings"),
                    ("registrar_offices", "Registrar Offices"),
                    ("transports", "Transports"),
                    ("libraries", "Libraries"),
                    ("hostels", "Hostels"),
                    ("cafeterias", "Cafeterias"),
                    ("other_institution_units", "Other Institution Units"),
                    ("public", "Public"),
                ],
                default="resource",
                max_length=1000,
            ),
        ),
    ]
