# Generated by Django 5.2.11 on 2026-03-05 06:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0008_customuser_date_of_birth_and_more"),
        ("Resources", "0004_alter_visibility_main_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Reason for requesting access"
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_access_requests",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="Resources.resource",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_access_requests",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "unique_together": {("resource", "requester")},
            },
        ),
        migrations.CreateModel(
            name="ResourceAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("download", "Downloaded"),
                            ("share", "Shared"),
                            ("access_request", "Access Requested"),
                            ("purchase", "Purchased"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="Resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_analytics",
                        to="Authentication.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "action"],
                        name="Resources_r_resourc_ba9ad6_idx",
                    ),
                    models.Index(
                        fields=["resource", "-created_at"],
                        name="Resources_r_resourc_090b1f_idx",
                    ),
                ],
            },
        ),
    ]
