# Generated by Django 5.1.7 on 2025-11-20 17:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0002_cafeteria_counselling_hostel_library_and_more"),
        (
            "Organisation",
            "0003_alter_board_created_on_alter_centre_created_on_and_more",
        ),
        ("Resources", "0004_remove_resourcevisibility_room_and_more"),
        ("Rooms", "0021_alter_defaultroom_room_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcevisibility",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="resourcevisibility",
            name="created_by",
        ),
        migrations.AddField(
            model_name="resource",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 21, 12, 969297)
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="edited_resources", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="admin_deps",
            field=models.ManyToManyField(blank=True, to="Institution.admindep"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="admissions",
            field=models.ManyToManyField(blank=True, to="Institution.admissions"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="boards",
            field=models.ManyToManyField(blank=True, to="Organisation.board"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="cafeterias",
            field=models.ManyToManyField(blank=True, to="Institution.cafeteria"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="career_offices",
            field=models.ManyToManyField(blank=True, to="Institution.careeroffice"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="centres",
            field=models.ManyToManyField(blank=True, to="Organisation.centre"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="committees",
            field=models.ManyToManyField(blank=True, to="Organisation.committee"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="counsellings",
            field=models.ManyToManyField(blank=True, to="Institution.counselling"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="departments",
            field=models.ManyToManyField(blank=True, to="Organisation.department"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="direct_message_rooms",
            field=models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="divisions",
            field=models.ManyToManyField(blank=True, to="Organisation.division"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="faculties",
            field=models.ManyToManyField(blank=True, to="Institution.faculty"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="finances",
            field=models.ManyToManyField(blank=True, to="Institution.finance"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="health_services",
            field=models.ManyToManyField(blank=True, to="Institution.healthservices"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="hostels",
            field=models.ManyToManyField(blank=True, to="Institution.hostel"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="hrs",
            field=models.ManyToManyField(blank=True, to="Institution.hr"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="icts",
            field=models.ManyToManyField(blank=True, to="Institution.ict"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="inst_departments",
            field=models.ManyToManyField(blank=True, to="Institution.instdepartment"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institutes",
            field=models.ManyToManyField(blank=True, to="Organisation.institute"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institution_branches",
            field=models.ManyToManyField(blank=True, to="Institution.instbranch"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="institutions",
            field=models.ManyToManyField(blank=True, to="Institution.institution"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="legals",
            field=models.ManyToManyField(blank=True, to="Institution.legal"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="libraries",
            field=models.ManyToManyField(blank=True, to="Institution.library"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="marketings",
            field=models.ManyToManyField(blank=True, to="Institution.marketing"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="Organisation.organisation"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="organistion_branches",
            field=models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="programmes",
            field=models.ManyToManyField(blank=True, to="Institution.programme"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="programs",
            field=models.ManyToManyField(blank=True, to="Organisation.program"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="projects",
            field=models.ManyToManyField(blank=True, to="Organisation.project"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="registrar_offices",
            field=models.ManyToManyField(blank=True, to="Institution.registraroffice"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="sections",
            field=models.ManyToManyField(blank=True, to="Organisation.section"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="securities",
            field=models.ManyToManyField(blank=True, to="Institution.security"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="student_affairs",
            field=models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="support_services",
            field=models.ManyToManyField(blank=True, to="Institution.supportservices"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="teams",
            field=models.ManyToManyField(blank=True, to="Organisation.team"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="transports",
            field=models.ManyToManyField(blank=True, to="Institution.transport"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="units",
            field=models.ManyToManyField(blank=True, to="Organisation.unit"),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="vc_offices",
            field=models.ManyToManyField(blank=True, to="Institution.vcoffice"),
        ),
        migrations.CreateModel(
            name="VisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("only_me", "Only Me"),
                            ("course", "Your Course or Class"),
                            ("faculty", "Your Faculty or School"),
                            ("institutional", "Your Institution"),
                            ("organisational", "Your Organisation"),
                            ("group", "Your Group or Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Resources.resource",
                    ),
                ),
            ],
        ),
    ]
