# Generated by Django 5.1.7 on 2025-11-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0005_remove_resourcevisibility_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 20, 20, 36, 37, 276130)
            ),
        ),
    ]
