# Generated by Django 5.1.7 on 2025-11-20 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institution", "0003_otherinstitutionunit"),
        (
            "Organisation",
            "0005_alter_board_created_on_alter_centre_created_on_and_more",
        ),
        ("Resources", "0006_alter_resource_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcevisibility",
            name="other_institution_units",
            field=models.ManyToManyField(
                blank=True, to="Institution.otherinstitutionunit"
            ),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="other_organisation_units",
            field=models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 1, 10, 0, 847442)
            ),
        ),
    ]
