# Generated by Django 5.2.11 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0006_resource_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="allow_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="resources/covers"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Resource auto-hides after this time", null=True
            ),
        ),
    ]
