# Generated by Django 5.1.7 on 2025-11-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0007_resourcevisibility_other_institution_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 4, 43, 557819)
            ),
        ),
    ]
