# Generated by Django 5.1.7 on 2025-11-21 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0008_alter_resource_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 21, 10, 13, 14, 89126)
            ),
        ),
    ]
