# Generated by Django 5.1.7 on 2025-11-21 10:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0012_alter_author_created_on_alter_editor_created_on_and_more",
        ),
        ("Resources", "0009_alter_resource_created_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visibilitylog",
            name="changed_at",
        ),
        migrations.RemoveField(
            model_name="visibilitylog",
            name="old_visibility",
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="changed_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="previous_visibility",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_resources",
                to="Authentication.profile",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_resources",
                to="Authentication.profile",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="resource",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="edited_resources", to="Authentication.profile"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("only_me", "Only Me"),
                    ("rooms", "Rooms"),
                    ("default_rooms", "Default Rooms"),
                    ("direct_message_rooms", "Direct Message Rooms"),
                    ("organisations", "Organisations"),
                    ("organisation_branches", "Organisation Branches"),
                    ("departments", "Departments"),
                    ("sections", "Sections"),
                    ("committees", "Committees"),
                    ("units", "Units"),
                    ("programs", "Programs"),
                    ("projects", "Projects"),
                    ("centres", "Centres"),
                    ("teams", "Teams"),
                    ("divisions", "Divisions"),
                    ("boards", "Boards"),
                    ("institutes", "Institutes"),
                    ("other_organisation_units", "Other Organisation Units"),
                    ("institutions", "Institutions"),
                    ("institution_branches", "Institution Branches"),
                    ("faculties", "Faculties"),
                    ("vc_offices", "VC Offices"),
                    ("inst_departments", "Institution Departments"),
                    ("admin_deps", "Admin Departments"),
                    ("programmes", "Programmes"),
                    ("hrs", "HRs"),
                    ("admissions", "Admissions"),
                    ("health_services", "Health Services"),
                    ("securities", "Securities"),
                    ("student_affairs", "Student Affairs"),
                    ("support_services", "Support Services"),
                    ("finances", "Finances"),
                    ("marketings", "Marketings"),
                    ("legals", "Legals"),
                    ("icts", "ICTs"),
                    ("career_offices", "Career Offices"),
                    ("counsellings", "Counsellings"),
                    ("registrar_offices", "Registrar Offices"),
                    ("transports", "Transports"),
                    ("libraries", "Libraries"),
                    ("hostels", "Hostels"),
                    ("cafeterias", "Cafeterias"),
                    ("other_institution_units", "Other Institution Units"),
                    ("public", "Public"),
                ],
                default="public",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="resourcevisibility",
            name="resource",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_visibility",
                to="Resources.resource",
            ),
        ),
        migrations.AlterField(
            model_name="visibilitylog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_changed_logs",
                to="Authentication.profile",
            ),
        ),
        migrations.AlterField(
            model_name="visibilitylog",
            name="new_visibility",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AlterField(
            model_name="visibilitylog",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_logs",
                to="Resources.resource",
            ),
        ),
    ]
