# Generated by Django 5.1.7 on 2025-11-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0012_alter_author_created_on_alter_editor_created_on_and_more",
        ),
        ("Resources", "0010_remove_visibilitylog_changed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="res_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="users_with_access",
            field=models.ManyToManyField(blank=True, to="Authentication.profile"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="res_file",
            field=models.FileField(blank=True, null=True, upload_to="resources/"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="res_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=5000)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_links",
                        to="Authentication.profile",
                    ),
                ),
            ],
        ),
    ]
