# Generated by Django 5.1.7 on 2025-11-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0011_resource_res_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="res_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
