# Generated by Django 5.1.7 on 2025-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0012_alter_resource_res_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="res_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
