# Generated by Django 5.1.7 on 2025-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0013_alter_resource_res_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="res_file",
            field=models.FileField(blank=True, null=True, upload_to="resources/docs"),
        ),
    ]
