# Generated by Django 5.1.7 on 2025-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0014_alter_resource_res_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcevisibility",
            name="expiry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="visibilitylog",
            name="new_visibility",
        ),
        migrations.RemoveField(
            model_name="visibilitylog",
            name="previous_visibility",
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="new_visibility",
            field=models.ManyToManyField(
                related_name="new_visibility_logs", to="Resources.resourcevisibility"
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="previous_visibility",
            field=models.ManyToManyField(
                null=True,
                related_name="previous_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
    ]
