# Generated by Django 5.1.7 on 2025-11-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        ("Resources", "0015_resourcevisibility_expiry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilitylog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visibility_changed_logs",
                to="Authentication.profile",
            ),
        ),
        migrations.RemoveField(
            model_name="visibilitylog",
            name="new_visibility",
        ),
        migrations.RemoveField(
            model_name="visibilitylog",
            name="previous_visibility",
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="new_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
        migrations.AddField(
            model_name="visibilitylog",
            name="previous_visibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_visibility_logs",
                to="Resources.resourcevisibility",
            ),
        ),
    ]
