# Generated by Django 5.1.7 on 2025-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0032_event_activate_feedback_event_attendees_viewable_and_more"),
        ("Resources", "0016_alter_visibilitylog_changed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="price_tag",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name="resourcevisibility",
            name="events",
            field=models.ManyToManyField(blank=True, to="Events.event"),
        ),
    ]
