# Generated by Django 5.1.7 on 2025-12-04 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0021_rename_user_instadmin_staff_and_more"),
        ("Events", "0032_event_activate_feedback_event_attendees_viewable_and_more"),
        (
            "Institution",
            "0005_admindep_staff_admissions_staff_cafeteria_staff_and_more",
        ),
        ("Organisation", "0010_alter_board_members_alter_centre_members_and_more"),
        ("Resources", "0017_resource_price_tag_resourcevisibility_events"),
        ("Rooms", "0069_defaultroom_operation_state_and_more"),
        ("Specialization", "0023_specializationroom_operation_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
        migrations.CreateModel(
            name="MainVisibilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_visibility_changed_logs",
                        to="Authentication.profile",
                    ),
                ),
                (
                    "new_visibility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_main_visibility_logs",
                        to="Resources.resourcevisibility",
                    ),
                ),
                (
                    "previous_visibility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_main_visibility_logs",
                        to="Resources.resourcevisibility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visibility",
            fields=[
                (
                    "main_entity",
                    models.CharField(
                        choices=[
                            ("comrade", "Comrade"),
                            ("creator", "Creator"),
                            ("admins", "Entity Admins"),
                            ("admins_moderators", "Admins and Moderators"),
                            ("resources", "Resources"),
                            ("rooms", "Rooms"),
                            ("default_rooms", "Default Rooms"),
                            ("direct_message_rooms", "Direct Message Rooms"),
                            ("organisations", "Organisations"),
                            ("organisation_branches", "Organisation Branches"),
                            ("departments", "Departments"),
                            ("sections", "Sections"),
                            ("committees", "Committees"),
                            ("units", "Units"),
                            ("programs", "Programs"),
                            ("projects", "Projects"),
                            ("centres", "Centres"),
                            ("teams", "Teams"),
                            ("divisions", "Divisions"),
                            ("boards", "Boards"),
                            ("institutes", "Institutes"),
                            ("other_organisation_units", "Other Organisation Units"),
                            ("institutions", "Institutions"),
                            ("institution_branches", "Institution Branches"),
                            ("faculties", "Faculties"),
                            ("vc_offices", "VC Offices"),
                            ("inst_departments", "Institution Departments"),
                            ("admin_deps", "Admin Departments"),
                            ("programmes", "Programmes"),
                            ("hrs", "HRs"),
                            ("admissions", "Admissions"),
                            ("health_services", "Health Services"),
                            ("securities", "Securities"),
                            ("student_affairs", "Student Affairs"),
                            ("support_services", "Support Services"),
                            ("finances", "Finances"),
                            ("marketings", "Marketings"),
                            ("legals", "Legals"),
                            ("icts", "ICTs"),
                            ("career_offices", "Career Offices"),
                            ("counsellings", "Counsellings"),
                            ("registrar_offices", "Registrar Offices"),
                            ("transports", "Transports"),
                            ("libraries", "Libraries"),
                            ("hostels", "Hostels"),
                            ("cafeterias", "Cafeterias"),
                            ("other_institution_units", "Other Institution Units"),
                            ("public", "Public"),
                        ],
                        default="resource",
                        max_length=1000,
                    ),
                ),
                (
                    "visibility_code",
                    models.CharField(
                        max_length=2000, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True)),
                ("expiry_time", models.DateTimeField(blank=True)),
                (
                    "admin_deps",
                    models.ManyToManyField(blank=True, to="Institution.admindep"),
                ),
                (
                    "admissions",
                    models.ManyToManyField(blank=True, to="Institution.admissions"),
                ),
                ("boards", models.ManyToManyField(blank=True, to="Organisation.board")),
                (
                    "cafeterias",
                    models.ManyToManyField(blank=True, to="Institution.cafeteria"),
                ),
                (
                    "career_offices",
                    models.ManyToManyField(blank=True, to="Institution.careeroffice"),
                ),
                (
                    "centres",
                    models.ManyToManyField(blank=True, to="Organisation.centre"),
                ),
                (
                    "committees",
                    models.ManyToManyField(blank=True, to="Organisation.committee"),
                ),
                (
                    "counsellings",
                    models.ManyToManyField(blank=True, to="Institution.counselling"),
                ),
                (
                    "default_rooms",
                    models.ManyToManyField(blank=True, to="Rooms.defaultroom"),
                ),
                (
                    "departments",
                    models.ManyToManyField(blank=True, to="Organisation.department"),
                ),
                (
                    "direct_message_rooms",
                    models.ManyToManyField(blank=True, to="Rooms.directmessageroom"),
                ),
                (
                    "divisions",
                    models.ManyToManyField(blank=True, to="Organisation.division"),
                ),
                ("events", models.ManyToManyField(blank=True, to="Events.event")),
                (
                    "faculties",
                    models.ManyToManyField(blank=True, to="Institution.faculty"),
                ),
                (
                    "finances",
                    models.ManyToManyField(blank=True, to="Institution.finance"),
                ),
                (
                    "health_services",
                    models.ManyToManyField(blank=True, to="Institution.healthservices"),
                ),
                (
                    "hostels",
                    models.ManyToManyField(blank=True, to="Institution.hostel"),
                ),
                ("hrs", models.ManyToManyField(blank=True, to="Institution.hr")),
                ("icts", models.ManyToManyField(blank=True, to="Institution.ict")),
                (
                    "inst_departments",
                    models.ManyToManyField(blank=True, to="Institution.instdepartment"),
                ),
                (
                    "institutes",
                    models.ManyToManyField(blank=True, to="Organisation.institute"),
                ),
                (
                    "institution_branches",
                    models.ManyToManyField(blank=True, to="Institution.instbranch"),
                ),
                (
                    "institutions",
                    models.ManyToManyField(blank=True, to="Institution.institution"),
                ),
                ("legals", models.ManyToManyField(blank=True, to="Institution.legal")),
                (
                    "libraries",
                    models.ManyToManyField(blank=True, to="Institution.library"),
                ),
                (
                    "marketings",
                    models.ManyToManyField(blank=True, to="Institution.marketing"),
                ),
                (
                    "organisations",
                    models.ManyToManyField(blank=True, to="Organisation.organisation"),
                ),
                (
                    "organistion_branches",
                    models.ManyToManyField(blank=True, to="Organisation.orgbranch"),
                ),
                (
                    "other_institution_units",
                    models.ManyToManyField(
                        blank=True, to="Institution.otherinstitutionunit"
                    ),
                ),
                (
                    "other_organisation_units",
                    models.ManyToManyField(blank=True, to="Organisation.otherorgunit"),
                ),
                (
                    "programmes",
                    models.ManyToManyField(blank=True, to="Institution.programme"),
                ),
                (
                    "programs",
                    models.ManyToManyField(blank=True, to="Organisation.program"),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, to="Organisation.project"),
                ),
                (
                    "registrar_offices",
                    models.ManyToManyField(
                        blank=True, to="Institution.registraroffice"
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="main_visibility_resources",
                        to="Resources.resource",
                    ),
                ),
                ("rooms", models.ManyToManyField(blank=True, to="Rooms.room")),
                (
                    "sections",
                    models.ManyToManyField(blank=True, to="Organisation.section"),
                ),
                (
                    "securities",
                    models.ManyToManyField(blank=True, to="Institution.security"),
                ),
                (
                    "student_affairs",
                    models.ManyToManyField(blank=True, to="Institution.studentaffairs"),
                ),
                (
                    "support_services",
                    models.ManyToManyField(
                        blank=True, to="Institution.supportservices"
                    ),
                ),
                ("teams", models.ManyToManyField(blank=True, to="Organisation.team")),
                (
                    "transports",
                    models.ManyToManyField(blank=True, to="Institution.transport"),
                ),
                ("units", models.ManyToManyField(blank=True, to="Organisation.unit")),
                (
                    "users_with_access",
                    models.ManyToManyField(blank=True, to="Authentication.profile"),
                ),
                (
                    "vc_offices",
                    models.ManyToManyField(blank=True, to="Institution.vcoffice"),
                ),
            ],
        ),
    ]
