# Generated by Django 5.1.7 on 2026-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resources", "0018_rename_links_link_mainvisibilitylog_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="visibility",
            name="operation_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("under_review", "Under Review"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sensored", "Sensored"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
